### ISSUE TITLE
Add Support to match PyCharm's wrap always and chop down

### ISSUE THREAD

**Issue by mikelane** [timothycrosley/isort#1001]
I'd love it if there was an option that matched pycharm:

```python
from something import wowzer
from foo import (
    bar,
    baz,
)
```
Single line helps with identifying changes in git. The option could perhaps be `force_vertical_hanging_indent=True`.

**Comment by Zarathustra2** [comment]
Hey @mikelane,

I think you are looking for **Vertical Hanging Indent**, see option 3 here: [https://github.com/timothycrosley/isort#multi-line-output-modes](https://github.com/timothycrosley/isort#multi-line-output-modes)

**Comment by mikelane** [comment]
@Zarathustra2, I definitely am looking for vertical hanging indent. However, I'd like that to be forced whether the line is too long or not. Right now, assuming you have 88 or 110 character line length, you'd have this if you use :
```python
from something import wowzer
from foo import bar, baz
```
And if you changed the line length to be shorter than the foo imports, you'd get this:
```python
from something import (
    wowzer,
)
from foo import (
    bar,
    baz,
)
```
Neither option is what makes sense, IMO, when `multi-line-output=3` is set.

**Comment by timothycrosley** [comment]
@mikelane I think you just want to set `force_grid_wrap` to 2:


From the docs:

force_grid_wrap: Force from imports to be grid wrapped regardless of line length, where the value given is the number of imports allowed before wrapping occurs.
