### ISSUE TITLE
isort seems to be affected by the environment. (ex: os, virtualenv)

### ISSUE THREAD

**Issue by choich** [timothycrosley/isort#1007]
I don't think this problem is completely fixed. #725 
My local (mac os + pipenv) and jenkins ci's isort works differently.
It also works differently inside and outside pipenv on the same mac local.
Can you confirm this?

If I run isort outside of pipenv in local, the files are fixed.
![스크린샷 2019-09-04 오전 10 46 40](https://user-images.githubusercontent.com/13517510/64219676-5cc76880-cf01-11e9-9d35-14bb0e2f1aba.png)

If I work inside pipenv shell after running isort outside pipenv, the file is fixed again.
![스크린샷 2019-09-04 오전 10 47 05](https://user-images.githubusercontent.com/13517510/64219740-ac0d9900-cf01-11e9-995d-b786567be87b.png)

**Comment by schumannd** [comment]
I have the same issue.

Isort sorts differently on different machines despite haveing the same version (4.3.4) and config:

Diff produced:

```
 from datetime import datetime
 from tempfile import TemporaryFile

-import ffmpeg
 import uuid
 from django.core.exceptions import ValidationError
 from django.core.files import File
 from django.db import models
 from django.forms import model_to_dict

+import ffmpeg
 from myapp.constants import EXPIRATION_DAYS, EXPIRATION_REPEAT, MP3_HEADERS
 from myproj.constants import A, B
 from myproj.settings import BASE_DIR, LOCAL
```

`.isort.cfg`
```
[settings]
line_length=160
multi_line_output=1
skip_glob=**/migrations/**.py
known_django = django
order_by_type = True
known_standard_library= datetime, pytz, json, re, string, time, unittest, 
known_third_party=django, rest_framework, raven, celery, model_mommy, uuid, request, pdfkit, pandas, matplotlib
known_first_party=myapp, myapp1,...
```

**Comment by Siecje** [comment]
@schumannd Are the Python versions the same?

**Comment by timothycrosley** [comment]
Generally, this is simply because the virtual env is different. Which was an intentional bit of magic (detect if something is third party based on if it is installed in virtual env).

**Comment by timothycrosley** [comment]
This should be fixed for the 5.0.0 release in spirit via this ticket: https://github.com/timothycrosley/isort/issues/1147

**Comment by ryan-faculty** [comment]
Having same issue, using `nox` vs. not using `nox` to run `isort`

**Comment by edgarrmondragon** [comment]
@ryan-faculty I'm having the same problem. Were you able to fix it?
