### ISSUE TITLE
Option to sort numbers in imports when written as words

### ISSUE THREAD

**Issue by martinburchell** [timothycrosley/isort#1011]
How easy would it be to add an option to preserve the order of something like:

```
from checkers import (
   ZERO_TO_ONE_CHECKER,
   ZERO_TO_TWO_CHECKER,
   ZERO_TO_FIVE_CHECKER,
)
```

currently this will get sorted as:

```
from checkers import (
   ZERO_TO_FIVE_CHECKER,
   ZERO_TO_ONE_CHECKER,
   ZERO_TO_TWO_CHECKER,
)
```

Maybe a pre-processing step to substitute the words zero, one, two, ..., nine with 0,1,2, ..., 9 
and don't attempt to handle anything greater than nine. 

There would be i18n considerations.

**Comment by timothycrosley** [comment]
Shouldn't be too difficult, primarily involving editing the sorting functions in sorting.py.
I would accept an optional sort that allowed this.

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
Since there hasn't been much movement on this, and I've never heard this as a request from additional users I'm closing, but  feel free to open a new similar issue if this is still something you want.

Thanks!

~Timothy

**Comment by martinburchell** [comment]
@timothycrosley Sure, it's not a high priority for us right now.
