### ISSUE TITLE
--filter-files broken for absolute paths

### ISSUE THREAD

**Issue by basepi** [timothycrosley/isort#1013]
I found this bug by using PyCharm FileWatchers. I was passing `$FilePath$` to `isort`, which was, as a result, not obeying my `skip` settings in [setup.cfg](https://github.com/elastic/apm-agent-python/blob/master/setup.cfg#L22-L34). Adding `--filter-files` made it so `isort` was skipping *all* files.

The fix for me was to pass in a relative path, `$FilePathRelativeToProjectRoot$`. However, I still think that absolute paths should be filtered properly, based on the current working directory.

```
[9:40:44] [basepi@corellia] [~/src/apm-agent-python] [master]
± pwd
/Users/basepi/src/apm-agent-python

[9:40:52] [basepi@corellia] [~/src/apm-agent-python] [master]
± /usr/local/bin/isort --filter-files /Users/basepi/src/apm-agent-python/elasticapm/base.py
Skipped 1 files

[9:40:55] [basepi@corellia] [~/src/apm-agent-python] [master]
± /usr/local/bin/isort --filter-files elasticapm/base.py
```

isort version 4.3.21

**Comment by timothycrosley** [comment]
Closing as this is likely resolved in the 5.x.x series. Feel free to open a new issue if this persists for you.

Thanks!

~Timothy
