### ISSUE TITLE
Option to not sort alphabetically within from

### ISSUE THREAD

**Issue by fgblomqvist** [timothycrosley/isort#1014]
At the moment, there doesn't seem to be an option to avoid changing `from x import y, z, k` to `from x import k, y, z`.

This is pretty annoying since in larger shared projects it's harder to enforce that people add their imports in complete alphabetical order _inside_ each from, and therefore, when I run isort, it throws things around making it hard for people to see in the commit which import I actually added/removed.

**Comment by DylanYoung** [comment]
Just do a check on the committed code so that these changes don't happen?  In modern setups all of this is done through build systems (pipelines), so this shouldn't be any harder or easier than maintaining any other style guides for the project.

**Comment by fgblomqvist** [comment]
Well it wouldn't be hard to automate it if isort actually allowed PEP8 sorting (3 sections instead of 4), but until it does, it will still require manual work after using the tool.

**Comment by DylanYoung** [comment]
It does. Use the flag to remove space between sections.

**Comment by DylanYoung** [comment]
It's not in the wiki though,  check out my other issue for the flag. It's somewhere near the bottom of the README as well.

**Comment by fgblomqvist** [comment]
What you're referring to is in the wiki. I suppose it does what I want now that I think about it. Nonetheless, it's still a bit of a hassle to have the whole team setup automatic running of isort (e.g. upon save or something). It would be a nice stepping stone to have the option that I originally requested, until we transition.

**Comment by DylanYoung** [comment]
You can do it with a precommit hook. I'll let you know our config once
we've set it up for our team.  Still getting a few other fixes that are
blockers for us first.
