### ISSUE TITLE
isort line-wraps later when multiple imports, making lines too long

### ISSUE THREAD

**Issue by davidparsson** [timothycrosley/isort#1015]
Should not `isort` always wrap after `import` when that is required to keep lines within the line length? When there are more than one import and Hanging Indent mode is used, that does not seem to be the case.

Or, in other words, should not `isort` always wrap after `import` in the example below?

```$ isort -w 25 -m 2 tmp.py```

Contents of `tmp.py`:
```
from package1 import first_package, \
    second_package
from package2 import \
    first_package

#                       |
#               25 characters
```

**Comment by tegkhanna** [comment]
This bug is only prevalent for hanging indent I believe. Should I go ahead and fix it?

**Comment by timothycrosley** [comment]
This is fixed into develop and will make it's way into the 5.0.0 release of isort.

Thanks everyone!
