### ISSUE TITLE
forced_together option or alternative for keeping top-level modules together

### ISSUE THREAD

**Issue by DylanYoung** [timothycrosley/isort#1021]
I'd like to see an equivalent of the `forced_separate` option called `forced_together` that takes section names and removes spaces between them.  

Here is the scenario:

I have two modules that I want to view as "the same" (they are separate for historic reasons only).  The problem is that isort lifts the `imports` above the `from` imports, messing up the order:

    import foo
    from blah import ... 
    from foo import ...

Which is ugly as sin. 

An alternative would be an option to only lift the bare `imports` for top-level modules (`--group-toplevel'), which would change the output to:

    from foo import ...
    import foo
    from blah import ...

**Comment by DylanYoung** [comment]
UPDATE: Just found the `no_lines_before` option!  This should work.

**Comment by DylanYoung** [comment]
FYI: it's missing from the wiki

**Comment by DylanYoung** [comment]
I still think a more generalized option, subgroup by top level module, or something to that effect would be valuable.   That way imports from the same module within a section would stay together, but the "bare" imports would still float to the top.

**Comment by timothycrosley** [comment]
Relooking at this now, I think this is now covered by this documentation: https://github.com/timothycrosley/isort#controlling-how-isort-sections-from-imports
