### ISSUE TITLE
isort 5.0

### ISSUE THREAD

**Issue by mkurnikov** [timothycrosley/isort#1024]
I'm an author of https://github.com/timothycrosley/isort/pull/951. 

@timothycrosley What do you think, for 5.0, about
1. Drop all config options for different styles of import formatting, except one compatible with black. 
2. Adopt https://github.com/Instagram/LibCST. I'm not sure about 2.7 support for it (as for 2.7 codebase import formatting, not execution), but I suspect that if it's 2/3 compatible codebase - it should work. But there's a risk of accidentally breaking support for 2.7 only codebases. 

In the current state of different config options, and parso library - it's intractable, at least for me. 

It will probably make it easier for 
1. Support sorting imports under non-global scopes.
2. If there's a code inside the imports, we can disable reorganizing, and only sort alphabetically inside sections.

**Comment by timothycrosley** [comment]
@mkurnikov,

I've done a lot of thinking about this and I've updated isort to support both of the requested features:

1. Support sorting imports under non-global scopes.
2. If there's a code inside the imports, we can disable reorganizing, and only sort alphabetically inside sections.

But I've done it without switching to AST style parsing. I realized that there are fairly strict requirements around import lines, making them very easy to identify with confidence separate from other code blocks, without using AST parsing. Doing so is also faster, and allows isort to remain immune to ast changes (such as the walrus operator, which broke other formatters if used across Python versions, but isort kept working). I'd be very happy to get your feedback and testing on this.

Thanks!

~Timothy
