### ISSUE TITLE
isort merges different aliases

### ISSUE THREAD

**Issue by srittau** [timothycrosley/isort#1037]
Consider the following file

```python
import datetime
import datetime as datetime
import datetime as dt
import datetime as dt2
```

This will get merged into just

```python
import datetime as dt
```

But apart from the first two lines, these are all different aliases for the same import and are most likely there for a reason. I don't think isort should merge them (except for possibly the first two lines).

**Comment by timothycrosley** [comment]
This is fixed in develop and will make its way out in the 5.0.0 release.

Thanks!

~Timothy
