### ISSUE TITLE
Return non-zero exit code for --diff for non-empty diff

### ISSUE THREAD

**Issue by mtlynch** [timothycrosley/isort#1039]
It would be great if the `--diff` flag caused `isort` to return a non-zero exit code when it produces a diff. This would make `isort`'s behavior consistent with the standard `diff` utility.

It would also make it easier to use `isort --diff` as a git pre-commit hook. I know that there's `--check-only`, but I'd like to see what specifically is incorrect in my files. `--check-only` produces an error message that's a bit opaque.

## Repro steps

Give `isort` unsorted import with the `--diff` flag:

```bash
$ printf "import sys, os\n" | isort --diff -
--- :before     2019-10-14 20:32:53.497965
+++ :after      2019-10-14 20:32:53.497977
@@ -1 +1,2 @@
-import sys, os
+import os
+import sys
```

## Expected behavior

isort returns a non-zero exit code after producing a non-empty diff.

```bash
$ printf "import sys, os\n" | isort --diff -
--- :before     2019-10-14 20:32:53.497965
+++ :after      2019-10-14 20:32:53.497977
@@ -1 +1,2 @@
-import sys, os
+import os
+import sys
$ echo $?
1 <<< or any other non-zero exit code
```

## Actual behavior

isort returns a zero exit code after producing a non-empty diff.

```bash
$ printf "import sys, os\n" | isort --diff -
--- :before     2019-10-14 20:32:53.497965
+++ :after      2019-10-14 20:32:53.497977
@@ -1 +1,2 @@
-import sys, os
+import os
+import sys
$ echo $?
0

```

**Comment by hwchase17** [comment]
if you combine `--check-only` with `--diff` you get both the error code and the nice output!

**Comment by mtlynch** [comment]
Thanks for the tip @hwchase17! 

I didn't realize those flags were combinable. I'd still like to see the exit code on `--diff` by itself, but this is a great workaround.

**Comment by timothycrosley** [comment]
While I agree that some may find the behaviour more intuitive, others may not. And, the current flags already have established interaction. I did a quick check to see how black behaved, and it behaved in the same manor as isort, so I'll be keeping this the same for now. I do appreciate you raising this issue, and I believe it acts as great documentation for others that encounter the same unexpected behaviour.

Thanks!

~Timothy
