### ISSUE TITLE
Python package handled differently on OSX and linux

### ISSUE THREAD

**Issue by Sytten** [timothycrosley/isort#1047]
I found another bug in the latest isort version (4.3.21).
If you have you dependencies listed in the `setup.py` and you do `pip install .`, isort on OSX will consider that import starting with your package name are local dependencies while on linux it's the contrary... The OSX behavior is the right one.

**Comment by timothycrosley** [comment]
Hi @Sytten,

Thanks for reporting! While I believe you encountered this issue, I simply have not been able to reproduce. I am looking into some different approaches for handling local import identification for isort 5.0.0 that should be able to have very exact and reproducible behaviour.

Thanks!

~Timothy

**Comment by Sytten** [comment]
Hum weird, I am able to reproduce this issue 100% of the time. While the code is not open source, I can create a sample repo if you want. This issue only applies to libraries that use a setup.py and install the dependencies using `pip install .` because this means the package is copied to the virtual env and is thus not considered "local". This is probably a "bug"/unexpected behavior in python itself (aka the lookup order is different).
