### ISSUE TITLE
Ability to merge configs

### ISSUE THREAD

**Issue by pkulev** [timothycrosley/isort#1056]
Hello!
I'm trying to incorporate isort into CI flow of big monorepository that consists of several subprojects.
Subproject imports should have separate section, so I wanted to place .isort.cfg into the root of repo and place configs into each subproject to override known_currentservice and some subproject related things, but seems that closest config was used. How can I override root config's values?

Thanks in advance!

**Comment by pkulev** [comment]
@timothycrosley, could you please say something, I'm stuck :(

**Comment by timothycrosley** [comment]
Hi @pkulev,

Would running isort multiple times, once per a sub directory be an option?

for example:

`isort directory_with_config1/'
'isort directory_with_config2/'
'...'

I think this would be the best way to guarantee consistency.
Sorry for the delay in response!

Thanks!

~Timothy
