### ISSUE TITLE
1st party vs 3rd party

### ISSUE THREAD

**Issue by jarednielsen** [timothycrosley/isort#1057]
What is the difference between a first-party and third-party library?

**Comment by asottile** [comment]
say you're working on an application which uses the top level module name `foo` -- imports `from foo import ...` or `import foo.bar` are "first party" -- they come from the application itself

now say one of your modules depends on say `pytest`, pytest is a "third party" module

**Comment by timothycrosley** [comment]
@asottile is correct,

Thanks for asking, and hopefully this explanation was helpful! Marking it as a question so that in the future I can add it to a FAQ page.

Thanks!

~Timothy

**Comment by zyxue** [comment]
how does isort tell apart first party vs third party?

isort usually works out of the box, but I'm using bazel for my current project, and isort seems to be confused and lump my current project (first party) and third party ones altogether. I wonder if I could configure isort somehow to tell them apart.

**Comment by anirudnits** [comment]
@zyxue Hello, you can configure isort to recognize modules as first party by using the `known_first_party` option in the config file or `-p` or `--project` CLI flag. https://github.com/PyCQA/isort/blob/develop/docs/configuration/options.md#known-first-party.

Hope this helps.

**Comment by zyxue** [comment]
@anirudnits , just gave `known_first_party=myapp` a try and it seems to work well. Thank you!

**Comment by zyxue** [comment]
Does isort have a concept of second party? E.g. a package not from the current application or pypi, but from another package being developed locally. This could have when in a repo with multiple applications.

**Comment by pozsa** [comment]
> Does isort have a concept of second party? E.g. a package not from the current application or pypi, but from another package being developed locally. This could have when in a repo with multiple applications.

That would count as a 3rd party package, even if developed by the same organization.
