### ISSUE TITLE
trailing-comma + use-parentheses repeatedly adds extra commas after comment

### ISSUE THREAD

**Issue by kapsh** [timothycrosley/isort#1059]
Using option `--trailing-comma` in combination with `--use-parentheses` repeatedly appends extra comma after comment if reformatting requires to add new line(s).

Example to show an idea (without configuration file, only these two options):
```
❯ cat imports.py
from distutils.spawn import find_executable  # pylint: disable=import-error, no-name-in-module

/tmp/isort
❯ isort -y -tc -up imports.py; cat imports.py
Fixing /tmp/isort/imports.py
from distutils.spawn import (
    find_executable)  # pylint: disable=import-error, no-name-in-module,

/tmp/isort
❯ isort -y -tc -up imports.py; cat imports.py
Fixing /tmp/isort/imports.py
from distutils.spawn import (
    find_executable)  # pylint: disable=import-error, no-name-in-module,,

/tmp/isort
❯ isort -y -tc -up imports.py; cat imports.py
Fixing /tmp/isort/imports.py
from distutils.spawn import (
    find_executable)  # pylint: disable=import-error, no-name-in-module,,,
```

**Comment by kapsh** [comment]
What I'm trying to do is create `black` compatible configuration for `isort`, and my full config file looks like this
```
[isort]
force_grid_wrap=0
include_trailing_comma=True
line_length=88
multi_line_output=3
use_parentheses=True
```
But I've narrowed down the issue to combination of include_trailing_comma and use_parentheses.

**Comment by kapsh** [comment]
I was wrong, it works in develop branch correctly. Still I prefer leave this issue open so others can learn that this will be fixed in future versions.

**Comment by timothycrosley** [comment]
Thanks for reporting @kapsh,
Closing now as part of preparing the 5.0.0 release.

Thanks!

~Timothy
