### ISSUE TITLE
--wrap-length prepends the line with a bad string

### ISSUE THREAD

**Issue by ibaguio** [timothycrosley/isort#1061]
isort version: 4.3.21
issue: using `--wrap-length` config adds the string `import \` at the end of the line

Note: 4.3.21 has an issue with --wrap-length via CLI parameter, as reported in #1060, for this issue to work, i've hotfixed my local isort to fix #1060 by wrapping the statement causing error with `int()`

Test files:

```
# test.py
def a_very_long_function_name_that_exceeds_the_normal_pep8_line_length():
    pass

# test2.py
from .test import a_very_long_function_name_that_exceeds_the_normal_pep8_line_length
```

after running the following command `isort -y test2.py --wrap-length=99` the output of test2.py will no be

```
# test2.py updated after isort
from .test import a_very_long_function_name_that_exceeds_the_normal_pep8_line_lengthimport \
```

notice that the string `import \` has been added to the end of the line, whereas running isort normally `isort -y test2.py` will yield

```
from .test import \
    a_very_long_function_name_that_exceeds_the_normal_pep8_line_length_of_79
```

**Comment by timothycrosley** [comment]
Thanks for reporting! I believe, this is an issue of validation and documentation, which has been improved in develop in preparation for isort 5.0.0 release. isort is an import only formatter. It is agnostic to any other line, such as the one presented in test.py above. Therefore, in general the line length should be specified with `-l`. If you want to set isort to wrap at a shorter length when seeing a longer line (say if it's going to wrap at all, wrap to 80 characters, but only wrap if it reaches a line over 100) that's where wrap_length comes in. See the original ticket that led to it's creation: https://github.com/timothycrosley/isort/issues/225. Therefore, I believe it only ever makes sense for wrap_length to be lower than line_length, and I've added validation and documentation toward that effect. 

Thanks!

~Timothy
