### ISSUE TITLE
Pylint integration

### ISSUE THREAD

**Issue by advance512** [timothycrosley/isort#1062]
Is there a version of isort that is a Pylint plugin, that integrates into running only Pylint, directly?
Pylint is now more tightly integrated into PyCharm and we're leaning towards running only Pylint, instead of the existing solution of running Pylint + Flake8 + isort.

**Comment by timothycrosley** [comment]
Pylint actually integrates isort directly, see: https://github.com/PyCQA/pylint/blob/master/pylint/__pkginfo__.py#L34.
