### ISSUE TITLE
poetry configuration invalid

### ISSUE THREAD

**Issue by mmerickel** [timothycrosley/isort#1063]
Tested with poetry 1.0.0b3 and 1.0.0b5 against current develop branch commit 6b8f57b8f64676ce2125e5b3c7bb7590539287c7.

```
❯ poetry install

[RuntimeError]
The Poetry configuration is invalid:
  - Additional properties are not allowed ('website' was unexpected)
```

**Comment by mmerickel** [comment]
pretty sure `homepage` is the right directive instead of `website`

**Comment by JacobHayes** [comment]
Think this can be closed after https://github.com/timothycrosley/isort/commit/cbb62cbc222511bc551c59301aa967c5407f20e8
