### ISSUE TITLE
Configuration in tox.ini conflicting with or being overridden by .isort.cfg further up the tree

### ISSUE THREAD

**Issue by Scotchester** [timothycrosley/isort#1064]
Hi there,

I have a situation where I'm trying to run isort via tox in a subproject within another project in my folder structure. I've set the isort settings in the subproject's `tox.ini` file, but it seems that the parent project's `.isort.cfg` is overriding that or somehow conflicting with it. If I copy the subproject out to a totally separate folder outside of the parent project, I get different results when running tox.

I found this page on the wiki that talks about settings prioritization, but it doesn't address how settings in tox.ini are prioritized: https://github.com/timothycrosley/isort/wiki/isort-Settings

Could someone clarify how this should work, and if my desired scenario is possible? Thanks!

**Comment by timothycrosley** [comment]
Hi @Scotchester, 

Currently in isort (4.x.x) config files are merged together to allow reuse of config variables. Most other tools don't due this, and while it does enable re-use, as in your case it seems to add more confusion that it is worth. In the soon to be released 5.0.0 version isort will no longer compose configs. And your example would work as expected.

Thanks!

~Timothy

**Comment by Scotchester** [comment]
Ahhh! Thanks so much for the clarification and for the forthcoming change, @timothycrosley!
