### ISSUE TITLE
Bug with noqa

### ISSUE THREAD

**Issue by Keats** [timothycrosley/isort#1065]
First thanks for the program, it does the right thing 99% of the time! The 1% is a bug I encountered with a file where I had to disable isort completely for it:

```py
#
# USER SIGNALS
#

from flask_login import user_logged_in, user_logged_out  # noqa

from flask_security.signals import (  # noqa
    password_changed as user_reset_password,  # noqa
    user_confirmed,  # noqa
    user_registered,  # noqa
)  # noqa

from flask_principal import identity_changed as user_identity_changed  # noqa
```

Running `isort --multi-line=3 --trailing-comma --force-grid-wrap=0 --combine-as --line-width 99 --recursive --apply` on it results in:

```py
#
# USER SIGNALS
#

from flask_login import user_logged_in, user_logged_out  # noqa
from flask_principal import identity_changed as user_identity_changed  # noqa
from flask_security.signals import user_confirmed  # noqa; noqa; noqa; noqa
from flask_security.signals import user_registered  # noqa
from flask_security.signals import password_changed as user_reset_password
```
One line has 4 noqa and the last one doesn't, failing flake8.

**Comment by timothycrosley** [comment]
Thanks for the kind words and reporting this problem! A fix has been completed, tested and merged. This bug should be fixed in the soon to be released 5.0.0 version.

Thanks!

~Timothy
