### ISSUE TITLE
Multi-line modes are being ignored.

### ISSUE THREAD

**Issue by julie777** [timothycrosley/isort#1066]
Regardless of the multi-line setting, either on the command line or in the config file "from x import"
lines always end up formated as mode 7.

from third_party import lib1, lib2, lib3, ...  # NOQA

This is also independent of the current format. I have tried formatting in various multi-line format for the source, and tried with different multi-line modes specified. The end result is always that the "from import" is compressed to a single line.

I am running version 4.3.21 of isort and python 3.7.

**Comment by julie777** [comment]
Upon further investigation, the cause of the problem is interaction between multi-line and line-width. Mode is ignored unless the line is longer than line-width.
This doesn't seem to make sense, as when a mode is chosen it seems logical to assume that all "from import" would be formatted that way. In my cause I was choosing mode 3 specifically to minimize diffs when committing changes to git.

**Comment by timothycrosley** [comment]
You can use the following setting, set to a small number, to get the behaviour you want:
```bash
  --wl WRAP_LENGTH, --wrap-length WRAP_LENGTH
                        Specifies how long lines that are wrapped should be,
                        if not set line_length is used. NOTE: wrap_length must
                        be LOWER than or equal to line_length.

```

Most people do not want wrapping, until the line is long, and this is the default of other common tools such as block. If you do isort does allow you to do that as well!

I hope this is helpful,

Thanks!

~Timothy
