### ISSUE TITLE
command line args for version and verbose are non-standard

### ISSUE THREAD

**Issue by julie777** [timothycrosley/isort#1067]
I don't know of a written standard, but for all the command line apps I have used 
   -v, --verbose is verbose output
   -V, --version is version output

For example from python:
-v     : verbose (trace import statements); also PYTHONVERBOSE=x
         can be supplied multiple times to increase verbosity
-V     : print the Python version number and exit (also --version)
         when given twice, print more information about the build

$ python -V
Python 3.7.5

**Comment by timothycrosley** [comment]
Thanks for reporting! This was an excellent time to raise this issue as command line flags are being reviewed for the breaking 5.0.0 release. I've updated develop to include this change which will make it out soon in 5.0.0.

Thanks!

~Timothy
