### ISSUE TITLE
bump version in git

### ISSUE THREAD

**Issue by omry** [timothycrosley/isort#1075]
To avoid confusion, can you bump the version in git?
This will help people that are installing from master differentiate between master and the latest stable version.
Since you are planning a 5.0.0 release, how about 5.0.0-dev1?

https://github.com/timothycrosley/isort/blob/c54b3dd4620f9b3e7ac127c583ecb029fb90f1b7/pyproject.toml#L3

**Comment by timothycrosley** [comment]
For sure! Done :) Sorry for any confusion the lack of a version bump caused.

~Timothy

**Comment by omry** [comment]
Thanks!
Another thing to consider is maybe to make a pre-release.
(https://www.python.org/dev/peps/pep-0440/#pre-releases)
Such packages are not installed automatically by users pip installing isort, except if they specify an exact package version or using --pre flag when pip installing.

This will make it much simpler for people to test the version in master.
Example of a package with pre-releases : [OmegaConf](https://pypi.org/project/omegaconf/#history).
