### ISSUE TITLE
Unnecessary Imports

### ISSUE THREAD

**Issue by hakancelik96** [timothycrosley/isort#1081]
When I ran [unimport](https://github.com/hakancelik96/unimport) on isort, I saw that there were unnecessary imports. I will remove unnecessary imports with the help of [unimport](https://github.com/hakancelik96/unimport) and then send my contribution.

**Comment by timothycrosley** [comment]
Fixed in develop, thank you!

unimport also looks useful!

**Comment by hakancelik96** [comment]
> Fixed in develop, thank you!
> 
> unimport also looks useful!

You're welcome, I'm glad you find unimport useful. We are working to release a new version when it's finished, I can send a new PR to use unimport on isort.
