### ISSUE TITLE
Isort hangs if a named pipe is present in the target directory

### ISSUE THREAD

**Issue by matys18** [timothycrosley/isort#1083]
### Issue

`isort` VERSION 4.3.21 seems to hang if a named pipe is present in the target directory when using the `--recursive` flag. Is this expected behavior? 🤔 

### How to reproduce with Python3.8 on Red Hat 7

1. Create an empty directory, eg: `mkdir /random`
2. Create a python file with some imports
3. Run `isort --recursive /random`, it succeeds ✅ 
4. Create a named pipe `mkfifo pipe`
5. Run `isort --recursive /random`, it fails ❗️

**Comment by timothycrosley** [comment]
Thanks for reporting!

This is fixed in develop and will make its way in the 5.0.0 release.

~Timothy
