### ISSUE TITLE
Deletes some comments before star import

### ISSUE THREAD

**Issue by andersk** [timothycrosley/isort#1091]
isort (commit fbe1ab9290f08521d39a929b516a973b14a53627 from `develop`) unexpectedly deletes some of these comments:

```diff
ERROR: /tmp/test.py Imports are incorrectly sorted and/or formatted.
--- /tmp/test.py:before	2020-01-07 17:36:54.859754
+++ /tmp/test.py:after	2020-01-07 17:37:18.481733
@@ -1,6 +1,4 @@
 # comment 1
 
 # comment 2
-# comment 3
-# comment 4
 from foo import *
```

**Comment by andersk** [comment]
This one may be the same as #787, which I guess has reappeared in `develop`.

**Comment by timothycrosley** [comment]
This is fixed in develop and will make its way out in the 5.0.0 release.

Thanks!

~Timothy
