### ISSUE TITLE
Document that config file options don't always match the cli names

### ISSUE THREAD

**Issue by therefromhere** [timothycrosley/isort#1094]
In 
https://github.com/timothycrosley/isort/wiki/isort-Settings#full-reference-of-isort-settings I think it would be good to have a note like:

> Please note, the settings options don't always match the long command line options.  eg `--force-single-line-imports` vs `force_single_line = True`

I was struggling to get .setup.cfg config working because I didn't read the wiki very carefully and assumed that the command line options mapped directly to the settings.

(just wanted to raise this before I added it to the wiki).

**Comment by timothycrosley** [comment]
I've now built extensive (mixed auto-manual) documentation on this exact subject for isort 5.0.0 here: https://timothycrosley.github.io/isort/docs/configuration/options/

Thanks!

~Timothy
