### ISSUE TITLE
Dev dependency identified as first party instead of third party

### ISSUE THREAD

**Issue by rommguy** [timothycrosley/isort#1098]
First, thank you very much for this great tool, it is super helpful.

We use poetry to install dependencies, and we see a this bug - 
Packages defined in our pyproject.toml as dev dependencies are identified as first party instead of first party. 
However, they are external to the project and are actually third party

we use isort version 4.3.21 on OSX

**Comment by toumorokoshi** [comment]
You may want to see #1104 as well, I believe this is for similar reasons.

**Comment by timothycrosley** [comment]
This should be fixed for the 5.0.0 release in spirit via this ticket: https://github.com/timothycrosley/isort/issues/1147
