### ISSUE TITLE
isort deletes 2 lines of 3 line import with a comment containing parentheses

### ISSUE THREAD

**Issue by wlcx** [timothycrosley/isort#1103]
OS: Microsoft Windows [Version 10.0.18363.592]
Python: 3.7.4
Isort: 4.3.21 & 8ada14e (5.0.0, latest master)

When run on a file containing an import split across 3 lines, with a comment on the first line containing parentheses, isort deletes the top two lines.

Example file:
```
from foo import ( # (some text in brackets)
    bar,
)
```

command run: `isort example.py`

Result:
```

    bar,
)
```

If there are no parens in the comment, it works as expected:
```
from foo import ( # some text not in brackets
    bar,
)
```
is formatted to:
```
from foo import bar  # some text not in brackets

```

This is a bit of a diabolical case, I appreciate, but is definitely not right!

Thanks,
Sam

**Comment by timothycrosley** [comment]
Thanks for reporting! This is now fixed in develop and will make it's way out in the 5.0.0 release
