### ISSUE TITLE
Isort used with black format with pre-commit

### ISSUE THREAD

**Issue by Sebastiencreoff** [timothycrosley/isort#1113]
Hi guys,

Within my project, I used black format and isort at the same time with pre-commit tool.
The configuration of isort is done inside .sort.cfg:

```
[settings]
multi_line_output=3
```

Black format as default configuration.

The issue I have is this one:

When isort is running: It sorts and output this thing:

```
from utilities import (
    Logger,
    ...
    safe_execute,
)
```
**Please note the comma at the end of the import.**

When **black** run on it after that, it does the same but **just delete the last comma**.
https://github.com/psf/black

=> With this behavior missmatch, I can not use both at the same time.

How can I fix it?
Would it be possible to avoid the add the last comma ?

Thanks.

**Comment by neighthan** [comment]
I think you have it backwards; `black` likes trailing commas, but `isort` might not by default. Take a look at the existing issues in this repo (e.g. https://github.com/timothycrosley/isort/issues/694) about making `isort` and `black` work together. There's also a section in the [Black docs](https://black.readthedocs.io/en/stable/the_black_code_style.html) with an example `.isort.cfg` file.

**Comment by janosh** [comment]
@Sebastiencreoff You can add `include_trailing_comma = True` to your `isort` settings.

**Comment by Sebastiencreoff** [comment]
ok, thanks for your answer. I will check it
