### ISSUE TITLE
NOQA cannot place after backslash

### ISSUE THREAD

**Issue by ki4070ma** [timothycrosley/isort#1114]
### Problem

In below case, it cause conflicts with pylint, flake8 too long line errors.

Original codes

```
from toooooooo_long_package. \   # NOQA <- Cannot put here
    sub_package import Class
```

After running `isort`

```
from toooooooo_long_package.sub_package import Class <- pylint too long error 
```

I've checked README, but I couldn't find the solution for above case.
If already any solutions now, please let me know.

Thanks

**Comment by ki4070ma** [comment]
Sample codes

https://github.com/ki4070ma/python-playground/tree/master/isort_

**Comment by timothycrosley** [comment]
Thanks for reporting!

Verified this should be fixed in develop and will make its way out in the 5.0.0 release.

~Timothy
