### ISSUE TITLE
Tagline wording improvement

### ISSUE THREAD

**Issue by chrahunt** [timothycrosley/isort#1116]
Currently the image tagline in the `master` README reads:

> isort your imports for you, so you don't have to.

I think it reads a little easier if we drop either "for you" or "your":

> isort your imports, so you don't have to.

> isort imports for you, so you don't have to.

**Comment by timothycrosley** [comment]
Thanks for the recommendation! I think you are correct, and I've updated it to use the first form suggested.

Thanks!

~Timothy
