### ISSUE TITLE
ignore all directories that start with dot

### ISSUE THREAD

**Issue by klahnakoski** [timothycrosley/isort#1118]
I am at a loss on how to `skip`  any directory that starts with a dot.  I put `.*/` in my `.gitignore`, I put `exclude = */.*/,.*/` for flake8.  I can not seem to find the combination for isort.

Thank you

**Comment by ucodery** [comment]
There is the --skip-glob option (or could be placed in a config file). To skip any directories starting with a dot I would add `--skip-glob '*/.*/*'`
