### ISSUE TITLE
trailing-comma adds commas to comments forever

### ISSUE THREAD

**Issue by waynew** [timothycrosley/isort#1119]
# The Setup

I'm using the recommended black-friendly settings for isort

Add
```
from json import dump  # here is a comment that will get all of the commas. It has to be long, though
```
 to a file.

# The Punchline

Now run `isort` against this file. Maybe like this:

 ```
for i in {1..100}
do
  isort --multi-line=3 --trailing-comma --force-grid-wrap=0 --use-parentheses --line-width=88 /tmp/blarp.py
done
```

And now watch isort scroll on past with 100 "Fixing /tmp/blarp.py". If you run `cat /tmp/blarp.py`? 

Yeah, *there will be 100 commas* at the end of the comment. Oops! :trollface:

**Comment by timothycrosley** [comment]
Thank you for reporting!
Verified this is not an issue in the develop branch and will be fixed in the soon to be released 5.0.0 version.

Thanks!

~Timothy
