### ISSUE TITLE
Switch to github actions

### ISSUE THREAD

**Issue by timothycrosley** [timothycrosley/isort#1121]
Currently isort uses .travis to run tests cases, however these tests can be very slow to run, as travis imposes limits on how many run in parallel. This ticket represents the work to move the tests to run on github actions to move past the travis limitation.

**Comment by hugovk** [comment]
Please see PR https://github.com/timothycrosley/isort/pull/1122 for a start on this.

**Comment by timothycrosley** [comment]
This is now merged in, and active for all testing across OSes. Thanks!
