### ISSUE TITLE
Updated documentation for new Refactor

### ISSUE THREAD

**Issue by timothycrosley** [timothycrosley/isort#1125]
With the new 5.0.0 refactor there is a lot of incorrect documentation left over. In particular a lot of command line flags have changed. It would be super useful for someone to look over the output of `isort -h` and upgrade the documentation to match.

**Comment by ucodery** [comment]
Found two deprecated options in the readme, -vb and -rc.

**Comment by ucodery** [comment]
Possibly fixed with https://github.com/timothycrosley/isort/pull/1127
