### ISSUE TITLE
Custom settings path not read unless file named .isort.cfg

### ISSUE THREAD

**Issue by KimiNewt** [timothycrosley/isort#1146]
When a specific settings file is used with `-sp` / `--settings-path`, the option only works if the file is named `.isort.cfg`. 

With all the other choices or with a custom name, it simply has no effect. 

isort==4.2.5, Python 3.5, Ubuntu 17

**Comment by timothycrosley** [comment]
Thanks for reporting!

This is already fixed in develop and will make its way out in the 5.0.0 release.

Thanks,

~Timothy
