### ISSUE TITLE
isort website

### ISSUE THREAD

**Issue by timothycrosley** [timothycrosley/isort#1149]
isort should have a website that enables, viewing all usage documentation, discovering new versions, and most importantly testing isort from the browser without a need to install.

**Comment by hugovk** [comment]
> and most importantly testing isort from the browser without a need to install.

Perhaps something like @jpadilla's Black playground?

* https://black.now.sh
* https://github.com/jpadilla/black-playground

**Comment by timothycrosley** [comment]
This is now finally complete, and with a fun twist that it doesn't send code over the wire: https://timothycrosley.github.io/isort/docs/interactive/try/
