### ISSUE TITLE
effect of `skip`  is not clear

### ISSUE THREAD

**Issue by antoine-gallix** [timothycrosley/isort#1155]
It's not clear in the documentation what is the effect of adding `# isort:skip` at the end of a line. From my observations, what it does is considering an import statement as a line of code, and moving it down after the import section, as if it was the first line of code. The `skip` name is maybe self explaining from the tool developers point of view, maybe because the import statement filter will skip this line, but from a user perspective, I bet most people will not guess what will be the effect of it. This could be better explained in the docs. Something in the line of:

"Adding `# isort:skip` as a comment at the end of a line will prevent an import statement to be recognized as such. In consequence, this line will be treated as code and be pushed down to below the import section of the file."

**Comment by timothycrosley** [comment]
Thanks for reporting! 
The improved documentation for this feature is now live, here: https://timothycrosley.github.io/isort/docs/configuration/action_comments/#isort-skip

**Comment by antoine-gallix** [comment]
Good! Thank you for the nice work with isort!
