### ISSUE TITLE
Bug related to isort:skip usage followed by a comment block

### ISSUE THREAD

**Issue by ljades** [timothycrosley/isort#1156]
There is a strange bug with isort happening during a very specific type of use case, steps to reproduce:

1. An import at the top of a module is separated from the rest of the module, and an `# isort: skip` is used to ignore grouping on it.
2. A comment block follows this ignored import.
3. An import is introduced, specifically with a `from` keyword
4. Another import in the same group follows.

Example:
```python
from top_level_ignored import config  # isort:skip
####################################
# COMMENT BLOCK SEPARATING THESE   #
####################################
from ast import excepthandler
import logging
```

The case above yields the following isort error:
```@@ -1,4 +1,5 @@
 from top_level_ignored import config  # isort:skip
+
 ####################################
 # COMMENT BLOCK SEPARATING THESE   #
 ####################################
```

When you add the extra line, however, isort still errors asking for *another* new line. And it just keeps going.

This is strangely idiosyncratic because:

- If the comment block is not there, it functions properly.
- If an import is introduced without `from` (`import ast`), it functions properly.
- If there isn't another following import in the same group, it functions properly.

**Comment by timothycrosley** [comment]
Thanks for reporting! This is fixed in release 5.1.2

~Timothy
