### ISSUE TITLE
specifying a bad settings-path will fail silently

### ISSUE THREAD

**Issue by aviau** [timothycrosley/isort#1158]
Hello!

It seems that specifying a bad settings-path will fail silently with no errors.

I can't seem to find out wether or not I am allowed to specify a pyproject.toml as a settings-path.

**Comment by michael0liver** [comment]
I have yet to get isort working with a pyproject.toml file.

**Comment by timothycrosley** [comment]
This is fixed in the latest isort release, thanks for reporting!

**Comment by aviau** [comment]
Thank youuuu :)
