### ISSUE TITLE
Useless "as" after reformatting imports

### ISSUE THREAD

**Issue by MomIsBestFriend** [timothycrosley/isort#1160]
When running ```isort (dev branch)``` on for example:

```python
import numpy.ma as ma
```

```isort``` will reformat this import line to:

```python
from numpy import ma as ma
```

which is the same as:

```python
from numpy import ma
```

---

<details>

INSTALLED VERSIONS
------------------
commit           : a04700812bd4b9eb687065d1199b52bb8e045774
python           : 3.8.1.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.23.a-1-hardened
machine          : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

isort : 5.0.0

</details>

----

P.S
You have an amazing software!

**Comment by ucodery** [comment]
Fix in https://github.com/timothycrosley/isort/pull/1193
