### ISSUE TITLE
Can I do `isort --black my_file.py` or something similar?

### ISSUE THREAD

**Issue by cclauss** [timothycrosley/isort#1161]
There are cool profiles like https://github.com/timothycrosley/isort/blob/develop/isort/profiles.py#L4-L10 so can I invoke them from the command line like `isort --black my_file.py` or something similar?

**Comment by boweeb** [comment]
`isort/profiles.py` isn't in the latest release (as of now) `4.3.21`.  Looks like it's coming in a future release.

**Comment by timothycrosley** [comment]
You can as of version 5.0.0: https://timothycrosley.github.io/isort/docs/major_releases/introducing_isort_5/
