### ISSUE TITLE
Ability to have diffrent isort configurations for diffrent file extension

### ISSUE THREAD

**Issue by MomIsBestFriend** [timothycrosley/isort#1162]
With ```isort``` 5.0.0 it's now possible to format ```pyx``` in addition to the traditional ```.py``` files.
my sorting order in ```.py``` files is different than my sorting order in ```.pyx``` files.
Is there an option to have different configuration for different file extensions?

**Comment by timothycrosley** [comment]
Currently, no, but i think this would be a great feature for isort to add

**Comment by timothycrosley** [comment]
This is implemented in develop and will find it's way out in the 5.3.0 release:

isort now has in both the config and CLI arguments, support for setting `blocked_extensions` and `supported_extensions`. This allows creating two config files, one that specifies sorting pyx files and another that specifies sorting pyfiles. Then isort would need to be executed per a config defined:


`isort --settings-path .isort.cfg .`
`isort --settings-path .cython.isort.cfg .`

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
This has now been released
