### ISSUE TITLE
Option to revert unwanted import pattern in 5.0.0

### ISSUE THREAD

**Issue by MomIsBestFriend** [timothycrosley/isort#1164]
#### Background:

I have noticed a new feature in ```isort``` 5.0.0 where it would reformat an import statement like:

```python
import foo.bar.baz as baz
```

To look like:

```python
from foo.bar import baz
```

---

#### Issue:

There was a discussion about this topic in [Pandas](https://github.com/pandas-dev/pandas) (we were trying the new ```isort``` on the repository), one of the things that were mentioned (ref https://github.com/pandas-dev/pandas/pull/32489#discussion_r389427595) is that this pattern is discouraged by Guido it self (ref https://docs.python.org/3/faq/programming.html#how-can-i-have-modules-that-mutually-import-each-other)

---

#### Questions

Can this formatting behavior be reverted?

Can ```isort``` have the option to enable/disable this formatting patter?

**Comment by timothycrosley** [comment]
Hi @MomIsBestFriend this formatting change is no longer present in 5.1.0, and should work the way as you intend by default:

https://timothycrosley.github.io/isort/CHANGELOG/#510-july-14-2020

Thanks!

~Timothy
