### ISSUE TITLE
Doc mismatch for xdg config filename

### ISSUE THREAD

**Issue by boweeb** [timothycrosley/isort#1168]
The docs currently say `$XDG_CONFIG_HOME/.isort.cfg` is supported but there's a typo.  The filename the code looks up does not have a dot prefix.

See:  https://github.com/timothycrosley/isort/blob/4.3.21/isort/settings.py#L180

I wouldn't mind submitting a MR but I'm curious to double-check which format _should_ be true -- should the the dot be kept or dropped?  Personally, I think the dot should be dropped since it's already inside a config dir where config files are _expected_ to be seen.

**Comment by timothycrosley** [comment]
isort no longer supports home directory config file looks at all as of 5.0.0, as it caused confusion in how configs would be merged with project level configs.
