### ISSUE TITLE
isort fails silently if --sp points to an invalid path.  and it ignores files not named exactly correctly.

### ISSUE THREAD

**Issue by hjwp** [timothycrosley/isort#1174]
i spent about an hour wondering why isort wasn't doing what i told it.

1.  `-sp /invalid/path` produces no errors
2. `-sp /real/path/to/a-file-not-name.isort.cfg` also fails silently

rage.gif

(i am not accusing anyone of a moral or professional failure here.  i am grateful for a free tool. just sharing my pain, in the hopes that someone else may be spared it)

**Comment by timothycrosley** [comment]
Thanks for reporting! This is fixed in the develop branch and will make it out in the 5.1.0 version of isort.

**Comment by timothycrosley** [comment]
This has now been deployed to PyPI in the [5.1.0 release](https://timothycrosley.github.io/isort/CHANGELOG/#510-july-14-2020), thanks again!

~Timothy
