### ISSUE TITLE
pyproject.toml missing from Wiki

### ISSUE THREAD

**Issue by MinchinWeb** [timothycrosley/isort#1176]
The wiki page on [configuration](https://github.com/timothycrosley/isort/wiki/isort-Settings) doesn't list `pyproject.toml`, which can also be used for `isort` configuration. Can the Wiki be updated to include it please?

Thanks!

**Comment by MindTooth** [comment]
Hi,

The wiki has write access for all registrated users.

I bet the maintainer would appriciate any contribution to the project. 😊

**Comment by MinchinWeb** [comment]
I would add it, but where does it go in the hierarchy? (Or can you point me to the code that handles said hierarchy?)

From the (current) wiki:

- Settings manually passed into the Python SortImports class.
- Settings manually passed into the command line utility.
- Settings placed in a setup.cfg file within the project's directory
- Settings placed in a .isort.cfg file within the project's directory.
- Settings placed in a .isort.cfg file within the users home directory.
- Settings placed in a .editorconfig file within the project's directory.
- Settings placed in a .editorconfig file within the users home directory.

**Comment by MindTooth** [comment]
I belive that [this](https://github.com/timothycrosley/isort/blob/develop/isort/settings.py#L52) can be of use.  Don't quote me on it though. 😉

**Comment by timothycrosley** [comment]
This is now documented on the new isort website:

https://timothycrosley.github.io/isort/docs/configuration/config_files/

Thanks for reporting!
