### ISSUE TITLE
Semicolon in decorator confuses lines_after_imports

### ISSUE THREAD

**Issue by FuegoFro** [timothycrosley/isort#1178]
If you have a decorator on the first class or function after imports that has a semicolon in the line (eg, in a string) it confuses the `lines_after_imports` setting into only putting a single blank line, when there should in fact be two. Here's a minimal repro:

```python
import pytest

@pytest.mark.skip(';')
def test_thing(): pass
```

Removing the semicolon in the `@pytest.mark.skip(';')` line (eg having it be an empty string) causes it to put two blank lines after imports (as expected here).

This bug causes `isort` to conflict with `black` (though a workaround is to just put a `pass` between the imports and the class or function).

This was tested on latest master at time of writing (1621e19c5bf6deacc54a017115c47175a6e52765).

**Comment by timothycrosley** [comment]
A fix for this has been deployed to PyPI in the [5.1.0 release](https://timothycrosley.github.io/isort/CHANGELOG/#510-july-14-2020), 

Thanks for reporting!

~Timothy

**Comment by FuegoFro** [comment]
Fantastic, thank you so much for the fix!
