### ISSUE TITLE
Does this project follow semantic versioning?

### ISSUE THREAD

**Issue by alvassin** [timothycrosley/isort#1180]
What is the best way to specify this project in requirements? Can i use this project with ~= operator and specify it like `isort~=4.3.21`?

Does this project follow [semver](https://semver.org), where version consists of the MAJOR.MINOR.PATCH segments (described below)? 
- `MAJOR` for incompatible API changes,
- `MINOR` for new functionality in a backwards compatible manner
- `PATCH` version when you make backwards compatible bug fixes

If it is, don't you mind to add this information to README/CHANGELOG (so, others could find answer for this question quickly)?

**Comment by timothycrosley** [comment]
Yes it does! Thanks for the note, I've added a mention at the top of the changelog
