### ISSUE TITLE
Project configuration files ignored if operating on standard input

### ISSUE THREAD

**Issue by PeterJCLaw** [timothycrosley/isort#1188]
The latest (`develop`) version (tested at 394738e2a21737c23fdc67be399691341ca422fa) of `isort` appears to have regressed the handling of configuration files when reading from standard input.

Under `isort` 4.3.21 (the latest release at the time of writing), configuration files in the current directory from which `isort` is run are obeyed even when reading from standard in. This is important to allow editor integrations to use `isort` on modified files and unsaved buffers as otherwise the editor would need to duplicate `isort`'s locating of configuration files.

```
$ cat .isort.cfg 
[isort]
length_sort = true

$ cat demo.py 
import os, sys, collections

$ isort - < demo.py 
import collections
import os
import sys
```

**Comment by timothycrosley** [comment]
This is verified fixed in the latest isort release. Thanks for  reporting!
