### ISSUE TITLE
Where in the settings-parsing hierarchy is pyproject.toml?

### ISSUE THREAD

**Issue by mfreeborn** [timothycrosley/isort#1196]
I was just looking at the wiki: https://github.com/timothycrosley/isort/wiki/isort-Settings

I noticed that pyproject.toml isn't mentioned in the settings hierarchy. Where would it fit?

**Comment by timothycrosley** [comment]
https://timothycrosley.github.io/isort/docs/configuration/config_files/ documentation is slowly moving over here which discusses hierchy. Eventually I'll deprecate the wiki to avoid confusion
