### ISSUE TITLE
when use the Multi line output modes 3, It doesn't end with ","

### ISSUE THREAD

**Issue by TonyMistark** [timothycrosley/isort#1198]
for example:
3 - Vertical Hanging Indent
```
from third_party import (
    lib1,
    lib2,
    lib3,
    lib4,
)
```
But, the actual result is
```
from third_party import (
    lib1,
    lib2,
    lib3,
    lib4
)
```
It doesn't end with ","

**Comment by timothycrosley** [comment]
I think what you are looking for is `include_trailing_comma` see: https://github.com/timothycrosley/isort/wiki/isort-Settings#include_trailing_comma.

Thanks!

~Timothy
