### ISSUE TITLE
New feature: slash line breaks vs parenthesis

### ISSUE THREAD

**Issue by sobolevn** [timothycrosley/isort#1211]
Currently on this code:

```python
from returns._generated.pointfree.bind_ioresult import _bind_ioresult as bind_ioresult
```

And these settings:

```int
[isort]
include_trailing_comma = true
multi_line_output = 3
default_section = FIRSTPARTY
line_length = 80
```

`isort` reformats this line to:

```python
from returns._generated.pointfree.bind_ioresult import \
    _bind_ioresult as bind_ioresult
```

But, I don't use `\` in my programs at all (with the help of https://github.com/sobolevn/flake8-broken-line), so instead I would love to have it formatted like so:

```python
from returns._generated.pointfree.bind_ioresult import (
    _bind_ioresult as bind_ioresult,
)
```

But, currently I am not able to find this setting. So, I propose to add it 🙂

**Comment by orsinium** [comment]
You need `use_parentheses = true`, it does exactly this:

```diff
@@ -1 +1,3 @@
-from returns._generated.pointfree.bind_ioresult import _bind_ioresult as bind_ioresult
+from returns._generated.pointfree.bind_ioresult import (
+    _bind_ioresult as bind_ioresult,
+)

```

I'm not sure why it's not in the README but it is in the [configuration wiki](https://github.com/timothycrosley/isort/wiki/isort-Settings)

**Comment by sobolevn** [comment]
Thanks, I have missed it. 🤝
