### ISSUE TITLE
filter_files doesn't work on latest develop branch

### ISSUE THREAD

**Issue by leos** [timothycrosley/isort#1213]
Using https://github.com/timothycrosley/isort/commit/80fec4d92b7b155e37e4ecac6711c35df98f297c if `filter_files` is set in the config, isort will blow up with the following error:
```
Traceback (most recent call last):
  File ".../py_env-python3.7/bin/isort", line 8, in <module>
    sys.exit(main())
  File ".../py_env-python3.7/lib/python3.7/site-packages/isort/main.py", line 619, in main
    config = Config(**config_dict)
  File ".../py_env-python3.7/lib/python3.7/site-packages/isort/settings.py", line 301, in __init__
    super().__init__(sources=tuple(sources), **combined_config)  # type: ignore
TypeError: __init__() got an unexpected keyword argument 'filter_files'
```
`filter_files` doesn't seem to be defined on `_Config` - is that intentional? is it going to be deprecated in 5.0.0?

**Comment by timothycrosley** [comment]
Hi @leos,

Sorry for the confusion! `filter_files` was never meant to be used from the configuration file, but was always a command line flag. Filter files will still be usable that way `isort --filter-files`.

Hope this is helpful!

Thanks!

~Timothy

**Comment by leos** [comment]
@timothycrosley , thanks for the response. It feels weird that there's a config option that's command line only and not available in the config file. What's the rationale behind that?

We'd like to be able to run `isort` without any arguments and ensure that it is running consistently and with the same settings no matter whether it's run by `pre-commit`, VS Code or directly on the command line.

If it's not available as an option that can be read from the `.isort.cfg` then we probably have to do workarounds like alias `isort` which feels less than ideal.

**Comment by eseglem** [comment]
Just wanted to chime in @timothycrosley I feel my only need for `--filter-files` is for use with `pre-commit` where I have files that need to not be ran through isort. It would also be nice to be able to run `isort .` on a dir and ignore the files as well. Is there a specific reason to not allow it in a config file?
