### ISSUE TITLE
isort fails with multi-line import using `as`

### ISSUE THREAD

**Issue by ryan-faculty** [timothycrosley/isort#1215]
```
from longgggggggggggggg.path.to.library import function_name as new_function_name
```

I am using `isort --recursive -l 79 --multi-line=3 --trailing-comma`

Expected behavior:
```
from longgggggggggggggg.path.to.library import (
    function_name as new_function_name
)
```

Observed behavior:
```
from longgggggggggggggg.path.to.library import \
    function_name as new_function_name
```

This results in a conflict with `black`

**Comment by timothycrosley** [comment]
This is fixed in the 5.0.0 release of isort: https://timothycrosley.github.io/isort/docs/major_releases/introducing_isort_5/

Thanks for reporting!
