### ISSUE TITLE
wrong classification for `posixpath`

### ISSUE THREAD

**Issue by xmnlab** [timothycrosley/isort#1216]
last week week using isort with pre-commit, posixpath was changed from STDLIB to 3rd-party section (this is the pre-commit config file https://github.com/ibis-project/ibis/blob/master/.pre-commit-config.yaml#L7)

as the isort is pinned to a specific commit ... not sure what could be the problem ... I also opened a PR pinning pre-commit to 2.1 to check if it was the problem.. but no success ... 

does anyone has any idea about this? thanks

**Comment by di** [comment]
One quick fix would be to replace `posixpath` with `os.path` instead, as they are equivalent: https://docs.python.org/3/library/os.path.html

**Comment by xmnlab** [comment]
thanks for the suggestion @di !

**Comment by andersk** [comment]
@di `posixpath` is only equivalent to `os.path` on POSIX systems. On Windows, `posixpath` still exists but behaves differently from `os.path`.

`sre_constants` is another standard library module misclassified as third-party.

I bisected this regression to 535b4e86d91bcc09aaac9dc6e37717bbaa95499e and 95f86bec13f7dcd924dce750ee4eba0bfce3fde9.

**Comment by andersk** [comment]
I see `posixpath` was just added in a4dea5fa72907ffefb21e40ef194f274c86f847a. We probably want `ntpath` too by symmetry.

**Comment by xmnlab** [comment]
thanks for the update @andersk !
