### ISSUE TITLE
 organize imports with mid-imports code

### ISSUE THREAD

**Issue by dvirginz** [timothycrosley/isort#1217]
As I run multiple projects with the same utils, I sometimes have the need to append a path of a relevant directory:
```
import os
import sys
sys.path.append(some_path)
<some imports that can only come here>
```

Unfortunately, after using isort , the `sys.append` line jumps to the bottom of the code, causing the file to crash (module not found error).
Is there a way to tell isort to not sort those lines?

**Comment by timothycrosley** [comment]
https://timothycrosley.github.io/isort/docs/major_releases/introducing_isort_5/ in the just released version isort should automatically skip over these.It also has action comments that allow you to manually turn and turn on sorting:

````
import b

# isort: off

import a

# isort: on
```
