### ISSUE TITLE
Comments not wrapped for long lines

### ISSUE THREAD

**Issue by dzieciou** [timothycrosley/isort#1219]
Version 4.3.21:

I have the following problematic file `totest.py`:

```python
from many_stop_words import (
    get_stop_words as get_base_stopwords,
)  # extended list of stop words, also for en
```

I run isort, black and then check results with isort to see if imports order have been preserved. The last step simulates what happens on Jenkins:

```bash
isort  -m 3 -tc -w 105 totest.py
black --line-length 105 totest.py
isort -c -m 3 -tc -w 105 totest.py
```

After first step I got

```python
from many_stop_words import get_stop_words as get_base_stopwords  # extended list of stop words, also for en
```

After second step, black formatting, I got

```python
from many_stop_words import (
    get_stop_words as get_base_stopwords,
)  # extended list of stop words, also for en
```

After last step, the check fails:
```
ERROR: totest.py Imports are incorrectly sorted.
```

It looks like isort ignores comments when wrapping long lines. The line without comment has 64 chars but with comment it has 108 chars, exceeding requested 105 chars.

I would expected from `isort  -m 3 -tc -w 105 totest.py` to give the following output:

```python
from many_stop_words import (
    get_stop_words as get_base_stopwords,
)  # extended list of stop words, also for en
```

How can I make isort to do that?

**Comment by timothycrosley** [comment]
Thanks for reporting! This is fixed in release 5.1.2

~Timothy
