### ISSUE TITLE
Improper handling of packages with - (dash) in name

### ISSUE THREAD

**Issue by dzieciou** [timothycrosley/isort#1221]
The problem occurs both in isort 4.3.21 and 5.0.0 (develop branch)

I have the following `totest.py` with two third-party libraries:

```python
import Levenshtein 
import numpy
```

and a corresponding `requirements.txt` 
```
python-Levenshtein
numpy
```

I expected isort to map Levenshtein module to python-Levenshtein thanks to the following[ entry in pipreqs mapping](https://github.com/bndr/pipreqs/blob/master/pipreqs/mapping#L22):

```
Levenshtein:python_Levenshtein
```
However, it looks like isort is not able to handle that properly

```bash
$ isort -c totest.py
ERROR: .../totest.py Imports are incorrectly sorted and/or formatted.
```

This is because python-Levenshtein in pipreqs mapping has already '-' replaced with '_'. The following fix to 'isort/finders/ Line 253:
```python
	name = self.mapping.get(name, name)
```

```python
	name = self.mapping.get(name.replace('-','_'), name)
```
My env to reproduce the case:

```bash
python3 -m venv ~/virtualenv/test
source ~/virtualenv/test/bin/activate
pip install pipreqs
pip install git+https://github.com/timothycrosley/isort.git
```

**Comment by timothycrosley** [comment]
This should no longer be an issue in 5.0.0 as it no longer looks inside requirements.txt files to determine placement
