### ISSUE TITLE
point to a specific requirements.txt in isort.cfg

### ISSUE THREAD

**Issue by graingert** [timothycrosley/isort#1223]
I have multiple requirements eg requirements.txt requirements-test.txt etc and they're sometimes in different folders due to convoluted docker cache hacks

eg in my tests I want to look at the test requirements, and not the prod requirements:
```ini
[tool:isort]
known_third_party = requirements:../requirements-test.txt
```

**Comment by timothycrosley** [comment]
in the just released 5.0.0 version of isort: https://timothycrosley.github.io/isort/docs/major_releases/introducing_isort_5/ requirements.txt are no longer taken into consideration, as everything defaults to third party - so this should no longer be an issue!

Thanks for reporting!

~Timothy
