### ISSUE TITLE
problems when using with pre-commit

### ISSUE THREAD

**Issue by Pix-00** [timothycrosley/isort#1225]
Receiving the following warning when use with `pre-commit`, and of cause, `isort` runs without the configs in `pyproject.toml`.

    UserWarning: Found ****\pyproject.toml with [tool.isort] section, but toml package is not installed. To configure isort with ****\pyproject.toml, install with 'isort[pyproject]'.

I guess this is cause because `pre-commit` initializes the environment with 'isort' rather than 'isort[pyproject]'. Will it be a good idea that get a new repo for `pre-commit` with `toml` in the default dependency.

**Comment by timothycrosley** [comment]
This shouldn't be an issue going forward as isort as of 5.0.0 includes the toml dependency by default vendored.
