### ISSUE TITLE
Skip comment ignored for long absolute imports

### ISSUE THREAD

**Issue by kriskorrel-cw** [timothycrosley/isort#1229]
I am trying to make a pre-commit and CI/CD setup including Isort, [Black](https://github.com/psf/black) and [Flake8](https://flake8.pycqa.org/en/latest/) work (in this order).
Now, I have a project with very long absolute imports like
```
from myproject.this.is.a.quite.long.aboslute.import.for.a.class import MyClass
```
Since this import in reality will exceed the 88 line-length limit I have setup, it will be wrapped to become
```
from myproject.this.is.a.quite.long.aboslute.import.for.a.class import (
    MyClass
)
```
But even this is too long. So I tried to disable formatting of this line using a skip-comment, but isort seems to ignore this comment.

For example,
```
#fmt: off
from myproject.this.is.a.quite.long.aboslute.import.for.a. \
 class import (  # isort:skip
    MyClass  # isort:skip
)  # isort:skip
#fmt: on
```
will still get formatted to
```
#mft: off
from myproject.this.is.a.quite.long.aboslute.import.for.a.class import ( 
    MyClass  # isort:skip, isort:skip, isort:skip
) 
#fmt: on
```
by isort.

I would say that it should be possible to ignore this import statement all-together. Right now, it seems that the only way to solve this for me, is to skip the entire file.

**Comment by timothycrosley** [comment]
It is true that isort: skip only works on the same line. However, with isort 5.0.0 you have more options such as turning isort off and back on:

```
import a

# isort: off
from myproject.this.is.a.quite.long.aboslute.import.for.a.class import (
    MyClass
)
#isort: on
```
https://timothycrosley.github.io/isort/docs/major_releases/introducing_isort_5/
