### ISSUE TITLE
Giving different sort order on Windows and Linux.

### ISSUE THREAD

**Issue by Julian-O** [timothycrosley/isort#1231]
I am trying to introduce `isort --check-only` into kivy\buildozer's tox file.

On my Windows development machine it correctly sorts the imports. In particular `import buildozer as buildozer_module` is correctedly detected as first-party.

    import tempfile
    from unittest import mock

    import pytest

    import buildozer as buildozer_module
    from buildozer import Buildozer
    from buildozer.targets.android import TargetAndroid

This is straight out-of-the-box - no `.isort.cfg`, no`setup.cfg`, no mention in `tox.ini` or any other configuration. Just the command line: 

    isort --recursive --diff buildozer/ tests/

Perfect.

But I want to enforce the check on every checkin, so I add an entry to `tox.ini` which is executed by a github action on every push and pull request.

    [tox]
    envlist = pep8, py3, isort

    [testenv]
    deps =
        pytest
        py3: coverage
    commands = pytest tests/

[...]

     [testenv:isort]
     deps = isort
     commands = isort --check-only --recursive --diff buildozer tests

There is no `[isort]` section. (I tried introducing one, but my attempts to make buildozer known first-party failed.)

I used to have trailing "/" after the directory names, but removed them in an attempt to debug - it made no difference.

Now, when tox is run by github, it complains that the  `import buildozer as buildozer_module` line belongs above `import pytest` - that is, it is considered third-party.

For me the key item here is that `import buildozer as ....` and `from buildozer import ...` are being treated differently (Third-Party versus First-Party) on Ubuntu, but as the same (First-Party) on Windows.

`buildozer` is a package - a directory called `buildozer` which contains a file called `__init__.py`. Nothing too tricky that I can see.

I skimmed the isort code looking for the sort of issues that might cause this - case-sensitivity issues, bad path separators, but it all looked fine.

I tried to write a test-case to reproduce this, but many unit tests failed in my (Ubuntu VirtualBox) test environment and I bailed.

**Comment by timothycrosley** [comment]
This is one of the major areas of focus for the 5.0.0 release: https://timothycrosley.github.io/isort/docs/major_releases/introducing_isort_5/ and hopefully should be fixed there.

Thanks for reporting!

~Timothy
