### ISSUE TITLE
length_sort separately from regular imports and from...imports

### ISSUE THREAD

**Issue by warsaw** [timothycrosley/isort#1232]
A style I adopted long ago (from Guido IIRC) was to sort the regular imports by length first then alphabetical, while sorting from...imports alphabetically only.  E.g.

```
import os
import sys
import datetime

from contextlib import ExitStack
from datetime import timedelta
```

However this doesn't seem possible, since `length_sort` is a single configuration for both sections.  If I set `length_sort = false` I get:

```
# These are sorted in the wrong order.
import datetime
import os
import sys

# These are sorted correctly.
from contextlib import ExitStack
from datetime import timedelta
```

and if I set `length_sort = true` I get:

```
# These are sorted correctly.
import os
import sys
import datetime

# These are sorted in the wrong order.
from datetime import timedelta
from contextlib import ExitStack
```

Neither of which I actually want.  Can you add a setting to split regular import sorting from from...import sorting?

Thanks for a great tool!

**Comment by warsaw** [comment]
This also affects sorting within multiline from...imports:

I want this:

```
from flufl.lock._lockfile import (
    AlreadyLockedError, Lock, LockError, NotLockedError, SEP, TimeOutError)
```

But I get this:

```
from flufl.lock._lockfile import (
    SEP, Lock, LockError, TimeOutError, NotLockedError, AlreadyLockedError)
```

**Comment by timothycrosley** [comment]
I'm def open to supporting this! Will have to be post 5.0.0 as I'm pretty heads down getting that out the door. Then I'll revisit. Thanks for the suggestion!

**Comment by warsaw** [comment]
Sure thing!  Thanks for the great tool!

**Comment by timothycrosley** [comment]
This has been deployed in release 5.4.0

Thanks!

~Timothy
