### ISSUE TITLE
Trailing comma goes at the end of inline comment

### ISSUE THREAD

**Issue by SofienBenAyed** [timothycrosley/isort#1234]
I use `include_trailing_comma` so that `isort` adds a trailing comma at the end of from imports.
It usually works perfectly except when I have inline comments.
For instance, when applying `isort` to this import:
```python
from project.moduleA.moduleB.moduleC.moduleD import (
    MyVeryUsefulClassA,  # some inline comment
)
```
it becomes:
```python
from project.moduleA.moduleB.moduleC.moduleD import (
    MyVeryUsefulClassA  # some inline comment,
)
```
The trailing comma travels from the end of the imported class to the end of the inline comment.

Moreover, it makes it incompatible with `black`.

Thank you!

---

Below is the `isort v4.3.21` configuration I use for `black` compatibility.
```
[isort]
multi_line_output=3
include_trailing_comma=True
force_grid_wrap=0
use_parentheses=True
line_length=88
```

**Comment by timothycrosley** [comment]
This is fixed in the just released 5.0.0 version of isort: https://timothycrosley.github.io/isort/docs/major_releases/introducing_isort_5/

Thank you for reporting!
