### ISSUE TITLE
Unnecessary blank lines left

### ISSUE THREAD

**Issue by SofienBenAyed** [timothycrosley/isort#1235]
Below is a (dummy) example where some global imports are not at the top of the file and placed between other statements:
```python
from math import pi


if True:
    print("True")

from math import log

from math import cos

from math import exp

if False:
    print("False")
```

Applying `isort v4.3.21` with the default configuration outputs:
```python
from math import cos, exp, log, pi

if True:
    print("True")




if False:
    print("False")
```
The two blank lines between the original misplaced imports are left.
The best would be to get:
```python
from math import cos, exp, log, pi

if True:
    print("True")


if False:
    print("False")
```

I don't know if it's really an issue or if `isort` is not supposed to handle those far-fetched cases.

Thank you!

**Comment by timothycrosley** [comment]
Thank you for reporting! This is fixed in the just released 5.0.0 version of isort: https://timothycrosley.github.io/isort/docs/major_releases/introducing_isort_5/
