### ISSUE TITLE
Relative path not in sorting order

### ISSUE THREAD

**Issue by irisliucy** [timothycrosley/isort#1236]
I am testing the isort for pre-commit and found that isort doesn't work as desired in relative path. 

Expected order:
```
from . import A, B
from .A import A
from .B import B
from .. import A, B
from ..A import A
from ..B import B
```
My setting on `setup.cfg` is as follows:
```
[tool:isort]
sections=FUTURE,STDLIB,FIRSTPARTY,THIRDPARTY,LOCALFOLDER
force_sort_within_sections = True
order_by_type = False
```

What I got from isort:
```
from . import A, B
from .. import A, B
from ..A import A
from ..B import B
from .A import A
from .B import B
```

Let me know if I simply miss something. Appreciated!

**Comment by timothycrosley** [comment]
This should be fixed in the recently released 5.0.0 version of isort: https://timothycrosley.github.io/isort/docs/major_releases/introducing_isort_5/
