### ISSUE TITLE
Different results when sorting individual files vs. multiple files

### ISSUE THREAD

**Issue by andersk** [timothycrosley/isort#1239]
Using `develop` (a4dea5fa72907ffefb21e40ef194f274c86f847a), isort seems to detect as first-party any module that’s present in the same directory as *any* of the input files, rather than considering only the directory of the file currently being sorted. This leads to the counterintuitive behavior that isort can give different results when processing single files than when processing multiple files at once.

Is this intentional? Can it be controlled? I know I can force extra directories to be considered for this heuristic with `src_paths`, but can I force extra directories *not* to be considered?

```diff
$ mkdir foo baz

$ echo 'import bar, quux, sys' > foo/bar.py

$ echo 'import bar, quux, sys' > baz/quux.py

$ isort --diff foo/bar.py
--- /home/anders/python/isort/foo/bar.py:before	2020-06-25 14:18:31.428391
+++ /home/anders/python/isort/foo/bar.py:after	2020-06-25 14:18:35.589068
@@ -1 +1,5 @@
-import bar, quux, sys
+import sys
+
+import quux
+
+import bar
Fixing /home/anders/python/isort/foo/bar.py

$ isort --diff baz/quux.py
--- /home/anders/python/isort/baz/quux.py:before	2020-06-25 14:17:55.415986
+++ /home/anders/python/isort/baz/quux.py:after	2020-06-25 14:19:08.826318
@@ -1 +1,5 @@
-import bar, quux, sys
+import sys
+
+import bar
+
+import quux
Fixing /home/anders/python/isort/baz/quux.py

$ isort --diff foo/bar.py baz/quux.py
--- /home/anders/python/isort/foo/bar.py:before	2020-06-25 14:18:35.587893
+++ /home/anders/python/isort/foo/bar.py:after	2020-06-25 14:19:26.094464
@@ -1,5 +1,4 @@
 import sys
 
+import bar
 import quux
-
-import bar
Fixing /home/anders/python/isort/foo/bar.py
--- /home/anders/python/isort/baz/quux.py:before	2020-06-25 14:19:08.825135
+++ /home/anders/python/isort/baz/quux.py:after	2020-06-25 14:19:26.095467
@@ -1,5 +1,4 @@
 import sys
 
 import bar
-
 import quux
Fixing /home/anders/python/isort/baz/quux.py
```

**Comment by andersk** [comment]
Searching all these extra directories also comes with a huge performance penalty. Running `isort` on all the Python files in zulip/zulip now takes ~40 seconds instead of ~5 seconds.

**Comment by timothycrosley** [comment]
Moving this over to help consolidate the conversation:

> When you fix this, I hope there will still be a way to either (a) use only the configured src_paths and not these dynamically added ones or (b) use only the configured src_paths along with just the one directory of the one file currently being sorted (rather than all the directories of all the files that will be sorted).

**Comment by timothycrosley** [comment]
Thanks for pointing out these deficiencies with the refactored finding approach! This ticket offers background on why the overall refactoring (which included this change) was done: https://github.com/timothycrosley/isort/issues/1147. TLDR; isort used to work usually given just a file name, but that relied on a lot of magic that was really hard to debug when it didn't work on CI/CD or someone else's machines. That said, I think just like it's important for it to behave predictably across different environments, it's also very important that it works in a predictable way independent on if you have one or multiple files passed in. I'm tempted to just make src_paths required, but I do feel like that may confuse people when they initially test out the project, and just want `isort .` to sort their project. I've made a change on develop that I hope improves this situation and am curious what you think of this approach:

The automatically determined 'runtime_src_paths` are now only be directories (not files) that are manually passed in. These are then combined with any configuration `src_paths` set in the configuration file. If there are no directories passed in and no source paths defined, isort will fallback to using the current working directory.

**Comment by andersk** [comment]
For my use case where I configure `src_paths` and only pass files, that should work.

But I worry that the difference between `isort .` and `isort file.py` may become a common point of confusion for users who run `isort .` manually or in CI, and also have an editor integration that runs `isort file.py`. It’d be nicer for the behavior on each file to be completely independent of which other files are also being sorted and how they were passed.

That might require giving up the simplicity of automatically detecting a default `src_paths` setting from the arguments. But maybe the common cases can be detected in some other way, like scanning for the parent directory that contains `.isort.cfg` or `setup.cfg` or `pyproject.toml`?

**Comment by timothycrosley** [comment]
I agree completely with your assessment! I've updated the logic to default to the most likely project root directory (closest config file or .git / .hg directory). And if none are found to use the CWD. If src_paths are defined, only those will be use.
