### ISSUE TITLE
create a new branch called stable which contains latest release code

### ISSUE THREAD

**Issue by lokesh1729** [timothycrosley/isort#1242]
Hey,

please create a new branch called stable which contains latest release code. The use-case is we use isort as a `pre-commit` hook, in the revision everytime we need to update the version tag, there's no branch which contains latest release code. [black](https://github.com/psf/black) is already doing this.

**Comment by timothycrosley** [comment]
isort has always had this. It is the master branch.

**Comment by lokesh1729** [comment]
@timothycrosley : if that's the case, why there are changes when i compare "master" branch and "4.3.21" tag

https://github.com/timothycrosley/isort/compare/master...4.3.21

**Comment by lokesh1729** [comment]
and changes between "4.3.21" and "master" too

https://github.com/timothycrosley/isort/compare/4.3.21...master

ideally a tag/branch should have been created from master, so when we compare there should be no commits from master into 4.3.21 isn't it ?

and when version 4.3.21 is released, the code would have been merged into and there should be no changes
