### ISSUE TITLE
Add a `first_party` setting

### ISSUE THREAD

**Issue by FFY00** [timothycrosley/isort#1247]
We currently have a `known_first_party` and `known_third_party` setting. This is useful, but in most use case-cases we want to specify our modules in `known_first_party` and all our dependencies (every else) in `known_third_party`, which forces us to maintain a dependency list in parallel for `known_third_party`. I propose introducing a `first_party` setting, which would supersede `known_{first,third}_party` if set, to allow us to just specify our modules and be done with it. It would set the first party modules as specified and mark everything else as third party.

For eg., in my project I could replace
```
known_first_party = build
known_third_party = nox,pallets_sphinx_themes,pep517,pytest,setuptools,toml
```
with
```
first_party = build
```
Since I can safely guarantee the only module I provide is `build`. If I was using a `tests` module or something similar in the tests, I could also specify it here.

What do you think?

**Comment by timothycrosley** [comment]
This is exactly how finding will work in 5.0.0 (to be released tomorrow!) with the exception that it's keeping the known_first_party designation. Note that you can get this behaviour in 4.x.x as well simply by changing the default to THIRD_PARTY

**Comment by FFY00** [comment]
Okay, so if I understand correctly what I want to do to keep 4.x compatibility, is this right?

```
known_first_party = build
default_section = THIRDPARTY
```

I had a look and it seems like you changed the `default_section` default to `THIRDPARTY` in 5.0.0, and that's why just specifying `known_first_party` will have the behavior I want by default, correct? I just want to make sure I understand :smile:.

**Comment by timothycrosley** [comment]
@FFY00 That's exactly correct! And thanks for verifying, will also help others who stumble onto this ticket
