### ISSUE TITLE
Missing documentation for Force Alphabetical Sort Within Sections

### ISSUE THREAD

**Issue by johnthagen** [timothycrosley/isort#1256]
https://timothycrosley.github.io/isort/docs/configuration/options/#force-alphabetical-sort-within-sections

> Force Alphabetical Sort Within Sections
> No Description

It would be helpful if there was a description for this. It reads very similarly to:

> Force Alphabetical Sort
> Force all imports to be sorted alphabetically within a section

**Comment by timothycrosley** [comment]
Thanks for reporting!
This has been fixed in the just published 5.0.3 patch version.

Thanks!

~Timothy

**Comment by johnthagen** [comment]
That description is much more helpful, thanks!
