### ISSUE TITLE
Support --filter-files in options

### ISSUE THREAD

**Issue by r-richmond** [timothycrosley/isort#1261]
According to http://timothycrosley.github.io/isort/docs/configuration/options/#filter-files is not supported in the config 

```
Tells isort to filter files even when they are explicitly passed in as part of the command

Type: Bool
Default: False
Python & Config File Name: Not Supported
CLI Flags:

    --filter-files
```

I'd like to set this option in this config file so that all of my Isort configurations are in the same place.

My use case involves
1. pre-commit hook
1. PyCharm file watcher
1. and just running `isort ./**/*.py -c` if I wanted.

Currently I have to remember to pass in `--filter-files` to these other tools otherwise files I want to exclude with be included. Instead I'd like to store all my Isort config files in one place and have that be respected. 

p.s. the behavior in 5.0 where it loudly fails on the unsupported options is much better 👍 ty for adding that, I was going crazy on 4.x trying to figure out where I was messing up and now its much clear.

**Comment by timothycrosley** [comment]
This was just deployed with version 5.2.0 of isort. Thanks! 

~Timothy

**Comment by r-richmond** [comment]
Hazaa, ty for the update!
