### ISSUE TITLE
FR: Update known_others documentation to make usage more clear

### ISSUE THREAD

**Issue by r-richmond** [timothycrosley/isort#1262]
I'm currently trying to use the following configuration in my project.toml

```
[tool.isort]
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'AIRFLOW', 'FIRSTPARTY', 'LOCALFOLDER']
known_first_party = ['modules']
known_others = {'AIRFLOW' = ['airflow', ] }
```

However, I'm continually met with
```
/usr/local/lib/python3.7/site-packages/isort/settings.py:421: UserWarning: Failed to pull configuration information from ./project_root/pyproject.toml
  warn(f"Failed to pull configuration information from {potential_config_file}")
```

but toml loads it just fine...
```
>>> test = """[tool.isort]
... sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'AIRFLOW', 'FIRSTPARTY', 'LOCALFOLDER']
... known_first_party = 'modules'
... known_others = {'AIRFLOW' = ['airflow', ] }"""
>>> pprint.pprint(toml.loads(test))
{'tool': {'isort': {'known_first_party': 'modules',
                    'known_others': {'AIRFLOW': ['airflow']},
                    'sections': ['FUTURE',
                                 'STDLIB',
                                 'THIRDPARTY',
                                 'AIRFLOW',
                                 'FIRSTPARTY',
                                 'LOCALFOLDER']}}}
>>> 
```

1. Is this a bug or have I made a mistake somewhere?

2. Perhaps it would be good to add an example value here?
http://timothycrosley.github.io/isort/docs/configuration/options/#known-other

note the docs lists the type as a dict whereas the code https://github.com/timothycrosley/isort/blob/64ab238666298d5ff203082a6213087fa4a39858/isort/settings.py#L105 more completely describes the type as Dict[str, FrozenSet[str]], 
3. perhaps the docs could use the type info from the type hint?

**Comment by r-richmond** [comment]
After reading the source code I figured out the issue. 
https://github.com/timothycrosley/isort/blob/64ab238666298d5ff203082a6213087fa4a39858/isort/settings.py#L267
the option isn't `known_others` it is `known_{SECTION}`

so the correct toml config above would be 

```
[tool.isort]
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'AIRFLOW', 'FIRSTPARTY', 'LOCALFOLDER']
known_first_party = ['modules']
known_airflow = ['airflow']
```

leaving this open as a documentation update request

**Comment by timothycrosley** [comment]
Closing this as your improvements have been merged :) Thanks again!
