### ISSUE TITLE
Thanks for the new release! It's awesome!

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [timothycrosley/isort#1265]
I tried it on my project with the black profile, and it worked great!

The compatibility with black and the "out of the box" experience with first party imports being detected out of the box is a huge improvement. Only the black profile to select it It just worked. Congrats and thanks for the 5.x release!

**Comment by jedie** [comment]
I just would also say: thanks!
👍

**Comment by asherf** [comment]
same. Thanks!!!

**Comment by timothycrosley** [comment]
Thanks everyone!

**Comment by shardros** [comment]
<3

**Comment by ichard26** [comment]
As a Black contributor, heavy thanks go to you for making the integration between Black and isort 5+ even better :)

Although soon, I might have to update Black's compatible configurations documentation... worth it though!
