### ISSUE TITLE
lines after imports bug with triple quotes

### ISSUE THREAD

**Issue by hyeonjames** [timothycrosley/isort#1276]
Hello!

I found that isort creates only one line when it starts with decorator and triple quotes for top level function or class definition. 

( I am not sure if it actually follows PEP8 but my PyCharm and flake8 see it as an error )

I am using isort v5.0.3

```python
from module import decorator


@decorator("""
hello
""")
def a():
    pass
```

I think this code is supposed to have no problem with isort, but when I used isort, it causes the error below:
```bash
(base) james@MacBook-Pro-9 playground % isort isort_bug.py --diff --check
ERROR: /Users/james/playground/isort_bug.py Imports are incorrectly sorted and/or formatted.
--- /Users/james/playground/isort_bug.py:before 2020-07-06 18:22:34.970555
+++ /Users/james/playground/isort_bug.py:after  2020-07-06 18:22:44.025902
@@ -1,5 +1,4 @@
 from module import decorator
-
 
 @decorator
```

Besides, I think it is caused only when it starts with triple quotes

Below codes have no problem
```python
from module import decorator


@decorator("hello")
def a():
    pass
```

**Comment by hyeonjames** [comment]
I think I can fix it, I am working on it.

**Comment by timothycrosley** [comment]
Thanks for reporting and fixing! Your changes have been deployed with the 5.0.6 release of isort :rocket: 

Thanks!

~Timothy
