### ISSUE TITLE
what is the replacement for isort --apply in 5.0.4?

### ISSUE THREAD

**Issue by Sahil-Ajmera** [timothycrosley/isort#1286]
Hi, thanks for the update 5.0.4 . According to the changelog for 5.0.4, --apply is removed and the functionality is default behavior now(https://timothycrosley.github.io/isort/CHANGELOG/)? I tried removing --apply (using via tox) but I still get the prompt before fixing any of my imports. Am I missing something here? Thank you.

**Comment by Sahil-Ajmera** [comment]
I am facing this issue while running via tox.. --apply is required while running from a tox environment it seems otherwise I get the prompts. Any ideas on how to fix that?

**Comment by timothycrosley** [comment]
Hi @Sahil-Ajmera, --apply simply doesn't exist in isort 5.0.0. If you need it within your tox environment, that means that your tox environment has isort 4.x.x installed within it. This makes sense as something that can happen, as tox intention is to isolate environments. I would ensure your dependency is set to 5 and delete your existing tox environment.

**Comment by Sahil-Ajmera** [comment]
Thanks @timothycrosley
