### ISSUE TITLE
Installation?

### ISSUE THREAD

**Issue by limburgher** [timothycrosley/isort#1291]
Hi! I'm the maintainer of the Fedora isort RPM. Previously, isort was installed with setuptools. In the 5.x releases, there's a setup.cfg but no setup.py. Is there another method of installation? pip isn't an option because this needs to be built from source.

**Comment by timothycrosley** [comment]
Hi @limburgher,

Thank you for maintaining the RPM! isort uses `poetry` now to manage package installation, which means it doesn't include setup.py file in the repo. However, when the project is released and pushed to PyPI it creates a setup.py in the source package:

See the tar.gz here: https://pypi.org/project/isort/5.0.5/#files

Could this be used to build the package?

**Comment by limburgher** [comment]
Yes, that works, thank you!
