### ISSUE TITLE
Is `--help` out of date?

### ISSUE THREAD

**Issue by max-sixty** [timothycrosley/isort#1298]
Thanks for `isort` and congrats on the latest release!

I'm was a bit confused on the default behavior. `[--help](https://github.com/timothycrosley/isort/blob/develop/isort/main.py#L133)` states:

```
        "within logical sections. Run with no arguments to run "
        "interactively. Run with `-` as the first argument to read from "
        "stdin. Otherwise provide a list of files to sort."
```

Changelog states:

```
isort now does nothing, beyond giving instructions and exiting status code 0, when ran with no arguments.
    a new --interactive flag has been added to enable the old style behaviour.
```

I think `--help` is out of date, is that right?

**Comment by timothycrosley** [comment]
Thanks for reporting this issue! I've fixed it with the 5.0.5 patch release. Sorry for any confusion this caused!
