### ISSUE TITLE
Update Readthedocs

### ISSUE THREAD

**Issue by therefromhere** [timothycrosley/isort#1303]
Hi, it looks like readthedocs hasn't been built in quite a while, can a fresh build be done for version 5?

And ideally hooked up to automatically build on commit to master?

**Comment by timothycrosley** [comment]
@therefromhere isort uses portray and github pages for documentation: https://timothycrosley.github.io/isort/. Is there any specific reason that readthedocs should be used / considered?

**Comment by therefromhere** [comment]
Ah that would explain why it's not updated :)

Unfortunately readthedocs is the 2nd Google result for "isort", I didn't realised it wasn't maintained until I saw reference to py2.6...

Is it possible to update the readthedocs page to link to the github.io site? (a redirect would be ideal, but I'm not sure readthedocs supports offsite redirects).

**Comment by timothycrosley** [comment]
That's a good idea! I'd hate for people to skip over the tool because they think it's unmaintained, I'll see if there's a way to put a redirect in place.

Thanks!

~Timothy

**Comment by johnthagen** [comment]
I'd second either taking down read the docs or redirecting. As a new user it was confusing to see the old docs as a top hit on Google.

**Comment by timothycrosley** [comment]
I've put in place a client side redirect (using javascript) and a fallback redirect link and notice on the old read the docs site.

Thanks!

~Timothy
