### ISSUE TITLE
isort 5 no longer recognises `sre_parse` as a stdlib module

### ISSUE THREAD

**Issue by Zac-HD** [timothycrosley/isort#1304]
For example, sort 

```python
import re
import sre_constants
import sre_parse
```

and `sre_parse` will be placed in a new section, which is a regression from isort 4.3.21, where `sre_parse` was correctly treated as a stdlib module.

(and thanks for shipping isort 5!  The new API is great for [my `shed` project](https://pypi.org/project/shed/), and as a user I also really like the profile system :smile:)

**Comment by timothycrosley** [comment]
Thanks for reporting! This is fixed with an additional regression test added in 5.0.6. `shed` looks awesome! I'm glad you like the new release!

Thanks!

~Timothy

**Comment by Zac-HD** [comment]
Wow! Awesomely fast response, and I'm similarly delighted that you like shed 😍
