### ISSUE TITLE
isort 5 splits "as" imports onto new lines

### ISSUE THREAD

**Issue by Zac-HD** [timothycrosley/isort#1305]
One line I end up writing in a lot of scripts is

```python
from hypothesis import given, strategies as st
```

and both `black` and `isort` 4 are happy with this.  However, isort 5 prefers to split it onto multiple lines:

```python
from hypothesis import given
from hypothesis import strategies as st
```

which I don't like so much, but :man_shrugging:.  However, if you have a longer list of imported names or turn down the line length, it looks really weird indeed:

```python
from hypothesis import (
    given,
)                            # I did not expect these two lines to exist,
from hypothesis import (     # but they even come back if I delete them!
    strategies as st,
)
```

Maybe there's just a setting that I (or isort) could add to `--profile=black`, because the first form is definitely my favorite.

**Comment by timothycrosley** [comment]
Hi @Zac-HD, 

I agree the first form looks nicer! The configuration option to add to have that style is `combine_as_imports`. See: https://timothycrosley.github.io/isort/docs/configuration/options/#combine-as-imports. It also works nicely with the black profile, and I'll keep this in mind for that profile in the future. In case it's helpful, you can also try out different combinations of settings online now, here: https://timothycrosley.github.io/isort/docs/quick_start/0.-try.

Thanks!

~Timothy

**Comment by jdufresne** [comment]
WDYT about making `combine_as_imports` as default `True`? This behavior surprised me as well and I think most projects prefer these import as one line. By flipping the default, we'd require less configuration in default cases.

**Comment by abitrolly** [comment]
@jdufresne I've got the same qurstion #1812

**Comment by timothycrosley** [comment]
Just a heads up! It might be a bit of time before the next major release of isort is finished, but once that happens the default will be switched to this. It hasn't been switched earlier just because of isort's formatting guarantee
