### ISSUE TITLE
files are patched with --diff (5.0.6)

### ISSUE THREAD

**Issue by Yura52** [timothycrosley/isort#1306]
Hi! Just upgraded isort from 4.* to 5.0.6 and found out that isort apply changes when `--diff` is given. I applied it to a directory, if it is important.

P.S. Are there any options to turn off changes of "import a.b as b" to "from a import b" in 5.0?

**Comment by timothycrosley** [comment]
Thanks for reporting, a new patch release has been pushed that fixes this. 

The other issue you mentioned doesn't yet have a resolution but is being tracked here: https://github.com/timothycrosley/isort/issues/1280

Thanks!

~Timothy
