### ISSUE TITLE
asciinema recordings archived - switch to termynal?

### ISSUE THREAD

**Issue by StephenBrown2** [timothycrosley/isort#1307]
"This recording has been archived" messages are showing for all terminal demonstrations. e.g. on https://timothycrosley.github.io/isort/docs/quick_start/2.-cli/
<img width="692" alt="Screenshot 2020-07-09 at 09 40 01" src="https://user-images.githubusercontent.com/1148665/87060868-41d01f80-c1c8-11ea-9bc0-d4eb55282e2c.png">

Perhaps use https://github.com/asciinema/asciicast2gif or https://github.com/icholy/ttygif to convert them to gifs, or switch to https://showterm.io/?

Or possibly even use https://github.com/ines/termynal for a non-externally hosted solution that also works without JS?

**Comment by timothycrosley** [comment]
Thank you for reporting this issue!
I've fixed it by re-recording the terminal sessions while I authenticated. It was my error for not remembering to log on when first recording. I am however very happy with the existing service, as it's very very low effort and allows copy and paste.
