### ISSUE TITLE
Alphabetical sorting regardless of capitalization

### ISSUE THREAD

**Issue by r0mainK** [timothycrosley/isort#1309]
Hi there ! First off thanks for you work, this tool is awesome, using it has made my life pure bliss 👌 

My issue is th following:

I am currently using isort with the following flags, in order to replicate the appnexus import style:

```bash
isort  --line-width=100 \
         --force-single-line-imports \
         --force-sort-within-sections \
         --lines-after-imports=2 \
         --lines-between-types=0
```

I've been unable to find a way to sort imports alphabetically within a section **ignoring capitalization** , e.g. in this example I would like `LSTM` to be put after `Dense`, instead of before:

```python
from pathlib import Path

from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

from my_company_package import something


...
```

I would like to know if it's possible and I'm overlooking something or if it would need to be added. the reason I ask is because I use `isort` with the `flake8-import-order` extension, which raises a warning here.

Nothing pressing about this obviously, I was just wondering if something could be done.

Cheers !

**Comment by timothycrosley** [comment]
Hi @r0mainK,

Thanks for reaching out! I'm so glad you find isort helpful!

I think you are looking for `order_by_type`: https://timothycrosley.github.io/isort/docs/configuration/options/#order-by-type if this is set to False, the automatic type inference from capitalization will no longer be included. The CLI flag for the `False` value is `--dont-order-by-type`: https://timothycrosley.github.io/isort/docs/configuration/options/#dont-order-by-type.

Hope this is helpful!

~Timothy
