### ISSUE TITLE
No changelog posted for 5.0.9

### ISSUE THREAD

**Issue by johnthagen** [timothycrosley/isort#1311]
I'm not sure if the website just takes longer to update, or if it was accidentally missing but 5.0.9 (latest version) is not mentioned in the docs:

https://timothycrosley.github.io/isort/CHANGELOG/

**Comment by timothycrosley** [comment]
It's there now :) The website can be a bit delayed, though generally it's updated within an hour  - safely within 24. The changelog is generated from: https://github.com/timothycrosley/isort/blob/develop/CHANGELOG.md if it's ever behind by bit.

**Comment by bnavigator** [comment]
The changelog entry for 5.0.9 is broken again

**Comment by timothycrosley** [comment]
Thanks for the heads up! I've fixed it on both the markdown file and website :)
