### ISSUE TITLE
Extra newline before comment with -n --fss, 5.0.5+ regression

### ISSUE THREAD

**Issue by scop** [timothycrosley/isort#1315]
isort 5.0.5 and later (up to 5.0.9) adds a spurious newline before a comment in the following scenario with `-n --fss`:
```
$ cat t.py
import sys

# Comment canary
from . import foo
$ isort -n --fss t.py 
Fixing /tmp/t.py
$ cat t.py
import sys


# Comment canary
from . import foo
```

There shouid be only one newline between `import sys` and `# Comment canary`. 5.0.4 and earlier did not have this problem. It is also somehow specific to both `-n` and `--fss` being specified; neither alone triggers the issue.

**Comment by timothycrosley** [comment]
A fix for this has been deployed to PyPI in the [5.1.0 release](https://timothycrosley.github.io/isort/CHANGELOG/#510-july-14-2020), 

Thanks for reporting!

~Timothy

**Comment by scop** [comment]
Thanks; that case is fixed indeed but there are some other related ones lurking, see #1322
