### ISSUE TITLE
Tag 5.0.9 does not point to sources for released 5.0.9 PYPI package

### ISSUE THREAD

**Issue by bnavigator** [timothycrosley/isort#1316]
The github `5.0.9` tag and master branch are identical to `5.0.8` but should probably be b49aba99b919473b66f05b663588cfac2472c601. This effects into failing `test_file_contents` when using the tests against the PyPI 5.0.9 release:

```
[   30s] E       ValueError: not enough values to unpack (expected 13, got 12)
```

**Comment by timothycrosley** [comment]
Thanks for reporting! I've updated the branch and tag to match
