### ISSUE TITLE
isort is directory or CWD based in 5.x

### ISSUE THREAD

**Issue by Leymore** [timothycrosley/isort#1318]
``` bash
# zhoufengzhe @ as2 in /data/tmp/foo/bar  [1:15:03]
$ ls
baz.py  qux.py
# zhoufengzhe @ as2 in /data/tmp/foo/bar  [1:15:05]
$ isort qux.py
# zhoufengzhe @ as2 in /data/tmp/foo/bar  [1:15:08]
$ cat qux.py
import os

import numpy

import baz
# zhoufengzhe @ as2 in /data/tmp/foo/bar  [1:15:11]
$ cd ..
# zhoufengzhe @ as2 in /data/tmp/foo  [1:15:12]
$ isort bar/qux.py
Fixing /data/tmp/foo/bar/qux.py
# zhoufengzhe @ as2 in /data/tmp/foo  [1:15:16]
$ cat bar/qux.py
import os

import baz
import numpy
```

The output of `isort==5.0.9` is inconsistent if the command is called from different path. If I run `isort qux.py`, `baz` will be parsed as FIRSTPARTY, which is correct to my view. However if I run `isort bar/qux.py`, `baz` will be parsed as THIRDPARTY.

I find `isort==4.3.21` gives consistent output，so I tried `--magic-placement` in 5.0.9，but it's not working.

**Comment by timothycrosley** [comment]
Hi @Leymore,

Thanks for reaching out!

The current working directory, is considered an input for many tools - including isort! isort will do it's best to determine the root of your project, however, if there is not enough context to do so, it will fall back to the current working directory being the implied src_path. If this was a project placed in side a git repo or with a root configuration file this would not happen. However, it's easy to work around - just specify the [--src-path](https://timothycrosley.github.io/isort/docs/configuration/options/#src-paths) setting to the directory that sits at the root of your project (the directory if ran from isort produces the output you expect).

Hope this helps!

~Timothy
