### ISSUE TITLE
404 at "online configuration reference" link on docs -> Quick Start -> Command Line Usage page

### ISSUE THREAD

**Issue by JoanEliot** [timothycrosley/isort#1320]
Link is "http://127.0.0.1:8000/docs/configuration/options/" -- guessing that's not what you meant, and I was able to get to the correct page by editing the link. 

Page containing the above link is at
https://timothycrosley.github.io/isort/docs/quick_start/2.-cli/

**Comment by timothycrosley** [comment]
Thanks for reporting! This has been fixed both in develop and on the live site thanks to your report :)
