### ISSUE TITLE
Two extra newlines before comment with -n --fss

### ISSUE THREAD

**Issue by scop** [timothycrosley/isort#1322]
```
$ isort --version | grep VERSION
                    VERSION 5.1.0
$ cat t.py
import logging

# Comment canary
from foo import bar
import quux
$ isort -n --fss -d t.py
import logging



# Comment canary
from foo import bar
import quux
```

Two empty lines were insterted before the comment, but none should have been (i.e. the existing one should have been kept; no changes should have been made).

**Comment by timothycrosley** [comment]
This is fixed in the just released 5.1.1 version: https://github.com/timothycrosley/isort/releases/tag/5.1.1

Thanks!

~Timothy
