### ISSUE TITLE
New feature: support non-import python statements within import section

### ISSUE THREAD

**Issue by meitham** [timothycrosley/isort#1325]
I'm working with a large code base that has a ``sys.path.insert`` usually in the middle of the imports, the effect of that is the rest of the imports don't raise ``ImportError`.  An example:

```
  import os
  import foo; foo.hack_path()
  import bar  # without foo.hack_path() this raises an ImportError.
```

 I admit it is quite ugly hack, but it's not easy to fix given the status of the library.

Can we get something like this to be supported by isort?

Perhaps a flag in the middle of sections::
```

sections = 
    FUTURE
    STDLIB
    THIRDPARTY
    IMPORTHACK
    FIRST_PARTY

KNOWN_IMPORTHACK = "import foo; foo.hack_path()"
```

Is this easy/sensible to add?

**Comment by timothycrosley** [comment]
I don't think you need something like this if you upgrade to isort 5.0.0+, it should just work. Albeit it wont put it on the same line:

```
import os
import foo

foo.hack_path()

import bar
```

But if anything, I think that makes it a little less hacky
