### ISSUE TITLE
Line-length issue with black profile

### ISSUE THREAD

**Issue by Gricha** [timothycrosley/isort#1326]
Hey! Thanks for the release that's more compatible with black, it is awesome! I think I might've hit an interesting issue which I don't know what the right way of proceeding with would be. Consider this file:
```
from django.db.models.fields.related_descriptors import ForwardOneToOneDescriptor as ForwardOneToOneDescriptor  # noqa: F401
```

The contents of this file are irrelevant. What you'll see is this line has over 120 length with comment, but under 120 without comment.

If I run black on it: `black . -S --line-length=120`, it will reformat this import to:
```
from django.db.models.fields.related_descriptors import (
    ForwardOneToOneDescriptor as ForwardOneToOneDescriptor,
)  # noqa: F401
```
Which I think would be expected. Then if I `isort` it with the following configuration:
```.isort.cfg
[settings]
profile = black
line_length = 120
```
the result will be:
```
from django.db.models.fields.related_descriptors import ForwardOneToOneDescriptor as ForwardOneToOneDescriptor  # noqa: F401
```
again.

I'm curious if that's a bug or just misconfiguration. Please let me know if there is any way I can help here!

The version I'm running is 5.1.1

**Comment by timothycrosley** [comment]
Hi @Gricha!

I'm glad you're enjoying the new release of isort! I've fixed this issue in the develop branch and plan on making a new patch release tomorrow.

Thanks!

~Timothy

**Comment by Gricha** [comment]
Thank you @timothycrosley
