### ISSUE TITLE
Using sys.stdout as keyword default messes up stdout capture for downstream packages

### ISSUE THREAD

**Issue by bnavigator** [timothycrosley/isort#1330]
Keyword defaults are evaluated at import time, not at call time. This makes trying to capture sys.stdout output of `isort.api` calls with `show_diff=True` difficult. (regression through #1189)

https://github.com/timothycrosley/isort/blob/447580671b2e37a21a3cf1a4d2e80c387f9af98a/isort/format.py#L31-L33

See also
https://github.com/gforcada/flake8-isort/pull/92#issuecomment-660558770

**Comment by timothycrosley** [comment]
Thanks for reporting this issue and your great work on fixing `flake8-isort compatibility`! I've fixed the regression in the 5.1.4 patch release, and I think fixed the underlying issue of there being no official mechanism to capture the diff in development slated for the 5.2.0 release: https://github.com/timothycrosley/isort/issues/1335

Thanks!

~Timothy
