### ISSUE TITLE
config: Stricter correspondence between `sections = {"{BUILTIN}"}` and `known_{built_in}`?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [timothycrosley/isort#1332]
It took me a quick second to see the docs where it corresponds `known_first_party` to "FIRSTPARTY", `extra_standard_library` to "STDLIB", etc.

Would it be possible to make this pairing more obvious, and only be a casing name change?
(or even better, don't change the casing?)

Examples for TOML:
```
sections = [
  "first_party",
  "third_party",
]

# Use a dict, which should have .keys() == sections
known_imports = {
  first_party: [ ... ],
  third_party: [ ... ],
}
# - or -
known_imports.first_party = [ ... ]
known_imports.third_party = [ ... ]

# Use the existing precedent
known_first_party = [ ... ]
known_third_party = [ ... ]
```

(FWIW For deprecation, I think that can be done with a little intermediate translator function - something that also checks for bad redundancy, akin to fail-fast for #1331)

(Also, dunno what to do about simpler config formats... Perhaps the `.` accessor is compatible with other formats?)

**Comment by timothycrosley** [comment]
I think your suggestions are solid here, that said I'm very hesitant to make any API / config changes, especially deprecation, so soon after the 5.0.0 release even if there are helpful shims in place, that can technically make it backward compatible. In the short term I'll plan on adding better documentation and error reporting for this issue.
