### ISSUE TITLE
Use of wrap_length raises an exception about it not being lower or equal to line_length

### ISSUE THREAD

**Issue by rtasarz** [timothycrosley/isort#1333]
Given both line_length and wrap_length are provided in config file and set to the same value (100 in my case), following exception is thrown when import line that needs wrapping is encountered:
    `ValueError: wrap_length must be set lower than or equal to line_length: 100 > 92.`

**Comment by timothycrosley** [comment]
Thanks for reporting and providing a fix for this issue! The fix has been deployed in the 5.1.4 patch release.

~Timothy
