### ISSUE TITLE
How to best run isort on "# %% notebooks"?

### ISSUE THREAD

**Issue by mwouts** [timothycrosley/isort#1338]
Hi @timothycrosley , thanks for `isort`, this is an awesome tool!

I am wondering what is the best way to run `isort` on Jupyter notebooks, or actually, on their text representations. One of the most common representation of notebooks as text uses `# %%` to mark cells. So in the below I have a notebook with three cells:

```python
# %%
import numpy as np
np.array([1,2,3])

# %%
import pandas as pd
pd.Series([1,2,3])

# %%
# This is a comment on the second import
import pandas as pd
pd.Series([4,5,6])
```

When I run `isort` on that script, the `# %%` markers move together with the import, and that changes the cell structure in my notebook. Instead, I would want to get this:
```python
# %%
import numpy as np

# This is a comment on the second import
import pandas as pd
np.array([1,2,3])

# %%
pd.Series([1,2,3])

# %%
pd.Series([4,5,6])
```

Do you have any advice on how to best address this? Can I tell `isort` to ignore any line that starts with `# %%`?

Alternatively, I am considering adding an option to insert a blank line after the `# %%` cell marker in `jupytext` (https://github.com/mwouts/jupytext/issues/553), but I am not sure this is a great idea, as the option would probably be used only in the `--pipe` mode of `jupytext`, so it may be hard for users to understand why they have blank lines there and not elsewhere...

**Comment by timothycrosley** [comment]
Hi @mwouts, 

Thanks for reaching out! I'm glad you find isort useful!

This Jupyter notebook case is interesting to me. Certainly, as I'm sure you can imagine, this was not a use case that was envisioned for isort initially. My initial thought would be that you don't want isort to be changing this cross cells, and instead would want it to limit it's sorting within a cell? I personally, would find it very jaring to have my imports from a cell at the bottom make their way to the top cell. isort provides a way to do that, but you would need to use # isort: skip comment:


```
# %%
import numpy as np
np.array([1,2,3])

# %% isort: skip
import pandas as pd
pd.Series([1,2,3])

# %% isort: skip
# This is a comment on the second import
import pandas as pd
pd.Series([4,5,6])
```

I could theoretically see an option to configure what comments or fragments lead to a skip. I certainly don't think I could include `# %%` as a magic integration, as I don't know if there are any other users using that comment for something else.

**Comment by mwouts** [comment]
Thank you @timothycrosley for your quick response!

> My initial thought would be that you don't want isort to be changing this cross cells, and instead would want it to limit its sorting to within a cell?

Oh interesting! Well maybe that is very personal, but I tend to have a first cell where I import everything, so I am more on the side of moving all the imports at the top :smile:

> I could theoretically see an option to configure what comments or fragments lead to a skip

Yes, that is what I was looking for initially, something like `isort --ignore-line-starting-with '# %%'` (lines, as opposed to paragraphs), of course with a more concise option name ideally.

In the next days/weeks, I'll test adding an the extra line between the `# %%` comment and the cell content in the `py:percent` format in Jupytext, maybe that is a direction worth exploring... It seems to give me the expected interaction with `isort`. I'll confirm this and also check what is the impact on other tools like `black`.

**Comment by timothycrosley** [comment]
@mwouts this is now supported (via #1357) in the develop branch of isort if you want to try it:

to keep sorting within cell:
`isort y.py --treat-comment-as-code "# %%"`

to, like you desired, put all imports to the top likely in their own cell:
`isort y.py --treat-comment-as-code "# %%" --float-to-top`

Would love to hear what you think and if it works for your use case.

Thanks!

~Timothy

**Comment by mwouts** [comment]
Hi @timothycrosley , thank you a lot! I just gave a try to the two options, and I confirm they work as expected on my test notebook. I'll now test this on longer notebooks and keep you posted.

**Comment by MarcoGorelli** [comment]
@mwouts just in case this is useful to you, I've been developing a tool which allows you to do this directly on a Jupyter Notebook:

```bash
nbqa isort my_notebook.ipynb --treat-comment-as-code "# %%"
```

See [the repo](https://github.com/nbQA-dev/nbQA) for more details

**Comment by yasirroni** [comment]
The docs about `treat-comments-as-code` can be read [here](https://pycqa.github.io/isort/docs/configuration/options.html#treat-comments-as-code).

For pyproject.toml

```toml
[tool.isort]
treat_comments_as_code = ["# my comment 1", "# my other comment"]
```

**Comment by hectormz** [comment]
@yasirroni I looked at this thread before you commented, and had a hard time seeing how to set this in `pyproject.toml`. I came back to add it and I'm glad you beat me!

**Comment by plwalsh** [comment]
Does this still work? I'm using the latest isort 5.13.2, and if I create `test.py` using the first block of code from the OP, I end up a result that looks mostly like the second block of code from the OP (with differences in line spacing). The command I used was:

```
isort --float-to-top --treat-comment-as-code="# %%" test.py
```
