### ISSUE TITLE
indent is not preserved when isort:skip is used in nested import

### ISSUE THREAD

**Issue by sergeant-wizard** [timothycrosley/isort#1339]
Hello, love the project.

When running isort version 5.1.4 against the following file

```python
def foo():
    from looooooooooooooooooooooooooooooooong_module import (  # isort:skip
        loooooooooooooooooooooooooooooooooong_name1)
```

isort suggests to unident the third line:

```sh
isort --check --diff tmp2.py
ERROR: tmp2.py Imports are incorrectly sorted and/or formatted.
--- tmp2.py:before        2020-07-22 11:11:29.987441
+++ tmp2.py:after 2020-07-22 11:16:13.352721
@@ -1,3 +1,3 @@
 def foo():
     from looooooooooooooooooooooooooooooooong_module import (  # isort:skip
-        loooooooooooooooooooooooooooooooooong_name1)
+    loooooooooooooooooooooooooooooooooong_name1)
```

We expected isort to ignore since `isort:skip` is specified.

Also, isort 4.3.21 will not report any violations for this code.
Running `git bisect` with this test case got me to [this commit](https://github.com/timothycrosley/isort/commit/955e5b) as the breaking commit.

The problem seems to be interlaced with the nested situation, as isort does not report violations for the following:

```python
from looooooooooooooooooooooooooooooooong_module import (  # isort:skip
    loooooooooooooooooooooooooooooooooong_name1)
```

Environment

* python 3.7.4 (pyenv)
* ubuntu 18.04
* isort 5.1.4 (fails) / 4.3.21 (succeeds)

**Comment by timothycrosley** [comment]
This was just deployed with version 5.2.0 of isort. Thanks! 

~Timothy
