### ISSUE TITLE
Improve description of force_sort_within_sections

### ISSUE THREAD

**Issue by rjmorris** [timothycrosley/isort#1347]
I'm new to `isort`, and first let me thank you for the package. I was surprised to see how many configuration options are available, so I'm sure this is a lot of work to maintain.

I prefer to have my from-style imports mixed in with my straight-style imports, sorted by package/module name. I eventually found that `force_sort_within_sections = true` does this, but neither its name nor its description at https://timothycrosley.github.io/isort/docs/configuration/options/ make its behavior very clear. I suggest improving the description. Currently, it says:

> Force imports to be sorted by module, independent of import_type

But `import_type` isn't defined anywhere (except the source code), so it isn't clear that this refers to from-style imports vs. straight-style imports. What about the following instead?

> Don't sort straight-style imports (like `import sys`) before from-style imports (like `from itertools import groupby`). Instead, sort the imports by module, independent of import style.

(I used "style" here instead of "type" to distinguish from how "type" is used in `--dont-order-by-type`.)

Maybe it would also be useful to have a section on the docs Home page showing isort's default behavior with straight-style and from-style imports, pointing to `force_sort_within_sections` and `from_first` as options to change this behavior. But I could see the argument that this is too niche a feature to warrant inclusion on the home page.

**Comment by timothycrosley** [comment]
Thanks for reporting!

I've updated the documentation, per your wonderfully crafted description for both the CLI interaction and on the online docs (see: https://timothycrosley.github.io/isort/docs/configuration/options/#force-sort-within-sections), and I've added a section to the README page here: https://timothycrosley.github.io/isort/#controlling-how-isort-sections-from-imports

(Note you may need to force reload each page to get the new version)

One of the hardest things of having so many options, is making it as easy as possible for those that need them to discover them, so help with documentation, and knowing where the gaps are is always really appreciated.

Thanks!

~Timothy

**Comment by rjmorris** [comment]
Great, thanks so much for the quick response!
