### ISSUE TITLE
Why third_party and my_lib have not blank lines in 5.1.4 version.

### ISSUE THREAD

**Issue by 549982170** [timothycrosley/isort#1352]
Why third_party and my_lib have not blank lines in 5.1.4 version.

**Comment by timothycrosley** [comment]
I'm sorry you are experiencing this issue!

Please check the upgrade guide here: https://timothycrosley.github.io/isort/docs/upgrade_guides/5.0.0/#module-placement-changes-known_third_party-known_first_party-default_section-etc and see if it addresses your issue. likely you simply need to remove config options in the new version to get the appropriate behaviour. 

Here is the background of why the change: https://github.com/timothycrosley/isort/issues/1147
Example #1 of working through the upgrade process with a user: https://github.com/timothycrosley/isort/issues/1336
Example #2 of working through the upgrade process with a user: https://github.com/timothycrosley/isort/issues/659#issuecomment-664044267

If none of these solve your issue, please let me know by opening up a new issue referencing this one.

Thanks!

~Timothy
