### ISSUE TITLE
Ability to sort literals

### ISSUE THREAD

**Issue by timothycrosley** [timothycrosley/isort#1358]
isort should provide the capability to sort all common built-in non-complex literal types. Initially, it would only need to support non dynamic ones understandable by ast.literal_eval, but long term could support even complex definitions using ast parsing. Importantly the output format should be compatible with black by default and should be ran by any configured format function.

```
# isort: list
__all__ = ["b", "a", "c"]
```
would be come:
```
# isort: list
__all__ = ["a", "b", "c"]
```

There should be an additional option to dedup lists for the user (sets and others than are deduped within python should auto dedup):

```
# isort: unique-list
__all__ = ["a", "a", "b", "c"]
```

would become: 

```
# isort: unique-list
__all__ = ["a", "b", "c"]
```

This supersedes https://github.com/timothycrosley/isort/issues/392

**Comment by timothycrosley** [comment]
This is finished in develop and will be released in the 5.3.0 release.

**Comment by blthayer** [comment]
Hello @timothycrosley!

Sorry for the silly question, but I'm having trouble finding how to turn this functionality on within `isort`. I was unable to find any references to `literal` or `__all__` within the [options](https://pycqa.github.io/isort/docs/configuration/options.html), and my manually reading/skimming didn't come up with anything obvious.

Is it possible to turn on sorting of `__all__` via the `isort` CLI?

**Comment by jugmac00** [comment]
@blthayer Have you found out how to sort `__all__` meanwhile?

**Comment by blthayer** [comment]
> @blthayer Have you found out how to sort `__all__` meanwhile?

@jugmac00 - I have not, unfortunately. I just sort of dropped it as "not worth it for now" 😄 

Good luck, and if you find something I'd love to hear about it!

**Comment by jugmac00** [comment]
Looks like I figured it out 😉

https://github.com/PyCQA/isort/issues/1887
