### ISSUE TITLE
known_standard_library resets the stdlib list

### ISSUE THREAD

**Issue by ionelmc** [timothycrosley/isort#1368]
If you use `known_standard_library` then isort simply forgets about all the other stdlib modules. It's a pretty useless option and it would only be useful if you'd fill that option with all the stdlib modules. I belive it should be additive instead, and add modules to the already known ones, instead of reseting it.

**Comment by timothycrosley** [comment]
See: https://timothycrosley.github.io/isort/docs/upgrade_guides/5.0.0/#known_standard_library. You likely want to set `extra_standard_library`. Really neither mode should be needed as isort's standard library listing is exhaustive from Python's own documentation.

**Comment by ionelmc** [comment]
Ooof ... yeah, I just discovered `extra_standard_library` after diggig into the docs. I think it should be mentioned in the readme :)

**Comment by timothycrosley** [comment]
Good call! I've added a mention to the readme :)
