### ISSUE TITLE
isort doesn't sort IO from typing properly

### ISSUE THREAD

**Issue by zyxue** [timothycrosley/isort#1372]
with `import typing.X`, the isort result is as expected 

```
import typing.Any
import typing.IO
```

but with `from ... import ...`, the order seems wrong.

```
from typing import IO, Any
```

shouldn't it be 

```
from typing import Any, IO
```

instead?

I'm using isort **VERSION 4.3.21**.

**Comment by timothycrosley** [comment]
By default, isort groups from imports by the type implied by the casing of the import, see more here: https://timothycrosley.github.io/isort/docs/configuration/options/#order-by-type on all versions of isort you can turn this off: `--dont-order-by-type` on the latest version you can provide the correct type grouping manually in your config file `classes=IO`

Hope this is helpful! 

~Timothy
