### ISSUE TITLE
Add docs link to repo

### ISSUE THREAD

**Issue by louisguitton** [timothycrosley/isort#1378]
Hey @timothycrosley , thanks for this. I use this package as part of my cookiecutter (so basically almost all my projects).

Could you add https://timothycrosley.github.io/isort/ to the Github page 🙏 ?
![image](https://user-images.githubusercontent.com/7823843/90039804-705d8080-dcc7-11ea-9e2f-029669ccc6ef.png)

This might sound silly but I was just looking for the configuration docs that I think used to be on the Readme, and I ended up looking for that link.

**Comment by timothycrosley** [comment]
Thanks for the recommendation! I've updated added the link to the side bar :) I'm so glad you find isort useful BTW!

~Timothy
