### ISSUE TITLE
Known other does not work anymore with .editorconfig

### ISSUE THREAD

**Issue by erdnaxeli** [timothycrosley/isort#1383]
Hi,

The doc says we can use `know_something` in the config file: https://timothycrosley.github.io/isort/docs/configuration/options/#known-other. There is no example for editorconfig but it used to work on 4.x branch. It does not work anymore because of this line: https://github.com/timothycrosley/isort/blob/develop/isort/settings.py#L657. As the key cannot be in `_DEFAULT_SETTINGS`, it is dropped.

Thanks.

**Comment by timothycrosley** [comment]
Thanks for reporting! This has been fixed in isort 5.4.2

~Timothy
