### ISSUE TITLE
Black incompatibility

### ISSUE THREAD

**Issue by kunalb** [timothycrosley/isort#1388]
Creating a new issue based on the comments on #694 

```diff
-from .trace import (
-    DurationTraceEvent,
-    FlowBindingPoint,
-    FlowTraceEvent,
-    Phase,
-    Trace,
-)
+from .trace import (DurationTraceEvent, FlowBindingPoint, FlowTraceEvent,
+                    Phase, Trace)
```

isort keeps moving the imports to two lines, and black then breaks them apart again.
 
My pyproject.toml  (I've also tried without the line lengths, only keeping the profile):

```
[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79
```

In case it helps, the actual code is at https://github.com/kunalb/panopticon/blob/master/panopticon/tracer.py#L13 .

Thanks!

**Comment by kunalb** [comment]
Er, I just realized I was on isort 4.x because of pylint, goes away with the latest version. Sorry about that!

**Comment by timothycrosley** [comment]
No worries! Glad to hear 5.0.0 resolved it :)
