### ISSUE TITLE
How do I set the config for one import per line with hanging vertical formatting?

### ISSUE THREAD

**Issue by NorthIsUp** [timothycrosley/isort#217]
What config options do I set to get the following results:

When there is a single import from a library it should be on one line and where there are multiple imports they should be using the hanging vertical formatting (#3). I can only seem to force this behavior with the line_length option, but that often results in a \ being used as a continuation.

```
from my.very.long.import.path import module
from os import path
from sys import (
    argv,
    stdout,
)
```

and not

```
from my.very.long.import.path \
    import module
from os import \
    path
from sys import (
    argv,
    stdout,
)
```

this is the config I am currently using
```
[isort]
add_imports=__future__.absolute_import
default_section=THIRDPARTY
import_heading_firstparty=Project Library
import_heading_stdlib=Standard Library
import_heading_thirdparty=External Libraries
indent=4
known_third_party=django,celery,disqus
line_length=1
multi_line_output=3
diff=1
```

**Comment by NorthIsUp** [comment]
bump?

**Comment by collinanderson** [comment]
I'm seeing this problem too.

**Comment by NorthIsUp** [comment]
I added a pull request for this #222

**Comment by collinanderson** [comment]
Nice. Is it possible to make the change without changing the indent? That would make the PR easier to review.

**Comment by NorthIsUp** [comment]
The indent changed because the nesting level changed. (it moved up one if statement)

**Comment by collinanderson** [comment]
Exactly, is there a way to fix this without changing the nesting level? I'm just thinking that might help the PR get accepted.

**Comment by NorthIsUp** [comment]
maybe, but I don't have the time to figure out a different way.

**Comment by timothycrosley** [comment]
Hi @NorthIsUp,

This is supported using your pull-request in version 3.9.5.

Thanks again!

~Timothy
