### ISSUE TITLE
Option to specify maximum single line length vs wrapping width

### ISSUE THREAD

**Issue by collinanderson** [timothycrosley/isort#225]
It would be nice to say: if the imports are longer than 100 characters, wrap at 80 characters

For example:

    from django.core.exceptions import FieldDoesNotExist, FieldError, PermissionDenied, ValidationError
    from django.forms.models import (
        BaseInlineFormSet, inlineformset_factory, modelform_defines_fields,
        modelform_factory, modelformset_factory)

**Comment by timothycrosley** [comment]
HI @collinanderson,

Thanks for the suggestion! I agree this would be a useful feature, and will implement it before the next version of isort.

~Timothy Crosley

**Comment by timothycrosley** [comment]
Hi @collinanderson,

This is now supported in release 3.9.5 - using the wrap_length setting documented here  https://github.com/timothycrosley/isort/wiki/isort-Settings

Thanks!

~Timothy

**Comment by collinanderson** [comment]
Wow. That was fast! Thanks!
