### ISSUE TITLE
encoding lines are damaged.

### ISSUE THREAD

**Issue by spookylukey** [timothycrosley/isort#226]
With current master, isort puts a space before a `# -*- coding` line, which is wrong, and in some cases seems to delete the line altogether. This didn't happen with 3.9.4

**Comment by spookylukey** [comment]
Actually, a test case as simple as this fails:

    # Comment
    import sys

isort strips the comment line.

I've attempted to fix this, but the ad-hoc, highly stateful parsing code is rather intimidating.

Have you looked at using the parser from 2to3 as a basis for this project? I recently had to do some automated Python source code work, and found lib2to3 to be the best way to parse Python code at this level. I was able to rewrite functions to add decorators and things on that level.

lib2to3 is rather undocumented, and of course it was written for another purpose, but it does the right kind of parsing. [python-modernize](https://github.com/mitsuhiko/python-modernize) is built on 2to3, for example.

**Comment by timothycrosley** [comment]
Hi @spookylukey,

Thanks for reporting this issue! I will make sure it is fixed prior to the next release. Regarding how isort performs it's parsing:

I have researched parsing differently and have so far not achieved good results. I'm completely open to restructuring how isort parses and moves imports but this would be a major re-factoring and be beyond the scope of a bug fix. Additionally, it would need to conform to isorts unique design goals:

- Run quickly over large amounts of code
- Run on both Python2 and Python3 code with one isort installation

I think both of these are possible to be achieved with a better parsing approach, and hopefully something like this could be done for release 4.0, I certainly would be very open to any pull requests that included such improvements.

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
Hi @spookylukey,

This issue has been fully resolved in release 3.9.5 and a test added for both provided cases to ensure it wont occur again.

Thanks!

~Timothy

**Comment by spookylukey** [comment]
Thanks so much!
