### ISSUE TITLE
Look in $VIRTUAL_ENV/src for potential 3rd party libraries

### ISSUE THREAD

**Issue by spookylukey** [timothycrosley/isort#227]
As well as `site-packages` etc., `os.environ['VIRTUAL_ENV'] + '/src'` (if it exists) could be used as a heuristic to detect 3rd party libraries. This is the directory used by pip when installing packages from a github/bitbucket URL, instead of PyPI.

**Comment by timothycrosley** [comment]
Hi @spookylukey,

Thanks for this suggestion! This sounds like it could be help improve isorts heuristics for virtualenv projects dramatically - I'll investigate adding it before next release.

Thanks!

~Timothy Crosley

**Comment by timothycrosley** [comment]
Hi @spookylukey,

A variation of this has been added in release 3.9.5 to better support use within a virtualenv.

Thanks!

~Timothy

**Comment by spookylukey** [comment]
That's great, thanks. As well as the `$VIRTUAL_ENV/.../site-packages` directories, there is also the `$VIRTUAL_ENV/src` directory, which is used by pip for packages that are downloaded from GitHub e.g. when you do `pip install -e git+https://github.com/ridethepony/django-fiber@48d1af8867e19b9e27332d2b98ca07a47927de15#egg=django-fiber`. This doesn't seem to be accounted for in the latest release.

**Comment by spookylukey** [comment]
This has been incorrectly closed - modules found in the "$VIRTUALENV/src" dir are not included in the 'third party' imports.

**Comment by spookylukey** [comment]
Please can we re-open this?

**Comment by timothycrosley** [comment]
Hi @spookylukey,

Sorry this wasn't reopened sooner! Didn't see your original request to reopen it, hopefully will have some time to work on this soon.

Thanks!

~Timothy

**Comment by spookylukey** [comment]
No, problem, I know how these things easily get missed! Thanks.

**Comment by jmagnusson** [comment]
This would be a great feature to have. Right now I have to have a ginormous list in `known_third_party` to circumvent this.

**Comment by timothycrosley** [comment]
This is *finally* implemented here: https://github.com/timothycrosley/isort/commit/9e384025d147ccd7b975e661b42cdb4f5363a918 and on it's way to develop, Really sorry about the long delay! I've been heads down working on hug: https://github.com/timothycrosley/hug and am just now taking the time to clean up and fix issues on isort for a 5.0.0 release soon. 


Thanks!

~Timothy

**Comment by spookylukey** [comment]
Thanks so much!
