### ISSUE TITLE
combine_as_imports option not documented in README

### ISSUE THREAD

**Issue by timgraham** [timothycrosley/isort#229]

**Comment by timothycrosley** [comment]
Hi @timgraham,

Thanks for the input! Unfortunately as the number of settings available to isort has expanded I've had to move some of the documentation to the wiki, including the general information about isort settings which is then linked to in the readme. You can see the documentation for this setting here: https://github.com/timothycrosley/isort/wiki/isort-Settings

Thanks!

~Timothy Crosley
