### ISSUE TITLE
Any plan for "import *" ?

### ISSUE THREAD

**Issue by douglarek** [timothycrosley/isort#231]
@timothycrosley any plan for this ? 

example:

```
from os import *
```

to be:

```
from os import path, chmod
```

**Comment by timothycrosley** [comment]
Hi @douglarek,

Thanks for the inquiry! I'm not sure I understand fully what you mean? Currently you set isort to combine imports into *,  or leave them separate with a config option. If you mean to actually intelligently figure out what from * is used and import only that - I think this would be very dangerous and hard to get right in a highly dynamic language such as Python. For instance, even if we spent the time and had all the information about what was available in a module and what was used from that module - there would still be the possibility that code was evaluated that used something in the module we couldn't detect. Additionally someone could even do globals()[var] and access an import that we could not pre-determine. 

I would certainly accept a pull-request that did this, but I think it would be very hard to get right - and would need to default to being off.

Thanks!

~Timothy

**Comment by douglarek** [comment]
@timothycrosley thanks, you are right !
