### ISSUE TITLE
"from" sorted behind "import", which is non-alphabetical

### ISSUE THREAD

**Issue by reinout** [timothycrosley/isort#234]
isort sorts 'from' behind 'import':

    import os
    import readline
    import shutil
    import subprocess
    import sys
    import webbrowser
    from datetime import datetime
    from string import Template

Alphabetically, "from" sorts before "import", so this interferes  a bit with the regular sorting that people do, like calling "sort-lines" in emacs.

Is there a specific reason for this? I don't remember seeing it in pep8.

**Comment by timothycrosley** [comment]
Hi @reinout,

Pep8 doesn't seem to specify it one way or the other (that I can see), however all the projects I've worked on so far have used this standard so It is the one I adopted for isort. I think the logic behind it is that the most basic imports come first followed by more complex ones. However, I can see the logic behind the other approach as well and will include an option to manage them that way before the next release.

Thanks so much for pointing out this issue!

~Timothy

**Comment by reinout** [comment]
Ok, thanks!

**Comment by timothycrosley** [comment]
Hi @reinout,

This is now fixed and released in version 3.9.5. You can enable by setting the from_first setting - documented here: https://github.com/timothycrosley/isort/wiki/isort-Settings

Thanks!

~Timothy

**Comment by reinout** [comment]
Works like a charm now!
