### ISSUE TITLE
schedule a new release for pypi

### ISSUE THREAD

**Issue by NorthIsUp** [timothycrosley/isort#244]
I want to get the sublime text plugin updated with all the new stuff, but I want to make sure you think it is stable first. Any thoughts on when the next release is?

**Comment by timothycrosley** [comment]
Hi @NorthIsUp,

A new release was done just a few minutes ago: 3.9.5. This release should be stable and includes all your fixes as well as general improvements, and is documented here: https://github.com/timothycrosley/isort/releases/tag/3.9.5

Thanks!

~Timothy

**Comment by NorthIsUp** [comment]
SUPER AWESOME!

-- 
Adam Hitchcock
Sent with Airmail

On February 5, 2015 at 2:27:48 PM, Timothy Edmund Crosley (notifications@github.com) wrote:

Hi @NorthIsUp,

A new release was done just a few minutes ago: 3.9.5. This release should be stable and includes all your fixes as well as general improvements, and is documented here: https://github.com/timothycrosley/isort/releases/tag/3.9.5

Thanks!

~Timothy
