### ISSUE TITLE
Isort does not support multiline values in config files

### ISSUE THREAD

**Issue by brianpeiris** [timothycrosley/isort#254]
I want to be able to list imports on multiple lines for readability and ease of editing. ConfigParser supports this but isort does not parse the value correctly.
Example:

```cfg
[settings]
known_third_party=
    django,
    boto,
    celery,
```

**Comment by timothycrosley** [comment]
@brianpeiris thanks for alerting me to this discrepancy! I agree the above syntax should be supported and will try to make sure it is prior to the next release.

Thanks! 

~Timothy

**Comment by helenst** [comment]
It looks as if this was (perhaps unintentionally?) fixed in c731b692634a5edfd5831bdba611795a3b1f9cfa since `strip` is now being called on each item in the tokenised list.

**Comment by timothycrosley** [comment]
Hi @helenst,

Thanks for nothing this. It was intentionally added as a fix for the 4.0 release, that was just pushed to PYPI

Thanks!

~Timothy

**Comment by helenst** [comment]
:balloon: Thanks for the new release!

**Comment by keimlink** [comment]
Thanks for the release @timothycrosley :thumbsup:
