### ISSUE TITLE
Integration with PyCharm

### ISSUE THREAD

**Issue by ramusus** [timothycrosley/isort#258]
Is it possible to integrate isort features to PyCharm ?

**Comment by benkonrath** [comment]
I'm interested in this as well.

**Comment by Septembers** [comment]
Want to support [PyCharm](https://www.jetbrains.com/pycharm/)

**Comment by jmfederico** [comment]
Super interested in this!

**Comment by teeberg** [comment]
You can set up an external tool like this:
![screen shot 2015-04-23 at 11 16 46 am](https://cloud.githubusercontent.com/assets/199071/7304139/15d0ab94-e9aa-11e4-9711-f08cd236f2c2.png)
![screen shot 2015-04-23 at 11 17 56 am](https://cloud.githubusercontent.com/assets/199071/7304109/ec989980-e9a9-11e4-8708-a450791fc185.png)
Then, you can even bind it to a shortcut for easy access:
![screen shot 2015-04-23 at 11 20 45 am](https://cloud.githubusercontent.com/assets/199071/7304163/5274212a-e9aa-11e4-8963-f80a8cdb6344.png)

**Comment by ramusus** [comment]
awesome, thanks a lot for solution!

**Comment by sunprophit** [comment]
I does not work correctly if isort placed somewhere outside of project, i.e. ~/.virtualenvs/*
3rd party modules and project modules are merged together
Though I guess it is pycharm problem - it uses full path when running external program

**Comment by teeberg** [comment]
`isort` does not always correctly detect which modules are third-party and which ones are yours. You can tell it to treat certain modules as third-party by passing `-o module_name` (`-o` is short for `--thirdparty` according to `isort --help`). I ended up creating an `.isort.cfg` in my project's top level folder which contains a section like this:
```
[settings]
known_third_party=caching,provider
```
This can then be nicely versioned and everybody in your team is on the same page. :-) From inside pycharm, I'm then invoking `isort` as
```
$PyInterpreterDirectory$/isort --settings-path $ProjectFileDir$ $FilePath$
```

Looking at the code, it treats all packages as third-party that have either `site-packages` or `dist-packages` in their import path. That probably doesn't include any packages that you installed via `pip install -e`.

**Comment by ramusus** [comment]
+1 for the trick with settings

**Comment by sunprophit** [comment]
Thanks for $PyInterpreterDirectory$/isort
I have been running system wide isort which does not have many of project specific 3rd party modules that is why it treated them and project modules the same way.

**Comment by teeberg** [comment]
As of #434, you can now also simply pass `--virtual-env <dir>` to `isort`, wherever it is installed

**Comment by mr-bo-jangles** [comment]
No longer needed, Pycharm does this itself now :)

**Comment by Skyross** [comment]
@teeberg Update the solution with the description for "Output Filters setup" for console clickable links
https://www.jetbrains.com/help/pycharm/2017.2/add-edit-filter-dialog-2.html?utm_medium=help_link&utm_source=from_product&utm_campaign=PY&utm_content=2017.2

**Comment by teeberg** [comment]
@Skyross my console output only shows:
```
/Users/jonas/code/project/env/bin/isort --settings-path /Users/jonas/code/project --virtual-env=/Users/jonas/code/project/env/bin/../ /Users/jonas/code/project/api.py

Process finished with exit code 0
```
which part of that do you want to make clickable?

**Comment by Skyross** [comment]
@teeberg In a case of having any errors in sorting. You will get some output with file paths if you run without automatic reformatting. If you running any `--diff` command for example.

**Comment by teeberg** [comment]
@Skyross I'm not sure if you're asking how to do that or if you're asking me to include those instructions in the guide above. If the former, adding this output filter did it for me:
![image](https://user-images.githubusercontent.com/199071/30745509-c72f11a0-9fa6-11e7-9630-981a7fca2d49.png)
However, the way I set up the example above, it always runs on the file that you currently have open anyway, so any filenames that could be matched in the output would just point back to the file that's already open. So I'm still not clear about what you're trying to accomplish. How did you set up isort in pycharm?

**Comment by mpasternak** [comment]
I was unable to set it up like that, because PyCharm kept running isort external tool without proper paths to virtual environment. 

I needed to hardcode the path (think ``export PYTHONPATH=/Users/mpasternak/envs/bpp/lib/python3.7/site-packages/                 
``) in the shell script, then run that shell script, then run sort. 

Without it, isort as ran by PyCharm was unable to ``import isort.main``

**Comment by rohe** [comment]
If I set up isort as an external tool it seems to be a general setting for PyCharm that is used across all projects I'm working on.
Is there a way to set project specific _working directory_ ??
Or is there a way to say: use the projects root directory ?

**Comment by atten** [comment]
This configuration automatically picks current virtualenv and working dir:
![image](https://user-images.githubusercontent.com/2737960/129018197-eabb9dcc-5033-4663-9783-cf5bc2f12a9a.png)
