### ISSUE TITLE
Cant get to detect first_party modules with django

### ISSUE THREAD

**Issue by leebrooks0** [timothycrosley/isort#259]
Here is a cas.api.views.py file (api is the app):

```
from rest_framework import status
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from api import models, serializers, utils
from django.contrib.auth import hashers
from django.core import signing
from django.db import transaction
from django.http import Http404
```

I have tried setting a .isort.cfg file in the project root, but I am still having no luck in getting api modules to the end of the import list

```
[settings]
known_first_party=api
```

**Comment by leebrooks0** [comment]
It fixed itself when I removed the cfg file?

**Comment by ssbb** [comment]
Same issue, also tried with -p arg in command line:

    isort -df -p "apps" views.py

Result:

    from django.views.generic.edit import CreateView, DeleteView, UpdateView

    from apps.utils.views import LoginRequiredMixin

    from .forms import ApplicationForm
    from .models import Application

**Comment by magicjohnson** [comment]
+1

**Comment by LuRsT** [comment]
I just found out about this project and I'm having the same problem :(

**Comment by benesch** [comment]
Haven't actually dug into the code, but setting

```
default_section=THIRDPARTY
```

worked for me. Otherwise, I think the default section is is `FIRSTPARTY`, so both `api` and `django` get counted as first party and are sorted alphabetically.

**Comment by jamesbeith** [comment]
How about this...
```
known_api=api
sections=FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER,API
```
http://isort.readthedocs.org/en/stable/#custom-sections-and-ordering

**Comment by timothycrosley** [comment]
I've been unable to reproduce this with the latest code, it looks like isort was incorrectly putting django in firstparty thus why explicitly stating that api was firstparty didn't resolve. isort now is much more intelligent about how it categorizes these things by default especially when within a virtualenv.

Thanks!

~Timothy
