### ISSUE TITLE
Support aliases

### ISSUE THREAD

**Issue by leebrooks0** [timothycrosley/isort#263]
I rerported this issue https://github.com/public/flake8-import-order/issues/33 here too, as I am not sure where the issue lies.

 I am using Google style imports:
```
from django.contrib.auth import models as auth
from django.contrib.auth import hashers
```

The linter I linked to is complaining about the order and says I should swap them around.
Obviously one way or the other is the correct way.

Is isort sorting correctly and the linter needs to take aliases into account, or is the linter correct?

**Comment by timothycrosley** [comment]
@leebrooks0, neither is correct or incorrect, there is some ambiguity in pep8 on purpose and it does not define exactly what to do. It never meant to be a gospel but only a quick guidline. isort assumes you want to group aliases together, and flake8 must assume you do not. isort has plenty of options to allow the flake8 style behavior.

Thanks!

~Timothy
