### ISSUE TITLE
Sort without sections option?

### ISSUE THREAD

**Issue by gforcada** [timothycrosley/isort#271]
Hi,

first, thanks for this awesome library!

Would it be possible to add a new command line switch to force strict ordering of imports without splitting them into sections (i.e. stdlib, etc etc)?

Is ``isort`` modular enough so that you can plug new sorting algorithms externally?

At @plone we have a style guide which basically says:

- keep imports one per line
- first all "from X import Y" and then after a blank line all "import X"
- without any distinction of stdlib, external libraries, etc etc

Could this style be provided by isort itself or can we plug it in?

**Comment by timothycrosley** [comment]
Hi @gforcada, Ill be looking into supporting this for the next release of isort and update this issue before the next release. Thanks for notifying me of this issue!

~Timothy

**Comment by gforcada** [comment]
@timothycrosley thanks for merging!

A release would be extra nice :)

**Comment by timothycrosley** [comment]
Fixed in version 4.1.0

Thanks!

~Timothy
