### ISSUE TITLE
No support for non-locale encodings

### ISSUE THREAD

**Issue by DRMacIver** [timothycrosley/isort#272]
If I run isort against the following file saved as utf-8 when the locale specifies a utf-8 encoding (e.g. en_GB.UTF-8), everything works fine:

```python
# coding=utf-8

snowman = "☃"
```
If I set LC_ALL=C first, it errors, despite the encoding comment explicitly saying this is a utf-8 file.

In Python 3 there's tokenize.open for handling this. I'm not aware of a backport, but there might be one (or it might be easy to create one, as it's pure Python).

**Comment by timothycrosley** [comment]
This should now be supported in isort 4.0 just released on PYPI,

Thanks!

~Timothy
