### ISSUE TITLE
py.test should not use local config

### ISSUE THREAD

**Issue by wimglenn** [timothycrosley/isort#278]
When running the tests using 

`py.test`

The config file from user `~/.isort.cfg` is still loaded up.  This can cause many test failures since the user can customise max line length etc.  

The test runner should know to patch out his own (default) configs, so that the tests are always executed from a known initial state.

**Comment by timothycrosley** [comment]
@wimglenn,

I agree with this assertion. Will try to get a fix in for this before the next release.

Thanks!

~Timothy
