### ISSUE TITLE
skip statements

### ISSUE THREAD

**Issue by simonzack** [timothycrosley/isort#295]
Some statements need to be nested within imports, is there a way for isort to ignore them?

Here's the motivating example:

```
import matplotlib
matplotlib.use('Agg')  # isort:skip
import matplotlib.pyplot as plt
```

the use Agg must be called before the plt import. `isort:skip` doesn't work here.

**Comment by simonzack** [comment]
I'm not sure how this would be implemented though as isort would not be aware of the proper ordering unless it's specified somehow.

**Comment by timothycrosley** [comment]
hi @simonzack,

Thanks for submitting this issue! I think this is one people run into a lot and don't report, I certainly run into it myself, so it's great to have it documented. After putting some thought into it, I think one potential solution would be to add a list of 'stop_patterns' that when contained in a line isort stops looking for imports. This isn't ideal, but would let you group all your normal imports  together (and automatically be sorted) and have all your magic imports below, manually sorted. Ideally, the imports that really on magic such as matlib use, and sys.path.append, would generally be minimal.

What do you think of this idea?


Thanks again!

~Timothy

**Comment by tino** [comment]
:+1: for this as well, got the same problem with matplotlib.

Would this work?

```python
import logging

# isort:maintain_block
import matplotlib
matplotlib.use('Agg')  
# isort:end_maintain_block

import matplotlib.pyplot as plt
```

Meaning that isort can shuffle above and below the `maintain_block`, but not over it?

**Comment by simonzack** [comment]
@timothycrosley Sorry about the late reply, I've forgot about this issue :( That's an interesting idea but it wouldn't sort the imports below the block. The following still looks nicer:

    import logging
    import matplotlib
    matplotlib.use('Agg')
    import yaml

    from yaml import load

than this:

    import logging
    import yaml

    from yaml import load
    
    import matplotlib
    matplotlib.use('Agg')

 I think @tino 's solution can fix this, although isort could also treat the block as a single item to sort, so in this case it still uses the line `import matplotlib`.

Perhaps it could also be done inline:

    import logging
    import matplotlib  # isort:block
    matplotlib.use('Agg')  # isort:end_block
    import matplotlib.pyplot as plt

**Comment by blueyed** [comment]
I think for starters it would be good if `isort:skip` would be kept with the line above.

My use case is with django-configurations, which has this pattern:

```
 from configurations import importer
 importer.install()  # noqa  # isort:skip
```

**Comment by tino** [comment]
Hmm, that might actually be a simple starting point indeed. I think it would have to work with multiple lines as well though, as these three need to be in this order (now that would work because of the default sorting, but that might not always be the case):

```
import matplotlib 
matplotlib.use('Agg')  # noqa  # isort:skip
import matplotlib.pyplot as plt  # isort:skip
```

**Comment by blueyed** [comment]
I think this block would also be covered by "stick lines with `isort:skip` to the one above".

Only `import matplotlib` would then be sorted, with the other lines below as-is.

**Comment by elbenfreund** [comment]
I just wanted to provide another common use case. Gtk will output warning if no specific minimal version is specified:

```
gi.require_version('Gdk', '3.0')  # NOQA
gi.require_version('Gtk', '3.0')  # NOQA
from gi.repository import Gdk, Gtk
```

**Comment by elbenfreund** [comment]
Is there by any change news on this? Or a viable workaround?

One way or the other: thanks for all your work! :)

**Comment by cas--** [comment]
Thought I would share a viable workaround for isort and flake8:

```python
import gi  # isort:skip
gi.require_version('PangoCairo', '1.0')  # NOQA: E402

# isort:imports-thirdparty
from gi.repository import PangoCairo

# isort:imports-firstparty
from my.module import MyClass

#isort:import-localfolder
from .common import util
```

**Comment by petobens** [comment]
This vim plugin prevents this situation by avoiding moving imports from the original placement: https://github.com/tweekmonster/impsort.vim

Can something like that be implemented? Are there any plans to work on this (i.e since the original issue has over 3 years now). Thanks!!

**Comment by petobens** [comment]
Hi @jdufresne I've noticed that you've making several changes to the library recently... any plans to tackle this issue? Thanks!

**Comment by Hnasar** [comment]
I thought this was implemented with #679 but PR #843 says
> Expected behavior is now that all isort:skip and NOQA imports will be moved to bottom, unsorted.

:(

There's still a need for this when doing [something like](https://python-gtk-3-tutorial.readthedocs.io/en/latest/introduction.html):

```python
import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk
```

**Comment by timothycrosley** [comment]
closing as the latest development branch (which will be release 5.0.0) includes extensive support for skipping statements as well as simply turning isort on and off over sections of code as needed.

**Comment by petobens** [comment]
Hi @timothycrosley can you point to some examples of will this work? Thanks

**Comment by Mattwmaster58** [comment]
@timothycrosley Hi, I was wondering if it were possible to skip rearranging blocks but still rearrange within the block as someone in this thread has already mentioned?

**Comment by PetterS** [comment]
@timothycrosley when will this version be released?

**Comment by sfdye** [comment]
Can we re-open this? It seems the latest released version does not allow you to skip a code statement and and version 5.0.0 is not released yet.

**Comment by duanyutong** [comment]
I'm running version 4.3.21 and it always wants to move the import marked as `isort:skip` to the end of all imports, instead of leaving it alone in place. Seems to be a related issue.

**Comment by duanyutong** [comment]
> @duanyutong one could interpret that as sort moving the imports after your skips to before.

Yes, either way, the same end result produced, not leaving skipped imports in place.

**Comment by thommiano** [comment]
See latest release: https://pycqa.github.io/isort/docs/upgrade_guides/5.0.0/

**Comment by thommiano** [comment]
For anyone running isort < version 5, this works for me:
```
import matplotlib  # isort:skip

matplotlib.use("agg")  # noqa: E402
import matplotlib.pyplot as plt  # isort:skip
```
`python --version`
> Python 3.7.0
`isort --version`
> VERSION 4.3.21
`flake8 --version`
>3.7.8 (mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.1) CPython 3.7.0 on Darwin

**Comment by exhuma** [comment]
For those looking for the official docs: https://pycqa.github.io/isort/#skip-processing-of-imports-outside-of-configuration

**Comment by earshinov** [comment]
I still don't understand how `isort:skip` is supposed to work. My code:

```python
from __future__ import annotations

# noinspection PyUnresolvedReferences
from . import global_config  # isort:skip

from typing import List, NamedTuple

import psycopg2
import psycopg2.extras
```

becomes

```python
from __future__ import annotations

from typing import List, NamedTuple

import psycopg2
import psycopg2.extras

# noinspection PyUnresolvedReferences
from . import global_config  # isort:skip
```

From the [docs](https://pycqa.github.io/isort/#skip-processing-of-imports-outside-of-configuration): "To make isort ignore a single import simply add a comment at the end of the import line containing the text isort:skip". Apparently me and `isort` have different ideas about what the verb "ignore" means in this case. Is there a way to prevent `isort` from moving the `global_config` import below the others other than disabling `isort` for the entire file?

**Comment by NoahCardoza** [comment]
Not sure if this will be helpful to anyone but:

I came here thinking I was facing the same issue until I realized that `autopep8` will also try to move imports to the top of the file. If you happen to have `pep8` installed try adding a `.pep8` config file at the root of your project:

`.pep8`:
```
[pycodestyle]
ignore = E402
```

Might be worth noting I'm using VS Code.

**Comment by timothycrosley** [comment]
Sorry everyone! I have a hard time keeping closed issues updated in response to comments. However, if anyone is wondering how to do the kind of "skip" that results in the import staying exactly where it is, (resulting in 2 import sections surrounding it), isort 5 has support for this using the "# isort: split" action comment. See the complete guide here: https://pycqa.github.io/isort/docs/configuration/action_comments.html

**Comment by ax3l** [comment]
Just to complete that section: how to combine `noqa` with `isort: skip` in a line?
```py
import a  # noqa isort:skip
```
or
```py
import a  # noqa  # isort: skip
```
?

**Comment by DhruvKoolRajamani** [comment]
Just add a `,` to separate the too.

```python
import a # noqa: <Error>, isort: skip
```

**Comment by brianefurlong** [comment]
Heads up in accounts.models.py:

Line 7 has a comment to make isort stop trying to move it above the import in line 5. When it does that, it results in a circular import. Is there a way to prevent the circular import?

**Comment by waketzheng** [comment]
> Just add a `,` to separate the too.
> 
> ```python
> import a # noqa: <Error>, isort: skip
> ```

Worked! Thanks~

But the way, the following lines not work as expected:
----
~import a  # isort: skip,noqa: \<Error>~   &nbsp;&nbsp; # Note: `noqa:` must be in front of `isort:`
~import a  # type:ignore,noqa: \<Error>,isort: skip~  &nbsp;&nbsp; # mypy/flake8 not work, isort work
~import a  # noqa: \<Error>,isort: skip,type:ignore~ &nbsp;&nbsp; # mypy not work, isort/flake8 work
