### ISSUE TITLE
Unable to get --skip option working correctly

### ISSUE THREAD

**Issue by edmorley** [timothycrosley/isort#296]
1) Clone https://github.com/mozilla/treeherder (revision 1c00ccf for reproducibility)
2) `pip install -r requirements/common.txt -r requirements/dev.txt`
3) `isort --recursive --skip bin/peep.py,deployment/update/update.py,treeherder/webapp/wsgi.py --check-only .`

Expected:
Output does not mention the three files listed under skip. Or alternatively, `isort --help` explains what syntax I'm supposed to use.

Actual:
```bash
ERROR: /home/vagrant/treeherder/bin/peep.py Imports are incorrectly sorted.
ERROR: /home/vagrant/treeherder/deployment/update/update.py Imports are incorrectly sorted.
ERROR: /home/vagrant/treeherder/tests/etl/test_classification_mirroring.py Imports are incorrectly sorted.
ERROR: /home/vagrant/treeherder/tests/log_parser/test_artifact_builder_collection.py Imports are incorrectly sorted.
ERROR: /home/vagrant/treeherder/tests/log_parser/test_job_artifact_builder.py Imports are incorrectly sorted.
ERROR: /home/vagrant/treeherder/tests/log_parser/test_log_view_artifact_builder.py Imports are incorrectly sorted.
ERROR: /home/vagrant/treeherder/tests/log_parser/test_performance_artifact_builder.py Imports are incorrectly sorted.
ERROR: /home/vagrant/treeherder/treeherder/etl/pushlog.py Imports are incorrectly sorted.
ERROR: /home/vagrant/treeherder/treeherder/etl/tasks/classification_mirroring_tasks.py Imports are incorrectly sorted.
ERROR: /home/vagrant/treeherder/treeherder/webapp/wsgi.py Imports are incorrectly sorted.
ERROR: /home/vagrant/treeherder/treeherder/webapp/api/artifact.py Imports are incorrectly sorted.
ERROR: /home/vagrant/treeherder/treeherder/webapp/api/exceptions.py Imports are incorrectly sorted.
ERROR: /home/vagrant/treeherder/treeherder/webapp/api/projects.py Imports are incorrectly sorted.
ERROR: /home/vagrant/treeherder/treeherder/webapp/api/urls.py Imports are incorrectly sorted.
```

I also tried using the same command as above, but without the commas, but that did not help.

Using isort 4.0.0 with Python 2.7.10 on Ubuntu 14.04.

**Comment by timothycrosley** [comment]
Hi @edmorley,

sorry for the delay! The --skip option uses the standard arg parse way of applying a list of arguments, which is to repeat the parameter. IE instead of --skip option1,option2 use:

    isort --skip option1 --skip option2

Hope this helps.

Thanks!

~Timothy

**Comment by edmorley** [comment]
Would it be possible to update the usage line/man page and/or the readme to document this?
That syntax wasn't overly obvious to me, and other than say for pip (with it's `-r` option), I'm struggling to think of other tools that only support multiple arguments like that :-)

**Comment by timothycrosley** [comment]
@edmorley, Ill update the usage documentation :). Thanks for letting me know that it's confusing, and I'm sorry I didn't get to this issue sooner! I was admittedly distracted by my new project: https://github.com/timothycrosley/hug

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
I've added the information to the terminal documentation here:

https://github.com/timothycrosley/isort/pull/315/files

and to the wiki here:

https://github.com/timothycrosley/isort/wiki/isort-Settings

Thanks!

~Timothy

**Comment by edmorley** [comment]
Awesome, thank you :-)
