### ISSUE TITLE
Add changelog file

### ISSUE THREAD

**Issue by adamchainz** [timothycrosley/isort#300]
When I upgrade dependencies, I'm thorough. Right now I want to read the changelog from `isort` 3.9.6 to 4.0.0, but I couldn't find it in the repo, on PyPI, or on the github wiki. It took me a few minutes to find the relevant commits and form the github compare url https://github.com/timothycrosley/isort/compare/f482da3752f520f74da6b9de098f1735b3b540cf...e44278e7b19efb54e21aff39dff1fe3871675c47 then try figure out what was important.

Please add changelog/history file :+1:

**Comment by timothycrosley** [comment]
Hi @adamchainz,

I agree a changelog file will be super useful and I'll start one on this release

~Timothy

**Comment by timothycrosley** [comment]
Fixed in version 4.1.0

Thanks!

~Timothy
