### ISSUE TITLE
Add support to run library module (python -m)

### ISSUE THREAD

**Issue by AbsoluteMSTR** [timothycrosley/isort#305]
Add support to run library module (python -m)
example:
`python -m isort -rc .`
like you can with
`python -m pip install -U isort`

**Comment by timothycrosley** [comment]
Hi @AbsoluteMSTR, I'm definitely open to implementing this, I'm not sure how to do this or what the use case is. Do you have a use case in mind and?

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
Your fix for this has been pushed out with release 4.2.0,

Thanks!

~Timothy
