### ISSUE TITLE
add an option to quiet the giant banner output and the skipped message

### ISSUE THREAD

**Issue by diwu1989** [timothycrosley/isort#317]
I only want isort to print out failures, so I would like an option to squelch the annoying banner output in the latest version and the `Skipped X files` message

**Comment by timothycrosley** [comment]
Hi @diwu1989,

Thanks for the input! I agree a quiet option would be useful and will try to put one in before the next release.

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
Fixed in release 4.1.1 with the addition of the `-q` or `--quiet` options
