### ISSUE TITLE
Option to order by module's package path, ignoring case

### ISSUE THREAD

**Issue by 7imon7ays** [timothycrosley/isort#318]
I'm working on a project following Google's Python style guide. It says: "Within each grouping, imports should be sorted lexicographically, ignoring case, according to each module's full package path".

http://google-styleguide.googlecode.com/svn/trunk/pyguide.html?showone=Imports_formatting#Imports_formatting

I believe isort configurations currently allow `from` imports to come either before or after straight imports within a section. Is there an option to order imports by package path, regardless whether they are `from` or straight? Also, is there an option to ignore case?

If not, would you consider these options worth adding?

With these isort would become compatible with flake8-import-order: https://github.com/public/flake8-import-order

**Comment by timothycrosley** [comment]
Hi @7imon7ays,

Have you tried the isort -fas option implemented here: 

https://github.com/timothycrosley/isort/pull/294/files

I believe it should fix your issue, if not let me know! I'll update the wiki to note this option exists as well.

Thanks!

~Timothy

**Comment by 7imon7ays** [comment]
Thanks for pointing out that option. Can I force alphabetical sorting, but only within sections? I'd still like standard libs to appear first and internal libs to appear last.

Is there an option to ignore case so that `a` comes before `Z`?

Thanks again!

**Comment by timothycrosley** [comment]
Hi @7imon7ays, 

Sorry for not getting back sooner! However, I have some good news: as of the just released version 4.2.2 of isort, this is now fully supported. To enabled this set `force_sort_within_sections` to `True` and set `order_by_type` to `False`.

As shown here: https://github.com/timothycrosley/isort/blob/develop/test_isort.py#L1619

Thanks!

~Timothy

**Comment by Saksow** [comment]
Thanks for hint @timothycrosley ! Can you add the order_by_type option to readme ? Would help other people in my situtation
