### ISSUE TITLE
Revisit ASCII art banner

### ISSUE THREAD

**Issue by timgraham** [timothycrosley/isort#325]
The ASCII art banner is cute, but seems unnecessary to me and creates extra work when scrolling through your console's history. I don't know of any other programs that do something like this, so I'm wondering what the reasons were for the addition. I know the `--quiet` command line option was added to suppress it, but it's a bit annoying to have to specify that every time. Thanks for your consideration!

**Comment by timgraham** [comment]
I saw you adding `'quiet': False` to `settings.py` but this is a bit misleading as `main.py` checks the arguments not the isort config, so it can't be overridden like the other config options.

**Comment by graingert** [comment]
:+1: for a revisit

**Comment by timothycrosley** [comment]
Thanks for the feedback guys, There are other tools like the redis & my own hug server that use ascii art - however I think it might make more sense for something like a server (where you run and then forget it) then for a cli app that your run over and over. I think it might make more sense to keep it, but hide it in the version menu for next release

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
This should be fixed in the just released 4.2.0,

Thanks!

~Timothy
