### ISSUE TITLE
Support running `isort` with no additional options on the CLI

### ISSUE THREAD

**Issue by edmorley** [timothycrosley/isort#338]
I'd like to add isort to the Travis run for a repo, so it enforces import style. However before I can do that, it needs to be easy for devs to run locally using the exact same settings as in the Travis run.

With flake8 we do this by adding the appropriate settings to setup.cfg, which then allows the use of a bare `flake8` call with no additional options. This runs flake8 recursively against the repo, taking into account the excluded directories in setup.cfg.

With isort there is currently no way to do this, so we'll either have to use a wrapper script, or get devs to remember to run:
`isort -rc .`
or say:
`isort --recursive --check-only --diff .`

Now I think it makes sense for a bare `isort` call to be non-destructive, so I guess it may have to be the equivalent of `--diff`? Or perhaps what mode is run by default could be specified in setup.cfg?

Thanks :-)

**Comment by timothycrosley** [comment]
I agree, this would definitively be an improvement in the project usability. I'm thinking a bare isort would show you the diff and then ask if you want to apply it [Y/n]?

Thanks for suggesting this feature!

~Timothy

**Comment by edmorley** [comment]
That sounds even better than what I had in mind - thank you :-)

**Comment by timothycrosley** [comment]
This is now officially supported in the just released isort 4.2.0

Thanks!

Timothy

**Comment by edmorley** [comment]
Works really well - thank you :-)

**Comment by edmorley** [comment]
> This is now officially supported in the just released isort 4.2.0

PyPI and the tags are updated, but https://github.com/timothycrosley/isort/releases is listing 3.9.6 as the latest release (until the "show newer tags" link is clicked). Could you update the GitHub latest feature thing to avoid confusion? :-)

**Comment by timothycrosley** [comment]
Should be fixed! Thanks for alerting me to the issue, I'll have to add to my per-release checklist to publish the release on github

Thanks!

~Timothy

**Comment by edmorley** [comment]
No problem - thank you! :-)
