### ISSUE TITLE
Wildcards for import groups

### ISSUE THREAD

**Issue by joaoponceleao** [timothycrosley/isort#347]
Hi,
I haven't managed to get this to work, wondered if there's a way.
Using isort, with the config in an editorconfig file.
Use case:
In django, one ends up having multiple apps/modules inside the project. A common way to organize these, is to use an `projectName_*` prefix (i.e. something_accounts, something_api, etc...). I would like to have all these sorted by isort within a section (first_party or named section), but the only way i've managed to do this is by referencing them explicitly one by one in editorconfig.
Can i not simply do something like `first_party=something_.\S*`?
It would make things much easier and not have update the config everytime a new project app is created.

**Comment by timothycrosley** [comment]
HI @joaoponceleao, 

I agree this could be very useful! I'll try to make sure and implement a solution for this before the next release of isort.

Thanks!

Timothy

**Comment by lundberg** [comment]
@joaoponceleao think we have the same issue, could you try my pull request and see if the solution fits and solves your problem?
