### ISSUE TITLE
isort should not make use of sys.setdefaultencoding('utf8')

### ISSUE THREAD

**Issue by lnielsen** [timothycrosley/isort#348]
On Python 2, isort has a call to ``sys.setdefaultencoding('utf-8')`` (https://github.com/timothycrosley/isort/blob/develop/isort/pie_slice.py#L166). While it might be convenient to use for ensuring strings always get decoded/encode with utf8, this call has system-wide effects on every other Python module installed. In particular this is a problem when using e.g. pytest-isort to integrate import sorting checks (similar to pep8 checks with pytest-pep8).

Following raises a UnicodeEncodeError:
```
f = open("test.txt", "w")
f.write(u'\xe6\xf8\xe5')
```

The following doesn't raise an error:
```
import isort
f = open("test.txt", "w")
f.write(u'\xe6\xf8\xe5')
```

**Comment by timothycrosley** [comment]
Unfourtantly, This is really necessary for any amount of easy backwards compatibility with Python2. really there are so many ways to not have to worry about this, that it isn't something the project should have to work around (you can install isort as a global Python3 package and then this code wont even get executed.) Python3 has been out for a looooooong time, at this point the fact isort chooses to support Python2 at all should be seen as a kind gesture, my future projects are not.

**Comment by lnielsen** [comment]
Thanks for answer, and thanks for the support Python 2 as well. The only reason that I'm concerned with Python 2, is because we also as a kind gesture support Python 2 on our projects.

I fully understand that you do not wish to spend time fixing this, and we're grateful for the time already spend on isort, but just as a last opinion I'd rather see Python 2 support removed from isort, than having the call to ``sys.setdefaultencoding('utf-8')``. The call has so many unwanted side-effects, that I'd rather see people forced to use Python 3.

**Comment by timothycrosley** [comment]
@lnielsen, the reason I do not remove Python2 entirely is because the use case for most people is to run isort as a command on systems that may only have Python2 available, am I correct that under this use case no unwanted side-effects should occur? I'm open to making changes / including work arounds to resolve this, especially if a pull request is given
