### ISSUE TITLE
"Apply suggested changes" prompt does nothing on plain "enter"

### ISSUE THREAD

**Issue by edmorley** [timothycrosley/isort#349]
1) Run `isort` with no params, but a config file present
2) At the `Apply suggested changes to '...' [Y/n/q]?` prompt, press enter

Expected:
Enter does the default action (ie `Y`, since it's in capitals). Alternatively, the `Y` should not be in capitals.

Actual:
The prompt is repeated.

**Comment by timothycrosley** [comment]
Hi @edmorley,

Thanks for reporting this! I'll make sure to lowercase the Y before the next release as that is indeed very confusing behavior.

Thanks!

~Timothy

**Comment by MinchinWeb** [comment]
:+1:

**Comment by timothycrosley** [comment]
This has now been fixed and will make its way into the next release.

Thanks!

~Timothy
