### ISSUE TITLE
Mixed EOL characters after running isort

### ISSUE THREAD

**Issue by cmeeren** [timothycrosley/isort#350]
After running isort, my editor complains about mixed EOL characters. Could isort detect the EOL characters being used and use them?

**Comment by timothycrosley** [comment]
Hi @cmeeren,

Thanks for reporting this issue! I'll see if I can find a way to more correctly handle EOL

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
This is now fixed in develop and should make its way into the next release.

Thanks!

~Timothy

**Comment by cmeeren** [comment]
Thanks! :smile:
