### ISSUE TITLE
isort on Hanging Grid Grouped sometimes uses line continuations rather than braces

### ISSUE THREAD

**Issue by graingert** [timothycrosley/isort#351]
eg

``` python
from datascience.early_warning_system import device_activations as ews_device_activations
```

becomes

``` python
from datascience.early_warning_system import \
    device_activations as ews_device_activations
```

rather than

``` python
from datascience.early_warning_system import (
    device_activations as ews_device_activations
)
```

**Comment by timothycrosley** [comment]
Thanks for reporting this issue!

I have an idea of what is causing this and will work on fixing it soon.

Thanks!

~Timothy

**Comment by mjholtkamp** [comment]
I have the same issue. If you also use `use_parentheses = true`, it will not use line continuation, but parenthesis. However, it will still not honor `multi_line_output = 5` or `include_trailing_comma = true` :)

The output will be (I'm using graingert's example):

```
from datascience.early_warning_system import (
    device_activations as ews_device_activations)
```

Which is *almost* what I want :)

**Comment by timothycrosley** [comment]
Closing this issue as it is now fixed in develop,

Thanks!

~Timothy

**Comment by mjholtkamp** [comment]
Nice :) Any idea when you would like to release a new version on pypi?
