### ISSUE TITLE
'ISortCommand' has no such option 'not_skip'

### ISSUE THREAD

**Issue by Azd325** [timothycrosley/isort#356]
This error appears where I'm running `python setup.py isort`

_Commandline_

``` bash
~/p/q (isort) $ python setup.py isort
running isort
error: error in setup.cfg: command 'ISortCommand' has no such option 'not_skip'

```

_setup.cfg_

```
[isort]
not_skip = __init__.py
```

**Comment by timothycrosley** [comment]
I'll look into this, thanks for reporting, sorry for the long wait, been heads down working on hug: https://github.com/timothycrosley/hug

Thanks!

~Timothy
