### ISSUE TITLE
#isort:imports-thirdparty removes imports

### ISSUE THREAD

**Issue by cas--** [timothycrosley/isort#357]
I am opening a new issue as it appears my comment in closed issue #177 has been missed. This still applies to 4.2.2

I just tried using those comments with isort 4.0 and adding either `#isort:imports-thirdparty` or `#isort:imports-firstparty` causes imports to be removed:

```
-#isort:imports-thirdparty
-import gobject
-import gtk
-from twisted.internet import gtk2reactor
-from twisted.internet.error import ReactorAlreadyInstalledError
-
 try:
     # Install twisted reactor, before any other modules import reactor.
     reactor = gtk2reactor.install()
@@ -26,31 +20,6 @@
     # Running unit tests so trial already installed a rector
     pass
 
-#isort:imports-firstparty
-import deluge.common
-import deluge.component as component
...
```

**Comment by timothycrosley** [comment]
Thanks for reporting, I'll be looking into this, sorry for the long wait I've been heads down working on hug: https://github.com/timothycrosley/hug

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
This has been fixed in develop here: https://github.com/timothycrosley/isort/pull/407/files and will make its way into the next release.

Thanks!

~Timothy
