### ISSUE TITLE
Adding blank line on every run.

### ISSUE THREAD

**Issue by euresti** [timothycrosley/isort#358]
I'm running isort with this setting:

```
[settings]
multi_line_output=3
```

Starting with a file that looks like this:
```
"""This is a docstring"""
# This is a comment
from __future__ import (
    absolute_import,
    division,
    print_function,
    unicode_literals
)
```

Running isort once will give me this file:
```
"""This is a docstring"""

# This is a comment
from __future__ import (
    absolute_import,
    division,
    print_function,
    unicode_literals
)
```

But running isort again will give me this file:
```
"""This is a docstring"""


# This is a comment
from __future__ import (
    absolute_import,
    division,
    print_function,
    unicode_literals
)
```

And the more I run isort the more blank lines it adds.  The only solution is to move the comment above the docstring or below the imports.

**Comment by timothycrosley** [comment]
I'll look into this, thanks for reporting! Sorry for the long wait, I've been heads down working on hug: https://github.com/timothycrosley/hug

**Comment by timothycrosley** [comment]
This has been fixed here: https://github.com/timothycrosley/isort/pull/406/files and will make its way into the next release.

Thanks so much for reporting!

~Timothy
