### ISSUE TITLE
Setting to skip an entire directory

### ISSUE THREAD

**Issue by jamesbeith** [timothycrosley/isort#360]
I'd like to skip an entire directory using a setting such as:
`skip=vendor/**`

**Comment by jamesbeith** [comment]
Using the command line argument _does_ work though, just not using `skip` in a settings file.
`isort --recursive --skip vendor/** .`

**Comment by jamesbeith** [comment]
Appears I can use the settings file and command line argument without asterisks to skip a directory.
`skip=vendor`
`isort --skip vendor`

So I guess what remains that I _could_ use asterisks in the command line argument but _not_ in the settings file.

**Comment by timothycrosley** [comment]
I'll look into this,

Thanks for reporting!

Sorry for the long wait, been heads down working on hug https://github.com/timothycrosley/hug

**Comment by timothycrosley** [comment]
Sorry after revisiting this, you can use ** in the args but you must use skip_glob as your doing a different kind of skip: 'skip_glob' the reason for the separation is that in your example its not isort that's allowing you to do ** but bash itself which is translating that to a list sent to isort. This is specific to your console and console configuration, several people even using the same OS will not have the same behavior, and is entirely independent of isort. For isort to do these calculations as efficiently as possible it is designed to only skip globs when explicitly asked to do so.

Hopefully this is helpful.

Thanks!

~Timothy

**Comment by jamesbeith** [comment]
Thanks Timothy. I came across `skip_glob` literally a week or so ago when setting up isort on a new project. Was meaning to close this ticket since. Thank for investigating.
