### ISSUE TITLE
No way to turn off --order-by-type

### ISSUE THREAD

**Issue by levic** [timothycrosley/isort#366]
If invoked on the command line, --order-by-type can be passed and will set order_by_type to True , but settings.py already has an order_by_type default of True.

It's therefore not possible to turn this off.

Ideally this (and other boolean options) would have a --no-XXX option that reverses the sense (and so would allow you to override an .isort.cfg file in the case that it had already enabled a flag)

**Comment by timothycrosley** [comment]
Agreed and I'll make sure to address this before the next release.

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
Implemented as -dt or --dont-order-by-type and merged into develop, will make its way into the next release

Thanks!

~Timothy
