### ISSUE TITLE
ConfigParser doesn't handle duplicate keys as expected

### ISSUE THREAD

**Issue by levic** [timothycrosley/isort#368]
```
[settings]
skip_glob=*/settings/*.py
skip_glob=*/node_modules/*.py
```

The last entry overwrites the first. This only happens in .ini files (command line arguments use argparse append so work as expected).

**Comment by levic** [comment]
(This presumably also applies to all appendable items in the command line arguments, I don't see any special case code for them)

**Comment by timothycrosley** [comment]
As you mentioned yourself isort is doing the right thing and simply using ConfigParser, so this would be a bug for ConfigParser and not isort. But really I think ConfigParser is doing the right thing too as what you have specified is really too ambiguous (it's not clear if you want both or want to override the first) and there's already 2 good ways to do this:

    skip_glob=*/settings/*.py, */node_modules/*.py

or

    skip_glob=*/settings/*.py
                     */node_modules/*.py

That are much more obvious and explicit as to your intentions. Hope this is helpful.

Thanks!

~Timothy

**Comment by yskomur** [comment]
It's not basic like that
example: systemd.network config
```ini
[Network]
Address=1.2.3.4/24
Address=2.4.5.6/24
DNS=8.8.8.8
DNS=8.8.4.4
```
generated by python, read from systemd-networkd

**Comment by yskomur** [comment]
It's not basic like that
example: systemd.network config
```ini
[Network]
Address=1.2.3.4/24
Address=2.4.5.6/24
DNS=8.8.8.8
DNS=8.8.4.4
```
generated by python, read from systemd-networkd

**Comment by yskomur** [comment]
It's not basic like that
example: systemd.network config
```ini
[Network]
Address=1.2.3.4/24
Address=2.4.5.6/24
DNS=8.8.8.8
DNS=8.8.4.4
```
generated by python, read from systemd-networkd
