### ISSUE TITLE
Sorting for "from x import y" is case-sensitive, but for "import x" is case-insensitive

### ISSUE THREAD

**Issue by apinkney97** [timothycrosley/isort#370]
Sample input file:
```python
import b, C, A
from A import b, C, A
```

On running isort (with default options) we get:
```python
import A
import b
import C
from A import A, C, b
```

whereas I would expect one of
```python
import A
import b
import C
from A import A, b, C
```
or
```python
import A
import C
import b
from A import A, C, b
```

Furthemore, `import B, C, b, A` sorts to
```python
import A
import B
import b
import C
```
and `import b, C, B, A` sorts to 
```python
import A
import b
import B
import C
```

so it looks as if the sort for this ignores case completely. In my opinion it would be better to have one unambiguous ordering of imports, so case should be taken into account for both `from x import y` and `import x`.

**Comment by timothycrosley** [comment]
Thanks for reporting this! However, this is intended and by-design. When doing from imports isort wants  to separate CONSTANTS, Classes, and variables from each-other. It is generally safe to assume this is not a consideration when sorting straight imports. This is logical, and easy to change with isort config options to any format you want.

Thanks!

~Timothy

**Comment by cans** [comment]
Well giving the option to choose whether I want that or not would be very nice.

**Comment by nickwilliams-eventbrite** [comment]
Yeah, as an organization, we sort our imports differently (always case-insensitive sorting regardless of import type), so it's a pain that there's no setting to control case sensitivity or anything similar at all).

**Comment by timothycrosley** [comment]
I am so sorry that I didn't catch these follow up questions! If you see my original reply - I do say that this is configurable in isort - it has been for years. The default setting which causes this to happen is:

`order_by_type`

which defaults to True. Simply setting order_by_type to False in a config file or doing --dont-order-by-type on the command line should give you the behavior that you want. You can see a full list of settings here: https://github.com/timothycrosley/isort/wiki/isort-Settings

Thanks! 

~Timothy

**Comment by Zacharias030** [comment]
@timothycrosley is this broken?
```python
✗ isort myfile.py --dont-order-by-type
Traceback (most recent call last):
  File "/usr/local/bin/isort", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/isort/main.py", line 812, in main
    config = Config(**config_dict)
  File "/usr/local/lib/python3.7/site-packages/isort/settings.py", line 422, in __init__
    super().__init__(sources=tuple(sources), **combined_config)  # type: ignore
TypeError: __init__() got an unexpected keyword argument 'dont_order_by_type'
```
