### ISSUE TITLE
'pathlib' is part of the Python 3.4 standard library

### ISSUE THREAD

**Issue by MinchinWeb** [timothycrosley/isort#382]
Using `isort`, it moves *pathlib* at the bottom of the third group (First party?), even though it has been [part of the standard library since Python 3.4](https://docs.python.org/3/library/pathlib.html).

I'm using isort 4.2.2 with Python 3.5.1 x64 on Windows 10. I have no configuration file set up.

Here's isort's output:
```python
import codecs
import fileinput
import multiprocessing
import os
import re
import sys
import textwrap
import uuid
import webbrowser
import zipfile
from datetime import date, datetime

import colorama
from colorama import Back, Fore, Style
from invoke import run, task

import minchin.text
import requests
import winshell
from bs4 import BeautifulSoup
from pathlib import Path
```

**Comment by timothycrosley** [comment]
Thanks for reporting! This has now been resovled in Develop and will make it's way into the next release.
