### ISSUE TITLE
Have option to move imports within functions/code blocks to top?

### ISSUE THREAD

**Issue by ghost** [timothycrosley/isort#385]
I would like to move imports within (nested) functions/code blocks to the top of the file. Is it possible to add an option enabling this (in the simplest way possible, not necessarily handling edge cases?).

**Comment by endrebak** [comment]
This seems to exist as an option, force to top or `-t`, but it does not do what I want to do - perhaps I misunderstand how it is to be used?

```python
for i in blah:
    import sys
    ...
```

should become 

```python
import sys
for i in blah:
    ...
```

**Comment by timothycrosley** [comment]
Since only 1 user asked for this, and they no longer have a github account I'm closing. Still open to this idea however
