### ISSUE TITLE
Packages installed via pip from git URIs aren't detected as third-party

### ISSUE THREAD

**Issue by saxbophone** [timothycrosley/isort#386]
Hi,

Recently had a problem where I was using a version of a library pinned to a git commit rather than a pypi version (due to the project not having made a proper release in ages).

I didn't realise that `isort` wasn't registering this library as a third-party library and instead suggesting that it was a first-party library that I had written.

When the library eventually made a new release and I moved the version pin to the latest version, `isort` was complaining that the imports weren't sorted correctly and it took a while to work out it was because it was now aware that the library was third-party and the code had to be amended to correct the ordering.

For details, here is the version I had pinned to a commit (in the format required by pip when installing from requirements files):

```
-e git://github.com/jezdez/django-configurations.git@5ece1070448d3e026b81422691c60207f5699c0c#egg=django-configurations
```

And what I changed it to:

```
django-configurations==1.0
```

I wonder if this is a bit related to #227 ? (I am using virtualenv).

Thanks in advance, love the library on the whole!

**Comment by bartekbrak** [comment]
You are installing a package in editable mode (usually this is for no good reason, unless you plan to develop it as well), so it becomes a first party. Contrary to popular belief, packages from github should not be installed with `-e`.

**Comment by saxbophone** [comment]
Aha! Thanks @bartekbrak for clarifying this, sorry for the noise!
