### ISSUE TITLE
New lines characters handled differently between operating systems. (assumption)

### ISSUE THREAD

**Issue by calvin** [timothycrosley/isort#391]
In *nix box, we don't experience this issue, but in Windows, we regularly see an `isort` result as the following:

```diff
.../isort.exe --diff --recursive --check-only --skip settings/development.py .
ERROR: ...\manage.py Imports are incorrectly sorted.
--- ...\manage.py:before	2016-02-01 14:46:04.483437
+++ ...\manage.py:after	2016-02-08 20:09:55.593976
@@ -1,7 +1,7 @@
 #!/usr/bin/env python
-import os
-import sys
-
+import os
+import sys
+
 if __name__ == "__main__":
     os.environ.setdefault("DJANGO_SETTINGS_MODULE", "....settings.development")
 
```

At sight, it seems like there are no differences between __before__ and __after__.

At this stage reporting, the only known characteristics of the problematic environment are that it is running Windows 7 and Python 3.5 (__after__) as opposed to *nix and python 2 (__before__).

**Comment by timothycrosley** [comment]
Thanks for reporting! I'll look into this, and also look into integrating app veyor Windows based automated testing into hug to avoid issues like this in the future. Just like I have done for hug https://github.com/timothycrosley/hug

**Comment by timothycrosley** [comment]
This should now be fixed and make its way into the next release.

Thanks!

~Timothy
