### ISSUE TITLE
sort __all__

### ISSUE THREAD

**Issue by stevenxxiu** [timothycrosley/isort#392]
Is it reasonable to include functionality to sort `__all__ = [export_1, export_2]`?

**Comment by timothycrosley** [comment]
I think this would be a cool feature. And in theory not too difficult to add. I may not have time to add it as I've been heads down working on hug: https://github.com/timothycrosley/hug but would be very open to a pull request that added it

**Comment by virusdefender** [comment]
+1

**Comment by timothycrosley** [comment]
Closing this, in favour of the more general approach for the same goal laid out here: https://github.com/timothycrosley/isort/issues/1358
