### ISSUE TITLE
Handle leading indent

### ISSUE THREAD

**Issue by blueyed** [timothycrosley/isort#398]
Imports do not seem to get sorted when they are indented?!

```
echo "    from a import d, c" | isort - 
    from a import d, c
```

That's necessary/useful when you want to sort imports inside of a function.

I am using this Vim commands for that:

```
" Sort Python imports.
command! -range=% -nargs=* Isort :<line1>,<line2>! isort --lines 79 <args> -
command! -range=% -nargs=* Isortdiff :<line1>,<line2>w !isort --lines 79 --diff <args> -
```

**Comment by timothycrosley** [comment]
Hi @blueyed, this is a design decision and simply is too costly / probably impossible to consistently handle correctly as discussed at length here: https://github.com/timothycrosley/isort/issues/302

Thanks!

~Timothy
