### ISSUE TITLE
forced_separate for globs/matches

### ISSUE THREAD

**Issue by danpalmer** [timothycrosley/isort#399]
Given the configuration:

```ini
[isort]
forced_separate=*.models
```

And the file:

```python
import os

from myproject.foo.models import Foo

from myproject.utils import util_method

from myproject.bar.models import Bar

import sys
```

I would expect the following output.

```python
import os
import sys

from myproject.utils import util_method

from myproject.bar.models import Bar
from myproject.foo.models import Foo
```

But instead I get:

```python
import os
import sys

from myproject.bar.models import Bar
from myproject.foo.models import Foo
from myproject.utils import util_method
```

I realise that globbed matches aren't supported here, but wonder if this could be added, or if it would be easy to add do you think, if I wanted to try?

**Comment by danpalmer** [comment]
Hi, just a quick ping on this, if I decided to write this feature, is it something that would be considered for inclusion in `isort`?

**Comment by timothycrosley** [comment]
Hi @danpalmer,

I would def accept a pull request that supported this feature.

Thanks!

~Timothy

**Comment by danpalmer** [comment]
I've started writing this (https://github.com/timothycrosley/isort/compare/develop...danpalmer:globbed-forced-separate), however it's turning out to be a lot more complex, once we want the `forced_separate` to apply to local imports as well, as it seems that in `place_module`, they can be _either_ local or separate, not both.

I haven't worked much further on this yet, and will come back to it sometime, but if you know of a different way to do this that might work better, definitely open to hearing suggestions.
