### ISSUE TITLE
isort behaves nondeterministic across machines

### ISSUE THREAD

**Issue by sils1297** [timothycrosley/isort#401]
When using isort via coala in CI or GitMate I regularly see that isort does not attempt to change my files on my PC but once I'm on another PC or in the CI docker container it does. There's some nondeterminism/dependency on actually installed libs here, isn't it? Can it be avoided?

**Comment by timothycrosley** [comment]
This should for the most part be fixed. There were a few issues that could have been causing this: isort was not correctly opening files in univeral new line mode, in develop it now is. isort was having trouble detecting certain virtual env environments (this should be fixed). If you still run into this issue once 4.2.3+ is pushed let me know.

Thanks!

~Timothy

**Comment by sils1297** [comment]
Cool, when is the release expected?

**Comment by timothycrosley** [comment]
Aiming for today, sometime this week at the latest
