### ISSUE TITLE
isort on drone.io marks everything as third party

### ISSUE THREAD

**Issue by timheap** [timothycrosley/isort#414]
[Wagtail](https://github.com/torchbox/wagtail) uses isort as part of its linting checks, which are automatically run on a [drone](https://drone.io/) instance. Drone clones git repos to a directory like `/drone/src/github.com/torchbox/wagtail` as part of its initialisation, before running the scripts. This causes an issue in isort 4.2.3 and above due to 9e384025d147ccd7b975e661b42cdb4f5363a918. isort looks in the path of the resolved Wagtail package and sees `src`, and assumes it is a third party package installed by pip. This is incorrect.

Sadly, it is not possible to reconfigure drone to clone the repo to somewhere else - cloning to a subdirectory of `/drone/src/` is a hard coded part of its git plugin.

I understand that supporting pip installed source packages is an important addition to isort, but the way it is implemented has broken every instance of isort running on Drone.

Is there a more robust way of checking if a package is a source install than the current method of just checking for `"src" in path`?

**Comment by timothycrosley** [comment]
@timheap,

Yes, it will require some refactoring work, but we should be able to keep track of active virtual environment and then compare against {virtualenv_path}/src instead of just '/src/'. I'm sorry this broke your build! And thanks for reporting this issue.

~Timothy

**Comment by timheap** [comment]
Thanks for looking in to it!

For now, we will pinned isort to version 4.2.2, as we do not need support for source packages.

**Comment by timothycrosley** [comment]
Hi @timheap,

isort 4.2.5 has just been released and should fix this issue, while retaining support for src packages within virtualenvs. Let me know if you have any further issues.

Thanks!

~Timothy

**Comment by timheap** [comment]
The new release does fix the issue. Thanks for the speedy fix!

**Comment by timothycrosley** [comment]
Glad I could help :)!
