### ISSUE TITLE
Windows filenames

### ISSUE THREAD

**Issue by jayvdb** [timothycrosley/isort#419]
`isort` allows filenames to be specified in a config file, and the examples use unix path separators.

There is no translation between win32 filenames to unix filenames, so there is no way for the config to be valid for unix and win32 filenames.

**Comment by AbdealiJK** [comment]
Could you provide an example here ? I always thought python already handles such conversions internally, and unless there's some unusual path manipulation in the source of isort this wouldnt be an issue.

Also, when i checked out https://github.com/timothycrosley/isort/wiki/isort-Settings there was only one setting - the `settings-path` which would be a path. Where else would paths be used ?

**Comment by jayvdb** [comment]
Paths are `.\\a\\b.py` on Windows and `./a/b.py` on Unix .  `os.path` provides methods for joining directories in an OS-independent manner.

The config variables `skip` and `not_skip` are lists of paths.  The workaround for this bug is to list both the unix and windows paths for each file in those config variables.

**Comment by AbdealiJK** [comment]
Hm, I see.
So this can be fixed by simply changing `should_skip()`  [here](https://github.com/timothycrosley/isort/blob/751c94e3306d86d9d5dce02db86b6f914235d6ce/isort/settings.py#L209) to be something like:
```
def should_skip(filename, config, path='/'):
    """Returns True if the file should be skipped based on the passed in settings."""
    for skip_path in normalized_skip:
        if os.path.abspath(os.path.join(path, filename)) == os.path.abspath(skip_path):
            return True

# This part would not be needed anymore ?
#    position = os.path.split(filename)
#    while position[1]:
#        if position[1] in config['skip']:
#            return True
#        position = os.path.split(position[0])

    for glob in config['skip_glob']:
        if fnmatch.fnmatch(filename, glob):
            return True

    return False
```

Not sure how globs work out. But `abspath` does convert `a/b/c` -> `a\\b\\c` [reference](http://stackoverflow.com/questions/13162372/using-absolute-unix-paths-in-windows-with-python)

@timothycrosley Is this acceptable? Should I make a patch for this ?

**Comment by timothycrosley** [comment]
This is now fixed in develop and will make its way into the next release.

Thanks!

~Timothy
