### ISSUE TITLE
imports in try: except: block forced under all other imports

### ISSUE THREAD

**Issue by jayvdb** [timothycrosley/isort#421]
For something like:

```
try:
    from unittest2 import TestCase, SkipTest
except ImportError:
    from unittest import TestCase, SkipTest
```

isort does not even recognise those as imports, so it by default pushes all of the other imports above these.  `# isort:skip` does not work here.

IMO, the default behaviour should detect if all imports anywhere in the try: except: block have the same "place" according to `place_module`.  If so, it should definitely place them in the appropriate section.

Then I can configure unittest2 to be part of stdlib by using `known_stdlib_library=unittest2`.

For blocks with imports with different "place", the block should be moved to the lowest "place".

**Comment by timothycrosley** [comment]
Hi @jayvdb, I appreciate your input on this! Here is my stance on this issue: This is a very simplistic view what happens in a try except block. In reality, it tends to be that people use this block for things like imports that then effect other imports, imports that can only happen after other imports, detection of Cython etc. When you do a try except block it should never be with the other imports regardless anyhow, as it definitely breaks the flow when reading the imports, making any sections you may have had undetectable.

Thanks!

~Timothy

**Comment by jayvdb** [comment]
I agree my example was simplistic, and try import blocks can contain some very complicated mess.  My worst is [here](https://github.com/wikimedia/pywikibot-core/blob/master/pywikibot/tools/ip.py), but for complex scenarios like that the complexity should be hidden in a dedicated module which can be ignored by isort.

My interest here is only in the very simple Python 2 vs 3 backports type imports, where all branches of the conditional import provide the same functionality.

My earlier suggestions were only initial ideas on how to handle these difficult conditional blocks.  I didnt mean to say that they were the only approaches I could accept.  I'm fairly flexible on what style should be produced by isort, however ...

I can't accept these imports being forced under the local imports.  I'm pretty sure I could accept any style where they appear anywhere above the local imports.

pep8 doesnt treat imports within try: and if: differently to other imports, but it also does not mention them at all, which is an odd omission.  In cases like this, different people believe pep8 says different things, and in this case a reasonable interpretation is that pep8 is discouraging imports in try:/if:/etc , or pep8 has no opinion on them at all and its import section doesnt relate to those imports.

Personally I believe that these imports should be ordered as part of the normal flow of import provided by pep8.  I can appreciate that is overly simplistic, and probably even quite complex to implement reliably in `isort`.
So, the complexity is eliminated by requiring that they are all placed directly above the local imports.

Then the only people with strange results from `isort` will be people who are conditionally importing local imports, which is a level of crazy that isort can't help with anyway.

I think/hope that almost dove-tails with your stance on this.

Two other approaches that come to mind:

1. Require that such conditional imports are explicitly placed into dedicated sections in `sections`.

2. Only accept one import in each conditional block, in which case standard lib and standard lib backports are separated using the following pattern:

```
try:
    from collections import OrderedDict
except ImportError:
    OrderedDict = None

...

if not OrderedDict:
    from ordereddict import OrderedDict
```

If you can accept any of those options, or have another idea on how to keep local imports at the bottom, I'm happy to try to build it.

**Comment by timothycrosley** [comment]
There is a way to accomplish this in isort right now that doesn't break its design constraints and that's to explicitly label your sections for every other kind of import:

    # isort:imports-thirdparty
    import gobject
    import gtk
    from twisted.internet import gtk2reactor
    from twisted.internet.error import ReactorAlreadyInstalledError

    try:
        # Install twisted reactor, before any other modules import reactor.
        reactor = gtk2reactor.install()
    except
        # Running unit tests so trial already installed a rector
        pass

    # isort:imports-firstparty
    import deluge.common
    import deluge.component as component

Regarding my view on an automated solution: Pep8 doesn't have a stance on this in any direction. Having try / excepts in the middle of sections even simple ones makes the sections unreadable and non-distinguishable. Simply removing the advantage of  using Pep8 or any standard for imports at all IMHO. A simple solution is simply to move these modules into a separate module if you have a high concern for this particular issue, or use a module like six which has done this work for you in a central way. isort has a strong design decision to never look for imports that are nested, as doing so would cause the task done by isort to reach infinity (the level of complexity once you start looking at imports withing code flow is just too much, with really no benefit, and lots of chances to break other peoples code.) I'm potentially okay with solutions or features that do not look at nested imports. Try / Except blocks should by definition be *exceptional* and therefore treated differently, if you have enough of these that they can't be, that's indicative of further design problems, or lack of reusing existing solutions (such as six).

Thanks!

~Timothy
