### ISSUE TITLE
import statement with `\` right after `import` will get removed on sort

### ISSUE THREAD

**Issue by junzh0u** [timothycrosley/isort#425]
Let's say I have a peice of code like this:

```
#!/usr/bin/python

from os import\
		getuid

print getuid()
```

After isort, it will become:
```
#!/usr/bin/python


print getuid()
```

**Comment by timothycrosley** [comment]
@junzh0u, Thanks for reporting!

A fix has been prepared by @bootandy  and will be included in the next point release (4.2.6)

Thanks!

~Timothy
