### ISSUE TITLE
Support adding encoding header

### ISSUE THREAD

**Issue by adamchainz** [timothycrosley/isort#431]
We like to make sure our files start with:

```
# -*- encoding:utf-8 -*-
from __future__ import absolute_import, division, print_function, unicode_literals
```

`isort` lets us automatically add the `__future__` imports, it could add the encoding comment too.
#260 seemed to discuss this but then became a bug report for them not working

**Comment by graingert** [comment]
FYI you can use https://pypi.python.org/pypi/flake8-coding/1.1.1

**Comment by adamchainz** [comment]
Thanks @graingert , will try that.

**Comment by graingert** [comment]
@adamchainz it doesn't auto add, but it's a checker

**Comment by adamchainz** [comment]
I'm happy with `flake8-coding` for now, leaving this issue open though in case anyone else has the same question though

**Comment by Stibbons** [comment]
+1 for auto add coding stuff

**Comment by graingert** [comment]
I'm -1 on this because you only need to add a coding header if you're supporting python 2 or using an encoding that's not utf8

**Comment by timothycrosley** [comment]
I'm with @graingert, 

Especially now that we are in 2020 and Python2 is deprecated. If someone feels strongly enough to prepare a pull-request I may reconsider.

Thanks!

~Timothy

**Comment by graingert** [comment]
@timothycrosley  when merging modules together or resolving merge conflicts isort is great for handling imports, however I often end up with duplicate coding definitions.

I'd like isort to pick just one
