### ISSUE TITLE
Extra new-line added when comment between imports and function definition

### ISSUE THREAD

**Issue by allanlewis** [timothycrosley/isort#435]
I have a module like this:

``` py
import foo

# comment


def baz():
    pass
```

As you can see, there is one blank line between the import block and the comment, and two blank lines between the comment and the function definition, as per PEP 8.

When I run `isort` on this file (with no additional options), it adds an extra new-line between the import block and the comment: surely this is incorrect?

My actual configuration in my project is:

``` sh
isort --thirdparty <...> --force-sort-within-sections --combine-as --multi_line 4 --order-by-type --line-width 80 --atomic
```

These options produce the same result on the module above as the defaults.

This is with the latest `isort` at time of writing, v4.2.5.

**Comment by timothycrosley** [comment]
Thanks for reporting!

This is now fixed in develop and will make its way into the next release.

Thanks!

~Timothy
