### ISSUE TITLE
force-sort-within-sections causes multi-line comments to be sorted

### ISSUE THREAD

**Issue by johncooke** [timothycrosley/isort#436]
If you have a multi-line comment before an import statement and run `isort --force-sort-within-sections` then the comment gets sorted.

E.g. sample.py

``` python
import re
import os.path

# report.py exists in ... comment line 1
# this file needs to ...  comment line 2
# it must not be ...      comment line 3
import report
```

`$ isort isort --force-sort-within-sections  -d sample.py`

```
import os.path
import re

# it must not be ...      comment line 3
# report.py exists in ... comment line 1
# this file needs to ...  comment line 2
import report
```

**Comment by timothycrosley** [comment]
This has now been fixed in develop and has been prepared for the next release.

Thanks!

~Timothy
