### ISSUE TITLE
Transparent version of the logo

### ISSUE THREAD

**Issue by sils** [timothycrosley/isort#438]
Do you have a version we can use to say things about isort in presentations with transparency?

**Comment by timothycrosley** [comment]
isort now has a new logo, however, this new logo doesn't aid itself well to a transparent variant. As such marking this as wont-fix, though if someone wants to add a transparent logo, I will accept such a pull request.

Thanks!

~Timothy

**Comment by jack1142** [comment]
In case someone else ever wants an isort's small logo with transparency and finds this thread, here's my take on it:
![isort-logo-1](https://user-images.githubusercontent.com/6032823/111358449-a19d9500-868a-11eb-87f2-07497295fc7e.png)
