### ISSUE TITLE
Import line comment with parentheses and "import"

### ISSUE THREAD

**Issue by wrwrwr** [timothycrosley/isort#439]
The following:

``` python
import a  # () import
from b import b
```

is sorted as:

``` python
import a  # () import
import b
import import
```

(Trivia: The actual comment was noting that pyximport.install() is executed on module import.)

**Comment by timothycrosley** [comment]
Thanks for reporting this issue!

It is now resolved in the develop branch and will make it into the next release.

Thanks!

~Timothy
