### ISSUE TITLE
add_import is not a supported setting in the .isort.cfg

### ISSUE THREAD

**Issue by humitos** [timothycrosley/isort#442]
I can use `-a` to automatically add an import statement using the command line, but why this option (`add_import`) is not supported / read from the `cfg` file?

It doesn't appear at: https://github.com/timothycrosley/isort/wiki/isort-Settings#full-reference-of-isort-settings

How I can do to add it in the config file or what it's not supported?

**Comment by humitos** [comment]
I'm not sure if it's a mistake in the code or it's mine, but the proper settings in the config file is `add_imports` (note the ending `s`).

Another observation is that you need to separate all the imports you want by comma, but repeating the `from/import`. For example, this worked great for me:

```
add_imports=from __future__ import division, from __future__ import print_function, from __future__ import unicode_literals
```

I will leave this issue opened because maybe the proper option is `add_import` instead of `add_imports` or we can consider both, since the `-h` suggest you both of them: `-a ADD_IMPORTS, --add_import ADD_IMPORTS`

Thanks!

**Comment by graingert** [comment]
@humitos neither add_imports nor add_import works for me in setup.cfg
