### ISSUE TITLE
Applying 'use_parentheses' should depend on 'multi_line_output' and 'include_trailing_comma'

### ISSUE THREAD

**Issue by ryabtsev** [timothycrosley/isort#445]
For example:
1. multi_line_output = 0, 1 or 2; include_trailing_comma = true
   from third_party import (
   long_name_of_the_library,)
2. multi_line_output = 3 or 5; include_trailing_comma = true
   from third_party import (
   long_name_of_the_library,
   )
3. multi_line_output = 0, 1 or 2; include_trailing_comma = false
   from third_party import (
   long_name_of_the_library)
4. multi_line_output = 3 or 5; include_trailing_comma = false
   from third_party import (
   long_name_of_the_library
   )

**Comment by RomuloOliveira** [comment]
👍

**Comment by ryabtsev** [comment]
Fixed in https://github.com/timothycrosley/isort/pull/451

**Comment by timothycrosley** [comment]
Closing this a as a fix has been merged in develop, thanks!
