### ISSUE TITLE
Option to eliminate localfolder section/combine with firstparty

### ISSUE THREAD

**Issue by dan-passaro** [timothycrosley/isort#447]
By default isort will take a module with PEP8-compliant imports like this:

```
import decimal

import django

from .utils import spellcheck
from myblog.models import Post
```

And sort them into four sections like this:

```
import decimal

import django

from myblog.models import Post

from .utils import spellcheck
```

I understand the rationale behind the four sections and their ordering, but PEP8 only mentions three distinct sections for imports (see https://www.python.org/dev/peps/pep-0008/#imports). It would be nice if isort accommodated projects which want to maintain a three-section PEP8 import style. I suspect this can be done most easily by having an option where any import that would go into the "localfolder" section gets put into the "firstparty" section instead.

**Comment by timothycrosley** [comment]
This is now supported via no_lines_before config option.

Thanks!

~Timothy
