### ISSUE TITLE
isort seems to ignore my known_first_party

### ISSUE THREAD

**Issue by aliva** [timothycrosley/isort#448]
I don't know if it's a problem with my config file or something else: (VERSION 4.2.5)

here is my simplified project structure

```
- mylib
    - __init__.py
    - a.py
    - b.py
- .isort.cfg
```

here is .isort.cfg

```
[settings]
forced_separate=django
known_first_party=mylib
```

and here is a.py

```python
import uuid
from mylib import something
from rest_framework.response import Response
from django.db import models
```

when I run isort on a.py (command: `isort a.py`) here is the result

```python
import uuid

from mylib import something
from rest_framework.response import Response

from django.db import models
```

but I expect something like this:

```python
import uuid

from rest_framework.response import Response

from django.db import models

from mylib import something
```

is there problem with my config file or it's an issue with isort?

**Comment by aliva** [comment]
it seems my answer was in [readme](https://github.com/timothycrosley/isort#custom-sections-and-ordering)

**Comment by kingbuzzman** [comment]
@aliva can you be more specific

**Comment by aliva** [comment]
link is to section `Custom Sections and Ordering` and I think it's clear, in short define your sections like this:

    known_django=django
    known_pandas=pandas,numpy

and use a line like this to tell sort order:

    sections=FUTURE,STDLIB,DJANGO,THIRDPARTY,PANDAS,FIRSTPARTY,LOCALFOLDER

**Comment by kingbuzzman** [comment]
@aliva I was referring more about `FIRSTPARTY` than a different section. My issue is that my main app package is being ignored and grouped with thirdparty.

**Comment by adamrt** [comment]
@kingbuzzman I ran into this issue as well. Here is my config that gave me the results I wanted.

`# ~/.isort.cfg

[isort]
default_section = THIRDPARTY
known_django = django
known_first_party = mylib
no_lines_before = LOCALFOLDER
skip = migrations
sections = FUTURE,STDLIB,DJANGO,THIRDPARTY,FIRSTPARTY,LOCALFOLDER`

**Comment by kingbuzzman** [comment]
Yeah i figured it out, `isort` looks at your site-packages, anything found in there is "thirdparty", my site-package was inside my docker image, and i was running isort from the context of my mac, it never saw them, so that means that isort only had two references: 1. your STDLIB, and 2. FIRSTPARTY -- everything else is ignored. (side note, as soon as i ran isort inside my docker image isort worked properly.)
