### ISSUE TITLE
syslog misclassified as first party instead of stdlib

### ISSUE THREAD

**Issue by asedeno** [timothycrosley/isort#449]
After upgrading to a pylint that uses isort, I found that this import sequence:

``` python
import syslog
import uuid
```

was being noted as wrong, with the following suggestion:

``` python
import uuid

import syslog
```

This happens on linux, and not OSX; I have not tested other platforms. The major difference I see between the platforms is:

linux: (Debian Jessie, python 2.7.9; Ubuntu Trusty, python 2.7.6)

```
>>> import sys
>>> import syslog
>>> sys.modules['syslog']
<module 'syslog' (built-in)>
```

OS X: (python 2.7.12 via macports; same, modulo path, for os-bundled 2.7.10)

```
>>> import sys
>>> import syslog
>>> sys.modules['syslog']
<module 'syslog' from '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/syslog.so'>
```

On OS X, isort finds `syslog.so` and marks it as STDLIB; on linux, isort fails to find a `syslog.py` or `syslog.so` and falls back to FIRST_PARTY.

`"syslog"` should be added to the `known_standard_library` list.

Alternatively, consider using `imp.find_module` as a fallback? I get #184, though I think isort could detect some reasonable scenarios and avoid using imp where it would be wrong to do so. This might be trickier to do correctly than I think it is, of course.

**Comment by asedeno** [comment]
NB: In the mean time, I've set up an .isort.cfg for my project and added syslog to my known_standard_library list. As I did not get here by using isort myself, but by using pylint, failed detection of stdlib stuff is an unexpected surprise.

**Comment by timothycrosley** [comment]
Going ahead and closing this as syslog has been added to the known standard library list as recommended, thanks!
