### ISSUE TITLE
`async def` syntax erroneously parsed as something import-related

### ISSUE THREAD

**Issue by underyx** [timothycrosley/isort#453]
## Steps to reproduce

1. Create the following file:

```
import asyncio


async def main():
    return
```

2. Run `isort` on it.

`isort` should not modify the file at all, but it actually changes it to

```
import asyncio

async def main():
    return
```

**Comment by samuelcolvin** [comment]
I don't think it's that isort thinks `async def` is related to import, but rather that isort isn't aware that `async def` should have two blank lines before it.

This is now enforced by pycodestyle as of 2.1.0 so running isort will break flake8 etc.

Is there anything we can do to help fix this?

**Comment by samuelcolvin** [comment]
**bump** any update on this @timothycrosley?

It's fairly annoying that currently isort breaks pep8 on almost all my test files.

**Comment by timothycrosley** [comment]
Closing as a fix for this has been merged into develop
