### ISSUE TITLE
Enhancement request: Change formatting options per section

### ISSUE THREAD

**Issue by cdrice** [timothycrosley/isort#454]
I just found isort (how have I survived so long without it?!) and let me first say a resounding THANK YOU.

I would like to request/suggest formatting options be adjustable per section (vs. always global).

For example, one might set (globally):
`multi_line_output=3`
`include_trailing_comma=true`

Then for (only) section FUTURE, change:
`multi_line_output=5`

Then for (only) section LOCALFOLDER, add:
`force_grid_wrap=true`

and so on.

Effectively allowing additions/changes to formatting options tailored for each section, vs. all formatting settings being global.

If this is already possible/available, please feel free to point me in the right direction -- but from quite a bit of documentation review and experimentation, I do not believe this is currently possible.

**Comment by timothycrosley** [comment]
Since it has been many years and no others have asked for this, I'm going to close this issue. That said, I'm still open to PRs that add support for this.

Thanks!

~Timothy
