### ISSUE TITLE
isort:skip comments and __future__ imports

### ISSUE THREAD

**Issue by w0rp** [timothycrosley/isort#455]
Hello. I have an interesting case for you with a suggestion. If it's crazy, then shout me down.

If you have import lines with `# isort:skip` in them, and you add a `__future__` import line, then isort will rightly not move the `__future__` imports above the import lines you have marked to be skipped. However, `__future__` imports should always appear at the top in practice. I'm wondering if we should make a special exception for `__future__` imports, so they can be moved to the top, ignoring skipped imports.

This is only really an issue for me because I add new imports to files by appending the import line to the end of the file, and then running isort on the entire file. I suppose in my scripts I could attempt to solve this by sorting the `__future__` import myself.

**Comment by timothycrosley** [comment]
isort now provides extensives work arounds to support these use cases, such as `# isort: split`
