### ISSUE TITLE
possible not calling reload(sys)?

### ISSUE THREAD

**Issue by wisechengyi** [timothycrosley/isort#456]
Hi,

https://github.com/timothycrosley/isort/blob/4680d1d53d65a634c9e3d7ddf02d2cdcb2011823/isort/pie_slice.py#L160-L166 indicates it is calling `reload(sys)`, thus killing our pre-loaded exception handling, and therefore we have to resort to running isort as a separate process. 

so question is, is there anyway to work around it, so we can load it our program in process without any side effects. 

Thanks,
Yi

**Comment by sebix** [comment]
Very simple workaround: Don't use Python 2 but current Python 3. As far as I see, there's no such ugly workaround in the code for current python versions.

**Comment by wisechengyi** [comment]
Thanks for the suggestion, but [our ship](https://github.com/pantsbuild/pants) is a bit too big to turn at the moment. Speaking of principles, loading a module probably should not have side effects, so I was hoping that you could kindly see to a solution in python 2 as well.
