### ISSUE TITLE
Allow to give a requirements.txt as parameter to set know third party

### ISSUE THREAD

**Issue by seocam** [timothycrosley/isort#459]
When developing using docker or vagrant my libs are installed inside the VM or container and I'm developing using my editor in my machine. Because of that isort can't say when libraries are third-party or not. Since I have a bunch of deps in my requiments.txt replicate all of those to the isort config file doesn't look to me as the best idea.

I'd like to have a requirements_file parameter that would parse the file and add the libs to my 3rd-party section.

**Comment by seocam** [comment]
I've realized that the requirements.txt won't work for many cases since the package doesn't always provide contents with it's name. For example `django-haystack` provides a lib called `haystack` only.

For now I'm using the following script to run isort inside my VM:
```bash
#!/bin/bash

vagrant ssh default -c "
    cd /vagrant && \
    . ~/venv/bin/activate && \
    isort $*"
```

**Comment by orsinium** [comment]
We can made it via [mapping from pipreqs](https://github.com/bndr/pipreqs/blob/master/pipreqs/mapping) and  [parser from pip](https://github.com/pypa/pip/blob/master/src/pip/_internal/req/req_file.py), but this is additional requirements for isort. Also we can parse Pipfile.lock via [requirementslib](https://github.com/sarugaku/requirementslib/blob/master/src/requirementslib/models/lockfile.py). @timothycrosley, @seocam, what do you think?

**Comment by seocam** [comment]
@orsinium I'm not familiar with `requirementslib` but does it download the deps and cache it somehow? If not I can't imagine how this would solve the problem of which packages are provided by each dep in the requirements file.

**Comment by orsinium** [comment]
Pipreqs solve it via mapping. I use it for both formats in my pull request. This is enough for most common cases. For more packages or other solutions you can contribute to providing ipreqs. This is better than nothing.

**Comment by seocam** [comment]
It sounds like a good start :)

**Comment by jinmel** [comment]
pipreqs doesn't seem to have scikit-learn mapping for normalization. I don't think the issue is completely resolved.

**Comment by orsinium** [comment]
Please, open the issue in [pipreqs](https://github.com/bndr/pipreqs). It's the very bad idea to make our own mapping and manually actualize it with pipreqs.

**Comment by orsinium** [comment]
It will be better if you would make PR to pipreqs with this patch instead of issue. Help to OSS to grow up.

**Comment by jonafato** [comment]
:wave: Hi folks, I'm interested in helping out here. I'm committing some time to `pipreqs`, and this seems like a great opportunity to formalize a public API for `pipreqs` (https://github.com/bndr/pipreqs/issues/108) and to explore how to make it easier to use these mappings directly (https://github.com/bndr/pipreqs/issues/147). Is there anything specific I can do to make this integration easier for `isort`?

**Comment by orsinium** [comment]
@jonafato, thank you for your proposal. Pipreqs mapping integration implemented in `isort.finders.ReqsBaseFinder._load_mapping`. Mapping loading takes about 3 lines of code. It's already simple enough, I guess :)
