### ISSUE TITLE
isort gives different results when executed twice

### ISSUE THREAD

**Issue by nicoddemus** [timothycrosley/isort#460]
Hey,

First of all thanks for the excellent tool!

Consider this file:

``` python
'''
See README.md for usage.
'''
import os

#===============================
# Ask
#===============================
import io


def Ask(question, answers):
    pass
```

Executing `isort` the first time, this diff is produced:

```
$ isort foo.py
```

``` diff
diff --git a/foo.py b/foo.py
index eb0e13a..c6fd800 100644
--- a/foo.py
+++ b/foo.py
@@ -1,12 +1,11 @@
 '''
 See README.md for usage.
 '''
-import os
-
 #===============================
 # Ask
 #===============================
 import io
+import os
```

Which looks good.

However, `isort` produces a different diff when executed again:

``` diff
diff --git a/foo.py b/foo.py
index c6fd800..17f208f 100644
--- a/foo.py
+++ b/foo.py
@@ -1,10 +1,11 @@
 '''
 See README.md for usage.
 '''
-#===============================
+
 # Ask
 #===============================
 import io
+#===============================
 import os
```

Executing it more times after that no longer produces a difference.

Is this a bug? Perhaps I'm missing some config option?

**Comment by bootandy** [comment]
odd, it looks like if there are more than 2 commented out lines above an import statement they are being moved down.

**Comment by nicoddemus** [comment]
Yes, seems like it.

**Comment by bootandy** [comment]
The bug is on this line:
https://github.com/timothycrosley/isort/blob/develop/isort/isort.py#L842

I strongly suspect that changing  "greater than <something complicated>" to "greater than 0" would fix this issue 
However this line was added in this commit: f157b06c61e6b77cc2c0d38710ab974d044cec02 and I do not understand why.

**Comment by nicoddemus** [comment]
Thanks for the investigation. Perhaps @timothycrosley would like to comment?

**Comment by bootandy** [comment]
I have sent a pull request with a comment - We will let tim decide.

**Comment by nicoddemus** [comment]
Cool, thanks! :grin:

**Comment by timothycrosley** [comment]
Closing as this as had a pull request, that fixes this issue, thanks!

~Timothy
