### ISSUE TITLE
automate or update known_standard_library

### ISSUE THREAD

**Issue by AnkurDedania** [timothycrosley/isort#462]
There are a lot of standard libraries missing with newer iteration of python. Possibly look for a way to generate a list on first run and cache it to something like ~/.isort.py3.5, ~/.isort/cache.py3.5, etc...

some examples of missing packages:
- asyncio
- concurrent
- http
- html
- typing
- xmlrpc

**Comment by timothycrosley** [comment]
Closing this as all of these have now been added to the known list in develop,
Thanks!

~Timothy
