### ISSUE TITLE
Some builtins not properly placed on non-standard Python installations (conda)

### ISSUE THREAD

**Issue by nicoddemus** [timothycrosley/isort#464]
Consider this file:

``` python
import thirdparty
import os
import ftplib
import ABC
import numbers
import colorama
```

On Windows with a **conda** Python 2.7 installation, `isort` produces this:

``` python
import os

import colorama

import ABC
import ftplib
import numbers
import thirdparty
```

(Note that `ftplib` and `numbers` were incorrectly placed in the "third party" section).

It seems the problem lies in the logic which decides which files are third-party (`isort.py:265`):

``` python
                elif 'python2' in prefix.lower() or 'python3' in prefix.lower():
                    return self.sections.STDLIB
```

Standard python is installed by default in `C:\Python27` or `C:\Python34` which explains why the above works in general, but in systems which have Python from anaconda or even Python installed in a non-standard location that logic does not work and the library is considered "thirdparty".

My Python is installed at `E:\Miniconda\python.exe` , so here's the path to `ftplib`:

```
$ python -c "import ftplib;print(ftplib.__file__)"
E:\Miniconda\lib\ftplib.pyc
```

A workaround is to add those builtin files in the `known_standard_library` config options.

**Comment by nicoddemus** [comment]
cc @fogo @gqmelo @prusse-martin

**Comment by gqmelo** [comment]
This can give you the stdlib directory:

```python -c "import sysconfig; print(sysconfig.get_paths()['stdlib'])"```

**Comment by nicoddemus** [comment]
Thanks, updated the PR!
