### ISSUE TITLE
aliases can cause isort to add backslashes even with multi_line_output=5

### ISSUE THREAD

**Issue by cjerdonek** [timothycrosley/isort#466]
When `multi_line_output` is set to 5 (which should result in parentheses), `isort` can still introduce backslashes. This can be seen in the Django project, for example, which [sets it to 5](https://github.com/django/django/blob/9a2a52558e080f109a27d40a033a135c9d0e7e50/setup.cfg#L16) and yet still has [the following](https://github.com/django/django/blob/9a2a52558e080f109a27d40a033a135c9d0e7e50/django/contrib/gis/db/backends/mysql/base.py#L1):

```
from django.db.backends.mysql.base import \
    DatabaseWrapper as MySQLDatabaseWrapper
```

**Comment by jcb91** [comment]
I see this on single-item imports which are nevertheless too long for a single line, even without aliases.
I set mutliline to 5 [in setup.cfg](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/2d271dd827818bc3fed482b0a3042746e6215358/setup.cfg#L9)
but still get complaints about [this import](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/2d271dd827818bc3fed482b0a3042746e6215358/src/jupyter_contrib_nbextensions/install.py#L15-L17) as follows:

```
+++ /home/travis/build/jcb91/jupyter_contrib_nbextensions/src/jupyter_contrib_nbextensions/install.py:after	2016-12-28 13:19:50.188283
@@ -12,9 +12,8 @@
 import latex_envs
 import psutil
 from jupyter_contrib_core.notebook_compat import nbextensions
-from jupyter_nbextensions_configurator.application import (
-    EnableJupyterNbextensionsConfiguratorApp,
-)
+from jupyter_nbextensions_configurator.application import \
+    EnableJupyterNbextensionsConfiguratorApp
 from traitlets.config import Config
 from traitlets.config.manager import BaseJSONConfigManager
```

(see https://travis-ci.org/jcb91/jupyter_contrib_nbextensions/jobs/187200090#L417-L429)

**Comment by timothycrosley** [comment]
Closing as this is now resolved in develop and will make it into the next release.

Thanks!

~Timothy

**Comment by mattbennett** [comment]
For others stumbling across this issue, it took me a while to realise that this is resolved _by using the `use_parentheses`_ config option. Setting `multi_line_output=5` is not sufficient on its own.
