### ISSUE TITLE
Option to allow code intermixing

### ISSUE THREAD

**Issue by rouge8** [timothycrosley/isort#468]
Unfortunately, we have some patterns that require:

``` python
import gevent.monkey
gevent.monkey.patch_all()

import other
```

isort currently clobbers that, as it should (`test_code_intermixed`). Can there be an option to disable that?

**Comment by jparise** [comment]
@timothycrosley, I can put some time toward this, but do you have any general guidance? For example, should this be a first-class pattern, or should we just find a way for this code to "opt-out" of sorting?

**Comment by csilvers** [comment]
@jparise if you're still interested in working on this a year later :-), I'd argue to have this be the default behavior.  As @benjaminjkraft says in #693, it's really more the job of a linter to do this rather than isort.

Of course, I'm not @timothycrosley, so take that suggestion for what it's worth.

**Comment by csilvers** [comment]
(Also, the way Khan/fix-includes does things is it sorts each region independently -- so in the above example it would sort all imports before the `patch_all()` code, and then sort all the imports after it.  I don't know if that's practical in the isort world-view.)

**Comment by viniciusban** [comment]
I'm using a turnaround as long as isort can't handle it yet.

See the `if True:` block:

```
import gevent.monkey
gevent.monkey.patch_all()

if True:
    import other
```

**Comment by timothycrosley** [comment]
isort 5.0.0 to be released soon, has much better support for any custom sorting using comments:

```
import gevent.monkey

# isort: off
gevent.monkey.patch_all()
# isort: on

import other
```

or 

```
import gevent.monkey
gevent.monkey.patch_all()
# isort: split

import other
```

Should both work as soon as the new version is released.

**Comment by antoine-gallix** [comment]
Is this working on the master branch already?

**Comment by YBadiss** [comment]
Any update on this, or the release of version 5.0.0?
