### ISSUE TITLE
Empty skip?

### ISSUE THREAD

**Issue by ionelmc** [timothycrosley/isort#470]
Seems that neither `--skip=` or `skip =` (in config file) work to set an empty skip list. I keep getting `__init__.py was skipped as it's listed in 'skip' setting or matches a glob in 'skip_glob' setting`. How to disable this default?

**Comment by cas--** [comment]
From isort help:
```
-ns NOT_SKIP, --dont-skip NOT_SKIP
                        Files that sort imports should never skip over.
```
So:
```
$ isort -ns __init__.py __init__.py
$
```
or in config:
```
[settings]
not_skip = __init__.py
```

For reference only `__init__.py` is skipped in default [settings.py](https://github.com/timothycrosley/isort/blob/master/isort/settings.py#L45)

**Comment by timothycrosley** [comment]
@cas is correct, the reason it works this way, is if you have a default config file with a bunch of skips and you use --skip on the command line, you are most likely *adding* a skip, not invalidating all existing skips

**Comment by clenk** [comment]
I have the same problem and -ns does not seem to do anything. It doesn't look like not_skip is used anywhere in the code.
