### ISSUE TITLE
Imports that wrap the maximum line length and contain comments are rendered incorrectly

### ISSUE THREAD

**Issue by nicoddemus** [timothycrosley/isort#471]
Consider:

``` python
from very_long_module_name import SuperLongClassName  #@UnusedImport -- long string of comments which wrap over
```

Running `isort` on it using `-m4` and forcing the use of parentheses renders this incorrect code:

``` python
from very_long_module_name import (
    SuperLongClassName  # @UnusedImport -- long string of comments which wrap over))))
```

(Note that `isort` added the `)` after the comment, which generated an syntactically invalid file).

**Comment by timothycrosley** [comment]
Thanks for reporting this major issue! I've resolved this issue in the development branch and prepared it for the next release.

Thanks!

~Timothy

**Comment by nicoddemus** [comment]
Thanks! 🙇
