### ISSUE TITLE
force_to_top not respected by force_sort_within_sections

### ISSUE THREAD

**Issue by elibixby** [timothycrosley/isort#473]
force_to_top seems to be applied before sections are sorted when force_sort_within_sections is specified:

testisort.py

```
import foo
import z
from foo import bar
```

~/.isort.cfg

```
[settings]
force_to_top=z
force_sort_within_sections=True
```

```
$ isort testisort.py
```

testisort.py

```
import foo
from foo import bar
import z
```

These seems like extremely counter-intuitive behavior.

**Comment by timothycrosley** [comment]
Thanks for reporting! This is now fixed in develop and will make its way into the next release.

Thanks!

~Timothy
