### ISSUE TITLE
lexical order within line

### ISSUE THREAD

**Issue by wisechengyi** [timothycrosley/isort#478]
Currently the behavior has:
`from my.package import Foo, apple, banana`.

Is there a way to enforce the lexical order, so it will look like:
`from my.package import apple, banana, Foo`?

I checked the wiki but can't seem to find what I desire.

**Comment by timothycrosley** [comment]
Hi @wisechengyi,

Sorry for the delayed answer!
What you are looking for is order-by-type: False or
`isort --dont-order-by-type` from the command line.

Thanks!

~Timothy
