### ISSUE TITLE
Force multiline imports

### ISSUE THREAD

**Issue by tejasjadhav** [timothycrosley/isort#480]
Can we have an option where imports should always be multiline despite not exceeding the line length?
For example, instead of this
```python
from collections import deque, OrderedDict
```
can we have this,
```python
from collections import (
    deque,
    OrderedDict,
)
```

However, this should only be applicable for multiple imports per line. Which means, if I am importing only a **single import** from the module, then it **should not** be multiline. Only if there are two or more imports, the forced multiline behaviour should happen.

**Comment by pjenvey** [comment]
--force-grid-wrap already does what you're asking for

**Comment by tejasjadhav** [comment]
That fixes my problem. Thanks!
