### ISSUE TITLE
isort --check-only randomly fails when imports from a same file have same spelling but differ in Case

### ISSUE THREAD

**Issue by voith** [timothycrosley/isort#484]
An example of the scenario:
`from scrapy.core.downloader.handlers.http import HttpDownloadHandler, HTTPDownloadHandler`

Isort applied on a file containing such an import will keep interchanging the names 
(`HttpDownloadHandler, HTTPDownloadHandler`  OR  `HTTPDownloadHandler, HttpDownloadHandler`)

when an isort --check-only is applied on such a file it fails randomly.

**Comment by jdufresne** [comment]
Duplicate of #472?

**Comment by timothycrosley** [comment]
Thanks for reporting this issue! Closing as it has now been resolved in develop and will make its way into the next release.

Thanks!

~Timothy
