### ISSUE TITLE
Support configuration in tox.ini

### ISSUE THREAD

**Issue by OddBloke** [timothycrosley/isort#487]
A lot of Python projects use tox to drive their testing; to reduce configuration cruft, and make finding test configuration easier, it can be helpful to have all the configuration for testing tools in `tox.ini`.

This would probably just involve looking for an `[isort]` stanza in the file.

An example of a couple of other testing tools that do this: [flake8](http://flake8.pycqa.org/en/latest/user/configuration.html) and [captainhook](https://github.com/alexcouper/captainhook#setting-up).

**Comment by timothycrosley** [comment]
Closing this as your a fix for it has been merged into dev

**Comment by jleclanche** [comment]
@timothycrosley is there going to be a release? Hasn't been one in over a year.

**Comment by timothycrosley** [comment]
@jleclanche, there will also be a new release soon, I've been steadily working my way through all the current bugs: https://github.com/timothycrosley/isort/issues?q=is%3Aissue+is%3Aopen+label%3Abug, with only a few remaining. Sorry for the delay, but I hope to finish this up soon.

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
@jdufresne, just finished working through all remaining bugs and pushed a new release: `4.2.8` out to PYPI. 

Thanks!
~Timothy

**Comment by jleclanche** [comment]
Awesome! Well done :D

**Comment by cprogrammer1994** [comment]
I am using isort `VERSION 4.2.15`

This feature is broken. I am using vscode and the tox.ini is located in the project root. The pylint and flake8 configuration is working. The isort does not recognize the `line_length=120` at all.

**tox.ini**

```
[isort]
line_length=120
known_third_party=ModernGL
```

or

```
[settings]
line_length=120
known_third_party=ModernGL
```
