### ISSUE TITLE
future imports and 'isort:skip' don't work together

### ISSUE THREAD

**Issue by spookylukey** [timothycrosley/isort#488]
For example:

    from __future__ import absolute_import
    
    import foo # isort:skip
    
    import os

`isort -c` on this file incorrectly says "Imports are incorrectly sorted". If the `__future__` imports are removed, there is no error. Putting "import foo" above the future import works, but is a problem in other ways (e.g. now flake8 rightly complains).

**Comment by Hnasar** [comment]
Duplicate of #455

**Comment by timothycrosley** [comment]
Closing due to duplication
