### ISSUE TITLE
Question: separate imports from project modules with blank line

### ISSUE THREAD

**Issue by antonioj-mattos** [timothycrosley/isort#494]
I am working on a project with too many modules, and the imports can get messy sometimes. Is there a easy way to automatically separate imports from my different modules with a blank line? 

for instance, like this:

```python
from mymodule1 import x, y
from mymodule1.foo import bar

from mymodule2 import z
```
Thank you.

**UPDATE:**
Currently, I have specified all modules with the forced_separate setting. However,
the list keeps growing and I have to manually add new entries.

**Comment by timothycrosley** [comment]
I'm going to close this, has it has been a few years now and other haven't requested this feature, and like you mentioned forced_separate does technically provide this functionality (though with some hand holding). If this is still something that is important to you, feel free to open a new issue.

Thanks!

~Timothy
