### ISSUE TITLE
Ability to add newline between normal import and from import

### ISSUE THREAD

**Issue by orsenthil** [timothycrosley/isort#495]
It is often desirable to separate the two import styles with a newline.

I realize that there is no option to tune that functionality. Can this be added to isort? If yes, I am ready to submit a patch.

```
import module

from module import ClassName
```

**Comment by timothycrosley** [comment]
@jaap3 is correct,

Thanks!

~Timothy

**Comment by jaap3** [comment]
The `lines_between_types` option doesn't seem to be documented however.

**Comment by jasonkuhrt** [comment]
Things have since changed, for any future visitors:

- `lines_between_sections=0`
- on the CLI `4.3.4` the flag `-lbt` does nothing (looks like it hasn't been updated)
