### ISSUE TITLE
wildcard import with specific style gets deleted

### ISSUE THREAD

**Issue by fletom** [timothycrosley/isort#496]
`isort` deleted the following line from one of my files altogether

```
from findorserver.coupon.models import*
```

`.isort.cfg` contents:

```
[settings]
line_length = 120
multi_line_output = 5
balanced_wrapping = true
include_trailing_comma = true
skip = migrations
```

properly formatted wildcard imports were unaffected

thanks for the great tool!

**Comment by timothycrosley** [comment]
Thanks for reporting this issue! I've prepared and merged in a resolution into develop, and am therefore closing this

**Comment by fletom** [comment]
awesome, thanks for the great work
