### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by pokey** [timothycrosley/isort#497]
It would be great if there were a new release to pip so that we could use the enforce_whitespace option.

Thanks!

**Comment by teeberg** [comment]
@timothycrosley Are there issues that need to be fixed before a new release that we could help with?

**Comment by timothycrosley** [comment]
Sorry for the delays everyone! I wanted to make sure all outstanding bugs where fixed before pushing out a new release. `4.2.8` was just pushed out tonight. 

Cheers!

~Timothy
