### ISSUE TITLE
Can't determine third party packages when it's installed globally

### ISSUE THREAD

**Issue by Kern3l** [timothycrosley/isort#498]
Here's a workaround(s): https://medium.com/@zwinny/different-isort-results-from-the-same-version-15c277600957

My static analysis checks fail on dockerized isort because it's not in virtualenv and so it can't determine which packages are first or third party. On virtualenv installation it correctly puts all nonlocal in third party. On global installation (docker image, "python:3.5") it doesn't recognize third party packages and just puts them all into first party section.

**Comment by thornycrackers** [comment]
I have mine working with global installations in docker. Are you running the isort inside of the docker container or somewhere else? If it can't pick up which party the modules are in it's usually a sign that it doesn't have access to the correct pathing, I was running my isort locally one time and not inside the docker which caused the isort to put them in the wrong order.

**Comment by timothycrosley** [comment]
There has been a considerable amount of work done since this issue was raised to improve isort's discovery of import locations. I am hopeful that this issue is now fixed, if this proves incorrect please feel free to open a new issue or write a comment here.

Thank you!

~Timothy
