### ISSUE TITLE
Can't set sorting method (LC_COLLATE)

### ISSUE THREAD

**Issue by Kern3l** [timothycrosley/isort#499]
If I have locale: `LC_COLLATE="en_US.UTF-8"` then I get different results from machines with locale: `LC_COLLATE="C.UTF-8"`

**The difference is in sorting big letters.** One is putting them first, the other doesn't care about capitalization at all. This creates different behaviours on different machines. 

**Could we get a setting to force locale?** I don't want to use isort like so:

`$ LC_COLLATE="en_US.UTF-8" isort`

**Comment by timothycrosley** [comment]
Somewhere along the way this stopped being an issue, confirmed locally on linux box. 

Thanks!

~Timothy
