### ISSUE TITLE
Add `skip_path_glob` setting

### ISSUE THREAD

**Issue by ThiefMaster** [timothycrosley/isort#517]
Unless I missed something, there there is currently no way to exclude e.g. `foo/bar/*.py` or even just anything in `foo/bar`.

This would be useful e.g.  for an alembic revisions directory since adding futures like unicode_literals isn't very useful there - but there is no way of disabling either just the `add_imports` or isort alrogether just for a specific subdirectory.

**Comment by cjdp25** [comment]
I was looking for a way to skip all files inside a directory too, specially for *django migrations* that are under `migrations/` directory.

**Comment by petrikoz** [comment]
@cjdp25 For Django Migrations you can use `skip = migrations`. I try this for my project - work fine.

**Comment by timothycrosley** [comment]
The latest versions isort now have a skip_glob feature that can be used for this! Enabling things like */migrations/*.py

Thanks!

~Timothy
