### ISSUE TITLE
Depreciation warnings

### ISSUE THREAD

**Issue by samuelcolvin** [timothycrosley/isort#542]
This has become a problem since pytest upgrade to 3.10.

Example: https://travis-ci.org/samuelcolvin/arq/jobs/238303765

But this is not just on travis, I'm always (unless results are cached) getting:

```
pytest arq -p no:sugar -q
..........
======================================= warnings summary ========================================
arq/__init__.py
  /home/samuel/code/arq/env/lib/python3.6/site-packages/isort/settings.py:182: DeprecationWarning: 'U' mode is deprecated
    with open(file_path, 'rU') as config_file:
  /home/samuel/code/arq/env/lib/python3.6/site-packages/isort/settings.py:193: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
    config = configparser.SafeConfigParser()
  /home/samuel/code/arq/env/lib/python3.6/site-packages/isort/settings.py:194: DeprecationWarning: This method will be removed in future versions.  Use 'parser.read_file()' instead.
    config.readfp(config_file)

-- Docs: http://doc.pytest.org/en/latest/warnings.html
10 passed, 3 warnings in 0.03 seconds
```

**Comment by jdufresne** [comment]
The warning `DeprecationWarning: 'U' mode is deprecated` was fixed in 8559b531cdc48f7b191cd05e0a0f02c48fef5574. The config parser warnings can't be fully fixed until support for Python 2 is dropped.

**Comment by samuelcolvin** [comment]
Thanks.

Why not drop support python2? Anyone on legacy code bases can continue to use the old version. Django (master) has now dropped 2 support, surely time for everyone else to follow suit.

(only partly joking)

**Comment by timothycrosley** [comment]
@samuelcolvin, serious answer: I prefer writing Python3+ (see hug) This release was the last release to support Python2.6 (it's now dropped) thanks to @jdufresne, I've decided to support Python2.7 for one more year and then drop it as well.

Thanks!

~Timothy

**Comment by dwaynebailey** [comment]
@samuelcolvin you can suppress those warnings using `filterwarnings` in setup.cfg, see https://github.com/translate/pootle/blob/master/setup.cfg#L8-L42

**Comment by samuelcolvin** [comment]
I know, but that often silences other warnings I want to see.

**Comment by dwaynebailey** [comment]
@samuelcolvin and `ignore::DeprecationWarning:isort.settings` silences more than the warning you want to silence?

**Comment by samuelcolvin** [comment]
awsome thanks, I didn't know about the `:isort.settings` suffix

**Comment by jleclanche** [comment]
#612 should take care of this.

**Comment by samuelcolvin** [comment]
Thanks so much.
