### ISSUE TITLE
Check-only option is broken

### ISSUE THREAD

**Issue by normanjaeckel** [timothycrosley/isort#543]
If I have incorretly sorted code and use the `--check-only` option, my code changes nevertheless. The regression came in with https://github.com/timothycrosley/isort/pull/428 I think because now there is no immediately return inside the check-part.

**Comment by timothycrosley** [comment]
Thanks for reporting!

I've pushed out a hot fix release `4.2.9` to resolve this

~Timothy

**Comment by normanjaeckel** [comment]
Thanks for quick reaction. :-)
