### ISSUE TITLE
Import error for python 3

### ISSUE THREAD

**Issue by wesleykendall** [timothycrosley/isort#548]
On isort==4.2.11, I get this:

```
File "/Users/weskendall/.pyenv/versions/3.5.3/envs/pgmock/lib/python3.5/site-packages/isort/isort.py", line 43, in <module>
        from .pie_slice import OrderedDict, OrderedSet, input, itemsview
    ImportError: cannot import name 'input'
    error in setup command: Error parsing /Users/weskendall/code/pgmock/setup.cfg: ImportError: cannot import name 'input'
```

Bumping down to isort==4.2.9 fixes this. It looks like `input` is not defined in the `pie_slice.py` file for python3

**Comment by wesleykendall** [comment]
Anyway this could be patched soon? I can open up a PR if necessary. It's causing so much of our stuff to break

**Comment by timothycrosley** [comment]
Somehow the wheel file had an outdated version of pie_slice, while the source version had the correct one, I've pushed out 4.2.12, after removing all cached build files, and verified it has the correct version of the file, can you try again?

Thanks!

~Timothy
