### ISSUE TITLE
Add flake8 to the Travis run

### ISSUE THREAD

**Issue by edmorley** [timothycrosley/isort#551]
I think it would be useful to add flake8 to the Travis run, since it would have caught some of the syntax errors that resulted in the hotfix releases today.

Whilst in an ideal world there would be 100% test coverage, linters help fill in the gaps, plus spot potential unused variable/imports cleanup.

**Comment by timothycrosley** [comment]
I agree with this, and will accept a pull request that accomplishes this, if I don't get to it at a later date.

Thanks!

~Timothy

**Comment by edmorley** [comment]
I'll open a PR in the next few days that adds this. If you could sync the latest release back to the develop branch it will reduce the merge conflicts with the PR :-)

**Comment by timothycrosley** [comment]
Awesome, and thank you! Done :).
