### ISSUE TITLE
Diff no longer shown when using `isort --check-only --diff` as of v4.2.9

### ISSUE THREAD

**Issue by edmorley** [timothycrosley/isort#553]
In our CI we use `isort --check-only --diff --quiet`, so that if there are any errors the diff is shown so developers know what to fix without having to run isort again themselves locally.

This used to work as of v4.2.8, eg:
https://travis-ci.org/mozilla/treeherder/jobs/238235705#L240

However does not in v4.2.9, eg:
https://travis-ci.org/mozilla/treeherder/jobs/238401565#L240

It appears to have been regressed by the `return` added in:
https://github.com/timothycrosley/isort/commit/6bf21fc1261ef46dd5b66561e5aae8a0ce76666b#diff-7597e4974079b411e5fb6464a449abf1R184

**Comment by edmorley** [comment]
(Have edited the OP to correct the commit link)

**Comment by timothycrosley** [comment]
Thanks for reporting!

This has been fixed in a `4.2.13` hotfix release

~Timothy

**Comment by edmorley** [comment]
Many thanks! :-)
