### ISSUE TITLE
Remove generated blob from runtests.py

### ISSUE THREAD

**Issue by edmorley** [timothycrosley/isort#554]
#55 / #57 added a generated blob to runtests.py I believe to support systems that didn't have setuptools installed.

This should no longer be necessary and can be removed.

https://github.com/timothycrosley/isort/blob/b41338b33f5e5ca0ce587a81e2f8a54ddf920d8b/runtests.py#L3

**Comment by timothycrosley** [comment]
Thanks for reporting this! This issue has now been resolved in develop
