### ISSUE TITLE
Missing git tag for 4.2.14 release

### ISSUE THREAD

**Issue by felixonmars** [timothycrosley/isort#568]
It would be nice to keep PyPI releases and git tags in sync :)

**Comment by timothycrosley** [comment]
It should be there :) I do my best to keep them up to date: https://github.com/timothycrosley/isort/releases, I just finished the release process.

Thanks for keeping me honest!

~Timothy

**Comment by felixonmars** [comment]
Hmm, sorry to bother but 4.2.15 seems to be missing again :3

**Comment by timothycrosley** [comment]
Hi @felixonmars,

I see it listed here as tagged: https://github.com/timothycrosley/isort/releases

Where are you not seeing it where you expect to?

**Comment by felixonmars** [comment]
It's 2.4.15, not 4.2.15 :P

**Comment by timothycrosley** [comment]
Oh wow. Haha thanks! I'll fix ASAP

**Comment by timothycrosley** [comment]
Fixed :), clearly one more sign that tags need to be automated for this project

**Comment by felixonmars** [comment]
Something like setuptools-scm could help :P BTW, it's now 2.2.15 now, but we want 4.2.15 :3

**Comment by timothycrosley** [comment]
I'm so sorry for the mess, It's fixed now - I'll make sure to set up automation for this before the next release

**Comment by felixonmars** [comment]
Works now, thanks :P
