### ISSUE TITLE
isort claims imports are incorrectly sorted when there is a comment after the imports

### ISSUE THREAD

**Issue by orhanhenrik** [timothycrosley/isort#572]
isort will fail if there are two newlines followed by a comment after imports, it is simple to reproduce:

```
import json


# Comment
```
`isort -rc -c filename.py` will fail, while this will be valid:
```
import json

# Comment
```

pep8 is not happy with the second option (one newline), so with this comment you cannot make both isort and pep8 to be happy.

Python version: 3.6.0
isort version: 4.2.15

This bug seems to have been introduced after isort `4.2.5`, since it is not reproducible with this version.

**Comment by timothycrosley** [comment]
Hi @orhanhenrik,

Thanks for sharing your concern. pep8 is 100% fine with the first option, only demanding 1 new line between imports and code unless the code is a def or class statement (a comment is neither of these), unless I'm missing something from the pep? 

Or by `pep8` are you referring to `flake8`, in which case see: https://github.com/timothycrosley/isort/issues/550 as there is an open issue on flake8 to fix this. Note that you can also tell isort 2 use 2 lines after imports no matter what if you would like.

Thanks!

~Timothy
