### ISSUE TITLE
Make configuration discovery public?

### ISSUE THREAD

**Issue by gforcada** [timothycrosley/isort#574]
On the flake8-isort plugin, which I'm the author, we are kind of playing catch-up with isort, as isort gets more and more ways where to store the settings.

Would it be possible/desirable to have a stable public method to get that configuration? Is there already one and I just missed it?

flake8-isort only needs a basic boolean value whether a configuration somewhere exists.

**Comment by timothycrosley** [comment]
This is fixed in develop with the `--show-config` option and will make it's way into the 5.0.0 release.

Thanks!

~Timothy
