### ISSUE TITLE
isort removes comments between imports

### ISSUE THREAD

**Issue by NiklasMM** [timothycrosley/isort#576]
If the following code is processed with isort the comment is removed.

```python
import distutils
# this comment is important and should not be removed 
from sys import api_version as api_version
```

This was reported in https://github.com/coala/coala-bears/issues/1929 as we use isort through coala. 

I'm not even sure what the intended behavior is here, since sorting imports with comments could raise all kinds of problems, but removing them seems wrong too. 

Have you thought about this problem yet?

**Comment by Alok** [comment]
I've run into this too.

**Comment by kchomski-reef** [comment]
Still exists on `4.2.15`.

Before `isort`:
```python
# Before imports comment
import distutils
# Between imports comment
from sys import api_version as api_version
# After imports comment
```
After `isort`:
```python
# Before imports comment
import distutils
from sys import api_version as api_version

# After imports comment
```

**Comment by dufferzafar** [comment]
Yeah, removing those comments feels pretty weird. This is one those things that's preventing me from running isort everytime a file gets saved.

**Comment by NiklasMM** [comment]
It's not that easy to decide how this should work correctly, because all kinds of things might happen, that could make the comment meaningless or confusing with the new sorting.

Without knowing, how isort works in detail, here's a proposition of what I think is a good "best effort" type solution:

1) When collecting imports, attach comments to the following import.
2) Sort imports like before
3) After sorting, for each import, insert attached comments above that import. 

An example: 

```python

# we must import z_foo for reason X
import z_foo

import datetime
from collections import defaultdict
# here we import Counter, because it's cool
from collections import Counter
```

This would result in this output:

```python

# here we import Counter, because it's cool
from collections import Counter, defaultdict
import datetime

# we must import z_foo for reason X
import z_foo
```

I'm sure there are edge cases where this still creates confusing comments, but I think it's a good start. 

What does everyone think? If this looks like a good idea, I'm willing to invest some time and create a PR.

**Comment by Alok** [comment]
I think this is a good default assumption, and I'd like to see a PR

**Comment by dufferzafar** [comment]
@NiklasMM That is a very good first draft. I know it'll solve all my hassles!
