### ISSUE TITLE
Inconsistent sorting order for relative import

### ISSUE THREAD

**Issue by benf-wspdigital** [timothycrosley/isort#577]
The default sorting order `isort` recommends for relative imports is inconsistent.

Given a sequence of import statements:

```python
from . import lorem
from . import ipsum
from .dolor import consecteur
from .sit import apidiscing
from .. import donec
from .. import euismod
from ..mi import iaculis
from ..nec import tempor
from ... import diam
from ... import dui
from ...eu import dignissim
from ...ex import metus
```

`isort` recommends an inconsistent sort order:

```python
from . import (ipsum, lorem)
from .. import (donec, euismod)
from ... import (diam, dui)
from ...eu import dignissim
from ...ex import metus
from ..mi import iaculis
from ..nec import tempor
from .dolor import consecteur
from .sit import apidiscing
```

The sort order recommended should not reverse from “increasing number of dots” to “decreasing number of dots”. It should montonically increase or decrease.

**Comment by benf-wspdigital** [comment]
Issue #417 is related (it asks for the ability to change the sort order).

This issue is different: it is asking to correct the default sort order so it is consistent within itself.

**Comment by timothycrosley** [comment]
This is fixed and will be pushed in a release later today
