### ISSUE TITLE
Modules on separate lines, but symbols on same line

### ISSUE THREAD

**Issue by girtsf** [timothycrosley/isort#579]
I would like isort to put imports of modules on separate lines, but imports of symbols (from a module) to stay on the same line:
```
from typing import Dict, List

from . import baz
from . import foo
```

From what I can tell, there is no way to currently configure that. If so, would a configuration setting that adds this be welcome?

**Comment by timothycrosley** [comment]
I'm going to close this, mostly because isort doesn't do that level of processing (it doesn't know if it's a symbol or a module!) which makes this kind of thing impractical, though I agree it would be cool!
