### ISSUE TITLE
Bug: add_imports by .editorconfig

### ISSUE THREAD

**Issue by jedie** [timothycrosley/isort#584]
In my .editorconfig i added this:
```
add_imports = from __future__ import print_function, absolute_import, unicode_literals
```

This will be result in adding this:
```
from __future__ import print_function

import absolute_import
import unicode_literals
``` 
:)

Work-a-round is this:
```
add_imports = from __future__ import print_function, from __future__ import absolute_import, from __future__ import unicode_literals
```

**Comment by timothycrosley** [comment]
I think there is simply ambiguity here, the comma represents a separator of import statements in the config, so your work around is simply the correct way to specify within the config.

Thanks!

~Timothy
