### ISSUE TITLE
Package installed as egg isn't detected as third-party

### ISSUE THREAD

**Issue by lexdene** [timothycrosley/isort#586]
Hi.

In Python shell:

    >>> import sniper
    >>> sniper
    <module 'sniper' from '/home/xxx/envs/test-my-env/lib/python3.6/site-packages/sniper-0.0.5-py3.6.egg/sniper/__init__.py'>

In shell:

    ->  file /home/xxx/envs/test-my-env/lib/python3.6/site-packages/sniper-0.0.5-py3.6.egg
    ../envs/test-my-env/lib/python3.6/site-packages/sniper-0.0.5-py3.6.egg: Zip archive data, at least v2.0 to extract

`sniper` is installed as an egg package, and when isort see `import sniper`, it doesnot detect `sniper` as a third-party package which lead to an error when run `isort -c`.

When I install `sniper` as a module, the isort error is gone.

**Comment by timothycrosley** [comment]
This should be fixed in develop, and released later today.

Thanks!

~Timothy
