### ISSUE TITLE
TypeError when used from command line with --wrap-length

### ISSUE THREAD

**Issue by a115** [timothycrosley/isort#587]
Using isort 4.2.15 with Python 3.6.1 from the command line and specifying the 'wl' (--wrap-length) option results in TypeError in isort.py (_output_grid):

$ isort -wl 120
TypeError: '>' not supported between instances of 'int' and 'str'

**Comment by kchomski-reef** [comment]
Can't reproduce this on `isort 4.2.15` and `Python 3.6.3`.

**Comment by moriyoshi** [comment]
Just wanted to let you know that this has been fixed only recently at https://github.com/timothycrosley/isort/commit/8924fe26bdf3cc6c1bb118c331ba9ac96ab2f3d1
