### ISSUE TITLE
Empty lines between “import …” and ”from …”

### ISSUE THREAD

**Issue by hynek** [timothycrosley/isort#589]
Hi,

is there any chance for an option that inserts an empty line between the “import …” and “from …” blocks?

I.e.

``` python
import os

from datetime import datetime

import attr

from attr import Factory
```

?

I find seeing them glued together almost physically painful. ;)

FWIW, I’ve asked around if there a way to achieve that before opening this issue and got a barrage of various hacks that people employed to get this done including writing own plugins and overwriting manually so there seems to be a lot of demand for this so I’m surprised I haven’t found an older issue for it (or I don't know how to use the search function…) – am I missing something?

**Comment by paltman** [comment]
This would be fantastic to have.

**Comment by kchomski-reef** [comment]
@hynek @paltman 
It's already there :smiley: You have to use `--lines-between-types` (`-lbt`) option followed by number of lines to insert.

`gh589.py`
```python
from attr import Factory
from datetime import datetime
import attr
import os
```
After running `isort gh589.py -lbt 1`:
```python
import os

from datetime import datetime

import attr

from attr import Factory
```

**Comment by hynek** [comment]
Huh!  I was aware of that option but for some reason it only changed the lines between blocks for me?  Maybe I had a typo in my config…thanks!

**Comment by beaugunderson** [comment]
this is missing from the [wiki](https://github.com/timothycrosley/isort/wiki/isort-Settings) but i'm glad the setting exists! :)
