### ISSUE TITLE
Add ability to provide a custom sorting key

### ISSUE THREAD

**Issue by wimglenn** [timothycrosley/isort#592]
Feature request. 

Canned example:

```
# third_party_module.py
kB = 1000
KiB = 1024
MiB = 1048576
```

I want this: 

```
# my_module.py
from third_party_module import kB
from third_party_module import KiB
from third_party_module import MiB
```

`isort` insists this

```
# my_module.py
from third_party_module import KiB
from third_party_module import MiB
from third_party_module import kB
```

presumably it's trying to group CONSTANTS, Classes, functions by naming conventions.  

Can you provide a way for user to customize the sort key?  This feature would provide a generic solution to get e.g. case-insensitivity, [natural sorting](https://pypi.python.org/pypi/natsort), or whatever other exotic custom use-cases.

**Comment by ibigpapa** [comment]
I would like to see this as well.

**Comment by nickwilliams-eventbrite** [comment]
Yeah, as an organization, we sort our imports differently (always case-insensitive sorting regardless of import type), so it's a pain that there's no setting to control case sensitivity or anything similar at all).

**Comment by timothycrosley** [comment]
I don't think this is required anymore as naturual sorting is now always used, and there are plenty of options to enable getting the intended sort (--fass, --dont-order-by-type, etc)
