### ISSUE TITLE
isort does not recognize six.moves and email modules properly.

### ISSUE THREAD

**Issue by fabioz** [timothycrosley/isort#596]
Given something as:

```
import email  # standard library
import os  # standard library
from os import path  # standard library

from six.moves import zip  # third party

import my_project  # project
from my_project import basic  # project
```

isort wrongly sorts to:

```
import os  # standard library
from os import path  # standard library

import my_project # project
import email  # standard library
from my_project import basic  # project
from six.moves import zip  # third party
```

**Comment by kchomski-reef** [comment]
This seems to be resolved in https://github.com/ESSS/esss_fix_format/pull/17, which already got merged to master.
@timothycrosley Could this issue be closed?

**Comment by fabioz** [comment]
@kchomski-reef that issue was solved in a totally different tool (which uses isort), so, the issue in isort persists (not that users can't manually change it to fix it as was done in the `esss_fix_format` tool, but the issue is still present on isort).

**Comment by kchomski-reef** [comment]
Ahh, my fault, I haven't looked close enough at the referenced PR, thanks for pointing this out :+1: 

I've checked your example against current master (`4.2.14`) and it seems that at least for `email` it got fixed, but `six.moves` still ends up at the bottom:

`gh.py`
```python
import email  # standard library
import os  # standard library
from os import path  # standard library

from six.moves import zip  # third party

import my_project  # project
from my_project import basic  # project
```
After running `isort gh.py`:

```python
import email  # standard library
import os  # standard library
from os import path  # standard library

import my_project  # project
from my_project import basic  # project
from six.moves import zip  # third party
```

**Comment by exhuma** [comment]
I have the same with a line in sqlalchemy and also with a private "third-party" module. Strangely, I don't get the problem with sqlalchemy all the time. This line in this case is:

    from sqlalchemy import create_engine

**Comment by exhuma** [comment]
The problem in my case was twofold:

* `__init__.py` files are skipped by default.
* `sqlalchemy` was not properly detected as third-party due to the usage of a virtualenv

Both could be fixed by adding two lines to my `.isort.cfg`:

    [settings]
    not_skip = __init__.py
    virtual_env = env

**Comment by rakeshcusat** [comment]
I fixed by introducing this line in `isort` section.

```
[isort]
known_third_party = six, six.moves
```

**Comment by timothycrosley** [comment]
This should be fixed in develop, with a planned release today.

Thanks!

~Timothy
