### ISSUE TITLE
there could be an error message making clear that imports are missing

### ISSUE THREAD

**Issue by kthhrv** [timothycrosley/isort#646]
when displaying a diff of missing imports the only error message printed is
"ERROR: {0} Imports are incorrectly sorted."

it would be nice if 
"ERROR: {0} Missing imports."
was printed in this case

**Comment by timothycrosley** [comment]
This is beyond isorts scope as isort doesn't create or intend to create an AST for an entire project or source file. As such it has no good way of knowing if an import is missing.
