### ISSUE TITLE
When you install isort==4.3.0 version still shows 4.2.14

### ISSUE THREAD

**Issue by fyber** [timothycrosley/isort#650]
After installing wheel for version `4.3.0`, `isort --version-number` still shows `4.2.14`.
I just examined wheel contents and it indeed contains old version number, the same as in repo: https://github.com/timothycrosley/isort/blob/master/isort/__init__.py#L28
My Python is 3.6.2.

**Comment by Plazmaz** [comment]
Should be fixed after merging #655

**Comment by Anthchirp** [comment]
Version 4.3.0 on pypi still shows 4.2.14.

**Comment by timothycrosley** [comment]
This should now be fixed in release 4.3.1, Thank you!
