### ISSUE TITLE
ISort produces different result running from command line vs from Vim's ISort function.

### ISSUE THREAD

**Issue by vincentwhales** [timothycrosley/isort#661]
This is the original list of imports: 

     from flask import Markup, Response, flash, redirect, request
     from flask_admin._compat import iteritems, text_type
     from flask_babelex import gettext, lazy_gettext
     from flask_admin.base import expose
     from flask_admin.helpers import get_redirect_target
     from flask_admin.model import typefmt
     from flask_admin.model.helpers import get_mdict_item_or_list
     from sqlalchemy import and_
     from sqlalchemy.inspection import inspect
     
     from portal.account.models import AttributeManagerSingleton as AMS
     from portal.account.utils import History, ReplacementBank
     from portal.admin.utils import (AccessControlView, AuthorizationRequiredView,
                                     TimeTrackedModelView)
     from portal.models import db
     from portal.user import RolesEnum
     from portal.user.models import User, UsersRoles, Role
     from portal.utils.EnumRelated import EnumSQLAModelView
     from portal.vps.widgets import ReleasableWidget
     

After running isort on the directory (`isort`), I get: 

    from flask import Markup, Response, flash, redirect, request
    from flask_admin._compat import iteritems, text_type
    from flask_admin.base import expose
    from flask_admin.helpers import get_redirect_target
    from flask_admin.model import typefmt
    from flask_admin.model.helpers import get_mdict_item_or_list
    from flask_babelex import gettext, lazy_gettext
    from portal.account.models import AttributeManagerSingleton as AMS
    from portal.account.utils import History, ReplacementBank
    from portal.admin.utils import (AccessControlView, AuthorizationRequiredView,
                                    TimeTrackedModelView)
    from portal.models import db
    from portal.user import RolesEnum
    from portal.user.models import Role, User, UsersRoles
    from portal.utils.EnumRelated import EnumSQLAModelView
    from portal.vps.widgets import ReleasableWidget
    from sqlalchemy import and_
    from sqlalchemy.inspection import inspect

I installed isort on vim and execute the following upon save: `:autocmd BufWritePost *.py Isort`

When I open this file and press save, I see isort sorted my imports yet again: 

    from flask import Markup, Response, flash, redirect, request
    from flask_admin._compat import iteritems, text_type
    from flask_admin.base import expose
    from flask_admin.helpers import get_redirect_target
    from flask_admin.model import typefmt
    from flask_admin.model.helpers import get_mdict_item_or_list
    from flask_babelex import gettext, lazy_gettext
    from sqlalchemy import and_
    from sqlalchemy.inspection import inspect
    
    from portal.account.models import AttributeManagerSingleton as AMS
    from portal.account.utils import History, ReplacementBank
    from portal.admin.utils import (AccessControlView, AuthorizationRequiredView,
                                    TimeTrackedModelView)
    from portal.models import db
    from portal.user import RolesEnum
    from portal.user.models import Role, User, UsersRoles
    from portal.utils.EnumRelated import EnumSQLAModelView
    from portal.vps.widgets import ReleasableWidget

Is this happening to anybody? I am very annoyed because Isort doesn't seem to be producing a deterministic output each time. 

I installed 'fisadev/vim-isort' via Plug. No other configuration is supplied to vim-isort.

**Comment by timothycrosley** [comment]
There has been a lot of work in the last several releases of isort to improve import categorization - I hope this work has solved this issue. If it has not please open a new issue or comment on this one to let me know.

Thanks!

~Timothy
