### ISSUE TITLE
Isort 4.3 turns all tab indent into 1-space indent

### ISSUE THREAD

**Issue by jleclanche** [timothycrosley/isort#665]
Reproduction steps:

1. `git clone https://github.com/HearthSim/twitch-hdt-ebs`
2. `pip install isort==4.3.2`
3. `isort -y`
4. `git diff`

This is a regression in 4.3.

**Comment by timothycrosley** [comment]
This has been fixed with tests introduced to ensure it doesn't occur again in the 4.3.3 hotfix release. Thanks for reporting and I apologize for any inconvenience this caused!

**Comment by jleclanche** [comment]
Thanks for the quick fix and the great tool @timothycrosley  :)
