### ISSUE TITLE
Strange sort order with 'from' imports and capitals

### ISSUE THREAD

**Issue by ukch** [timothycrosley/isort#669]
Given the following example:

```python
from aaa import Ab
from aaa import BC
from aaa import Bc
```
I would expect the above to be the correct order, but isort complains that the first two imports are incorrectly sorted. Running `isort -df` on the file yields the following:

```diff
+from aaa import BC
 from aaa import Ab
-from aaa import BC
 from aaa import Bc
```

I can't see any logical reason why isort would sort these lines in this way, so I guess this is a bug.

**Comment by timothycrosley** [comment]
isort by default imports orders by type: CONSTANT, ClassDefinition, function_or_variable. Since isort doesn't have any information about the actual types in question, it uses casing convention to determine the type. You can turn this feature on/off using the `order_by_type`.
