### ISSUE TITLE
sort order changed recently when mixing "from ... import" statements where only some have an "as" clause

### ISSUE THREAD

**Issue by teeberg** [timothycrosley/isort#675]
We're running `isort` as a pre-commit hook, so all files have had their imports sorted at some point.

Now I just ran `isort` on our repo and found a bunch of changes like these:
![image](https://user-images.githubusercontent.com/199071/36170874-933313d0-10b5-11e8-9310-202204adeb51.png)

so it seems like it used to group all imports without an "as" clause together, but now sorts them alphabetically, even if that means splitting them up.

I personally preferred the previous style, but I guess it doesn't really matter. I'd be happy to commit as is if isort prefers that now :)

Was that an intentional change? If yes, is it configurable?

**Comment by timothycrosley** [comment]
This was intentional to keep the imports sorted alphabetically while keeping the ability to have single line as imports. Closing and marking as wont-fix, but if anyone has enough passion about this issue to submit a pull-request I will reconsider.

Thanks!

~Timothy
