### ISSUE TITLE
ujson treated as a firstparty/localfolder

### ISSUE THREAD

**Issue by haizaar** [timothycrosley/isort#678]
ujson is a thridparty library that implements JSON encoder/decoder, however isort treats it as a firstparty or localfolder:

```
$ cat main.py 

import os

import requests
import ujson

import foo
$ touch foo.py
$ isort --diff main.py 
--- /tmp/bar/main.py:before	2018-02-20 15:52:06.323003
+++ /tmp/bar/main.py:after	2018-02-20 15:52:09.555307
@@ -2,6 +2,6 @@
 import os
 
 import requests
-import ujson
 
 import foo
+import ujson
```
In my reproduction it want to put it after `foo` which is a local module and detach from `requests` which is a third-party module (where I want to put ujson as well).

System info:
```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
$ python --version
Python 3.6.4
$ pip freeze
certifi==2018.1.18
chardet==3.0.4
idna==2.6
isort==4.3.4
requests==2.18.4
ujson==1.35
urllib3==1.22
```

Thanks!

**Comment by apb7** [comment]
Hey, @haizaar! One possible solution is to specify `ujson` under `known_third_party` in your setup.cfg or tox.ini file.  
Thanks!

**Comment by haizaar** [comment]
Excellent! It did the trick. Is it still considered a bug though?

**Comment by apb7** [comment]
No, I don't think so since it is not possible for isort to detect each and every third party library. Although you can define a `default_section` for this purpose.  
Thanks!

**Comment by haizaar** [comment]
Thanks for another trick. I still wonder - isort does a great job with sorting stuff out. So far `ujson` is the only library that fell through. `usjon` was installed through pip like all other libraries, so I wonder why is it special...

**Comment by apb7** [comment]
You can go through the documentation. There are other options too which can be tweaked. Personally, I find isort very helpful. It's a great tool. Thanks to @timothycrosley!

**Comment by jamesmallen** [comment]
FWIW, `ciso8601` is another third-party library that isort seems to think is local. Like ujson, it is a C library - I wonder if that is the common thread?

**Comment by timothycrosley** [comment]
There's been a lot of work on improving the categorization of imports (especially C based ones) in the latest isort release. I believe this issue should now be fixed, please comment here if it turns out I am wrong.

Thanks, everyone!

~Timothy
