### ISSUE TITLE
Rename abbreviation of --REMOVE-IMPORTS from -r to -ri, -rm or another name

### ISSUE THREAD

**Issue by drunkwcodes** [timothycrosley/isort#689]
For example, here is a project with some modules:

```
 a.py
 b.py
 test.py
 __init__.py
```

Here is the test.py:

```
from . import a
from . import b
```

Running `isort -r .` ends with missing those lines and causing ImportError.
Though there is a comfirmation before deletion.

People used to treat `-r` as `--recursive` instead of `--remove`.
Maybe it's safer and more friendly to users.

**Comment by timothycrosley** [comment]
Agreed! Updating to be `-rm` in today's release. Will keep `-rc` for recursive for now, but at some point in the future - maybe next major release we can revisit that.

Thanks!

~Timothy
