### ISSUE TITLE
Don't skip __init__.py by default

### ISSUE THREAD

**Issue by edmorley** [timothycrosley/isort#690]
Hi!

isort's `skip` list includes `__init__.py` by default, which we hadn't realised until now (after two years of using isort). I think it makes sense for isort to not do this, and let people explicitly set which files they want to skip - to reduce confusion and increase coverage (I would imagine most people would want all files consistently sorted).

See also #183.

Thoughts? :-)

**Comment by Lukas0907** [comment]
For reference, this can be also achieved with a config setting in ``.isort.cfg``:

```cfg
not_skip=__init__.py
```

**Comment by hugovk** [comment]
This can be closed now https://github.com/timothycrosley/isort/pull/702 has been merged.

Please could we have a new release to include it?

Thank you!

**Comment by jaswilli** [comment]
Yes, it would be great if this change to the default behavior could be released. I have a project using a `pyproject.toml` file and for some reason `not_skip` isn't picked up out of `pyproject.toml`. Working around it by adding it to `.editorconfig` for now.

**Comment by timothycrosley** [comment]
In newer versions of isort __init__.py is no longer skipped by default.

Thanks, everyone!

~Timothy
