### ISSUE TITLE
isort should not move imports past other code

### ISSUE THREAD

**Issue by benjaminjkraft** [timothycrosley/isort#693]
Currently, if you have a file like:
```
import sys

sys.path.insert(...)

import foo
import bar
```
then isort will move the two later imports up to go above the `sys.path` line.  But you probably put it after the `sys.path` line because you need that path modification to find `foo`!

What I would expect isort to do here is to treat two import blocks that have a non-import statement in between as completely separate: that is, it should sort the block with `import sys` (trivial), and separately sort the block with `import foo` and `import bar` (swap the two), but not mix those two blocks together.

(This behavior could, of course, be optional, although I'd argue it's the right behavior for most cases; it's not the job of isort to decide whether having that code in the middle of your imports was a good idea.  A linter is better suited to do that; and it would allow you to `# noqa` the offending line if you really do want it.)

**Comment by benjaminjkraft** [comment]
Oops, I missed #468; this is a duplicate of it.

**Comment by antoine-gallix** [comment]
While waiting for the release of the features that'll allow it, here is my workaround. I put the patching and path altering commands their own module, so they are triggered by an import statement in the original file. Then using isort configuration, one can control the position of this import, for example making it it's own section and controlling the order of it.

Before:
```
# file: main.py
import sys
sys.path.append('.vendor')
import my_vendorized_module
```

After:
```
# file: main.py
import setuppath
import my_vendorized_module

# file: setuppath.py
import sys
sys.path.append('.vendor')
```

Configure isort with:
```
# file: setup.cfg
[isort]
force_to_top=setuppath
```
