### ISSUE TITLE
README incorrectly claims that isort sorts alphabetically

### ISSUE THREAD

**Issue by OddBloke** [timothycrosley/isort#698]
It, in fact, sorts by the type being imported (inferred from the naming) and then alphabetically within each of those types.

This isn't a problem per-se, but did just lead to some confusion when trying to work out why I was getting particularly output; I had to examine the isort code to work out what the expected behaviour was.

**Comment by timothycrosley** [comment]
Thanks for sharing your confusion!
I've updated the documentation in an attempt to be more concise about it's default behaviour.

Thanks!

~Timothy

**Comment by OddBloke** [comment]
Thanks, looks good!

**Comment by leos** [comment]
I just ran into this as well - it would be great for the docs to give an example or two to clarify this since it's really subtle.
