### ISSUE TITLE
Only sort imports that are already at the top?

### ISSUE THREAD

**Issue by alok** [timothycrosley/isort#706]
I'm working on a project where some imports are in the middle and they run code, so the order from them matters, but the imports at the top can be freely ordered. Is there a way to only order imports that are already at the top?

**Comment by fyber** [comment]
You can use the special comment in order for isort to skip the import:

    from foo import bar  # isort:skip

**Comment by benjaminjkraft** [comment]
See also #468 which as I understand would solve this.

**Comment by timothycrosley** [comment]
This is fixed I believe, in spirit by #468 as mentioned by @benjaminjkraft which is in develop and will make its way in the 5.0.0 release. It  does sort beyond the top, but allows freely splitting where sorting happens, or using isort: off to stop splitting after the top.

Thanks!

~Timothy
