### ISSUE TITLE
isort doesn't seem to respect dunders

### ISSUE THREAD

**Issue by AlecRosenbaum** [timothycrosley/isort#711]
This is not breaking, but does definitely prevent me from adding this to any automated process.

Basically, isort doesn't seem to respect the positioning of dunders. Take the following code for example:
```python
from __future__ import absolute_imports

__all__ = [
    "SomeClass",
]

import os
import sys

class SomeClass(object):
    ...
```

[According to PEP8](https://www.python.org/dev/peps/pep-0008/#module-level-dunder-names), dunders should come immediately after `__future__` imports, which it does in this case. After running isort, dunders will be moved to after the import block.

```python
from __future__ import absolute_imports

import os
import sys


__all__ = [
    "SomeClass",
]


class SomeClass(object):
    ...
```

**Comment by viniciusban** [comment]
I'm using  a turnaround as long as isort can't handle it yet:

```
from __future__ import absolute_imports

__all__ = [
    "SomeClass",
]

if True:
    import os
    import sys

class SomeClass(object):
    ...
```

**Comment by timothycrosley** [comment]
This is fixed in develop and will make it's way in the 5.0.0 release.

Thanks!

~Timothy

**Comment by graingert** [comment]
@timothycrosley do you have a release schedule for v5?

**Comment by jarekkar** [comment]
+1

**Comment by graingert** [comment]
@timothycrosley I tried using isort v5 but it doesn't seem to correctly place `__all__` (between `__future__` imports and other imports) is there an option I need to set?

**Comment by timothycrosley** [comment]
@graingert sorry for not being clear about what was implemented here! It's not that isort will now find the correct position for the dunders, just that it will now respect their initial placement. So, if a user places them correctly, isort will not move them.
