### ISSUE TITLE
respect the XDG_CONFIG_HOME environment variable

### ISSUE THREAD

**Issue by NorthIsUp** [timothycrosley/isort#713]
An increasing number of projects are starting to respect the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) and it would be awesome if isort did that too!

Basically, this means to check for the environment variable XDG_CONFIG_HOME. If it exists, make your configuration file relative to that (`${XDG_CONFIG_HOME}/isort/`). If it does not exist, make your configuration file relative to `~/.config/isort/`

**Comment by dsifford** [comment]
@timothycrosley I was looking into maybe contributing this fix and after looking at the following lines...

https://github.com/timothycrosley/isort/blob/fcd80d46e66179f9464c2df745ffed07622d9ee3/isort/settings.py#L145-L151

It appears that configurations are found in the global configuration (i.e `~/.isort.cfg`), they'll overwrite the identical settings set in the project-level configurations. Is this the intended effect?

Also, the settings file is a bit complex, no? What are your thoughts on maybe giving it a spring cleaning? Freedesktop provides a spec-compliant helper library to find config files using the XDG specification (https://freedesktop.org/wiki/Software/pyxdg/) which might make life a bit easier on this front.

Thanks for clarifying.

**Comment by timothycrosley** [comment]
This has been implemented and will make it's way into today's release. Thank you!

~Timothy
