### ISSUE TITLE
improve skip_glob to eagerly ignore directories

### ISSUE THREAD

**Issue by gaborbernat** [timothycrosley/isort#714]
At the moment one can use skip_glob to ignore folders. However, the ignore is evaluated lazily (meaning we look at each file and decide if it needs it or not). For folders that have a lot of file in it (e.g. ``.git``, or ``.tox`` folders) this becomes really slow. Ideally, if a directory matches the glob expression we should not look into that folder anymore entirely.

**Comment by gaborbernat** [comment]
@timothycrosley ping :smiley:

**Comment by motin** [comment]
One can use `skip` to ignore those folders eagerly. Is your issue about using a glob pattern like `**/.git` for ignoring all `.git` folders found anywhere in the source tree?
Would you mind comparing the difference in runtime for some public github repository, comparing `skip_glob` and hard-coded equivalent `skip` configuration? For instance, if the `skip_glob` pattern is `**/.git` and the repository has 20 submodules - what is the difference in runtime between:

```
skip_glob = **/.git
```

and

```
skip = path/to/submodule1/.git
skip = path/to/submodule2/.git
skip = path/to/submodule3/.git
etc...
```
?

**Comment by gaborbernat** [comment]
The benchmarking does not make sense here per se, because you would mostly benchmark the disk speed. E.g. the numbers would be very different when talking about a network file system versus a super fast SSD. Generally the least disk operations we can do the better overall user experience we can expect.

**Comment by motin** [comment]
This issue is about lazy evaluation being "really slow". Just wondering what it means. 10s? 20s? Minutes? Could that runtime be shrunk to 1s? 30s? etc in projects of a certain composition?
Also, is this issue reported based on a situation where isort runs too slow, or is the issue a general placeholder in the style of "lazy loading here is wrong so it should be fixed for good measure"?

**Comment by gaborbernat** [comment]
Assume using this inside a project with tox. tox will create virtual environments in the current folder (we're talking here about tens of folders with thousands of files). The time can be seconds on a slow network file system just to discover and remove these virtual environment files from passing onto isort. Even a second is a lot when it can be avoided.

**Comment by motin** [comment]
Since tox creates all virtual environments within `.tox` (`.tox/py27`, `.tox/py36` etc), all you need is ´skip=.tox´ to ignore all of those files.

**Comment by timothycrosley** [comment]
This should be implemented in the latest version of isort.
Thanks!

~Timothy
