### ISSUE TITLE
Problem with spaces when using Pylint pragmas

### ISSUE THREAD

**Issue by apb7** [timothycrosley/isort#718]
## Observed behavior:
When using pylint pragmas such as `# pylint: disable=relative-import` in the same line as the imports, Isort wants two spaces before the pragma and produces the error message, `Imports are incorrectly sorted` for the following lines:

```python
import a # pylint: disable=relative-import
from b import c # pylint: disable=relative-import
from x import y # pylint: disable=relative-import
``` 
The error log and diff:
```bash
ERROR: /home/dev/test.py Imports are incorrectly sorted.
--- /home/dev/test.py:before	2018-07-10 18:30:00.551178
+++ /home/dev/test.py:after	2018-07-10 18:30:04.896646
@@ -1,3 +1,3 @@
-import a # pylint: disable=relative-import
-from b import c # pylint: disable=relative-import
-from x import y # pylint: disable=relative-import
+import a  # pylint: disable=relative-import
+from b import c  # pylint: disable=relative-import
+from x import y  # pylint: disable=relative-import
```

## Expected behavior:
~Isort should not consider the whitespaces post the import statement (`ignore_whitespace` can be set to `true` here but still whitespaces after the import statement should not be taken into account) if possible.~
The error message for this case, where the diffs differ in whitespaces, should be different from `Imports are incorrectly sorted` since the imports are actually in the correct order.

## Versions:
Python: 2.7.12
Isort: 4.2.15 (Also, tested this on 4.3.4 and observed the same behavior)

Thanks!

**Comment by timothycrosley** [comment]
2 spaces before comments on the same line are consistent with the pep8 recommendation and enforced by many linters. As far as I understand it pylint will be perfectly happy with 2 spaces as well. I'm going to close thi, unless at some point it becomes clear this issue effects more users.

Thanks!

~Timothy
