### ISSUE TITLE
Make "first party" take priority when import matches both first party and another section?

### ISSUE THREAD

**Issue by aldanor** [timothycrosley/isort#721]
Example - the local package is `foo_bar`, but there are more similarly named packages, `foo_a`, `foo_b` and `foo_c` that we'd like to separate into a group:

```ini
sections=FOO,FIRSTPARTY
known_firstparty=foo_bar
known_foo=foo_*
```

and the desired result is

```python
from foo_a import a
from foo_b import b
from foo_c import c

from foo_bar import x
```

However they all get mashed into one "foo" group because foo_bar matches its wildcard:

```python
from foo_a import a
from foo_b import b
from foo_bar import x
from foo_c import c
```

Is there a way to tell it for the first party to "take priority" somehow?

**Comment by aldanor** [comment]
Just a though, maybe something like this could hypothetically work?

```ini
sections=FOO,FIRSTPARTY
known_firstparty=foo_bar
known_foo=foo_*
ignore_foo=foo_bar
```

**Comment by sztamas** [comment]
I think this is just a typo in the configuration!

`known_firstparty` should be `known_first_party` (note: the extra **`_`** between `first` and `party`).

Fixing it in the config or passing in `-p foo_bar` will give the desired output ie.:

```python
from foo_a import a
from foo_b import b
from foo_c import c

from foo_bar import x
```

I think this issue should be closed.

**Comment by timothycrosley** [comment]
@sztamas Thanks for investigating this! I agree with your assessment!
