### ISSUE TITLE
Feature request: Give support to '-' to read from standard input

### ISSUE THREAD

**Issue by brupelo** [timothycrosley/isort#728]
Here's a little example showing how to achieve this simple but at the same time useful time when it comes to integrate these type of tools with text editor plugins:

 - Make sure this option doesn't conflict with existing one: [https://github.com/hhatto/autopep8/blob/master/autopep8.py#L3446-L3457](https://github.com/hhatto/autopep8/blob/master/autopep8.py#L3446-L3457)
 - Read from standard input: [https://github.com/hhatto/autopep8/blob/master/autopep8.py#L3955-L3963](https://github.com/hhatto/autopep8/blob/master/autopep8.py#L3955-L3963)

**Comment by brupelo** [comment]
It seems this feature has been living in the repo since 2014, ie: [https://github.com/timothycrosley/isort/commit/e3f76656646b6286c9a832e249ad1e9851cbe235](https://github.com/timothycrosley/isort/commit/e3f76656646b6286c9a832e249ad1e9851cbe235), I had opened this issue mainly because it wasn't listed with --help

**Comment by timothycrosley** [comment]
Thanks for this insight! In the latest release, the isort --help documentation describes this behavior.

Thanks!

~Timothy
