### ISSUE TITLE
The -k/--keep-direct-and-as flag does not work

### ISSUE THREAD

**Issue by user37596** [timothycrosley/isort#735]
-k, --keep-direct-and-as
                        Turns off default behavior that removes direct imports
                        when as imports exist.
But when I have file `test.py`:

    from django.utils.translation import ugettext as _, ugettext

and run `isort -k test.py` or `isort --keep-direct-and-as test.py`, the result is:

    from django.utils.translation import ugettext as _

isort version is 4.3.4.

**Comment by timothycrosley** [comment]
This is fixed in develop and will make it's way out in the 5.0.0 release.

Thanks!

~Timothy
