### ISSUE TITLE
isort does not support unix paths in config when run on Windows

### ISSUE THREAD

**Issue by jayvdb** [timothycrosley/isort#737]
The following config does not work on Windows 
```ini
[isort]
skip=tests/test_config.py,tests/test_integration.py
```

I raised this previously as https://github.com/timothycrosley/isort/issues/419 , and it doesnt appear to work for 4.2.8, or 4.3, or in latest.

**Comment by timothycrosley** [comment]
This is fixed in the release to be distributed to PYPI today,

Thanks!

~Timothy
