### ISSUE TITLE
isort doesn't recognize cpython compiled libraries properly

### ISSUE THREAD

**Issue by matejcik** [timothycrosley/isort#740]
the check at https://github.com/timothycrosley/isort/blob/develop/isort/isort.py#L316 tests for `<name>.py` or `<name>.so`.

But in Python 3, compiled modules are named something like `<name>.cpython-36m-x86_64-linux-gnu.so`. Also IIRC Windows use ".pyd" extension, so I assume this never worked there?

The correct suffix can be read from `sysconfig.get_config_var("EXT_SUFFIX")`.

as a complete aside: i assume there is a good reason, but why won't isort simply import the name and use the `__file__` property?

**Comment by timothycrosley** [comment]
Hi @matejcik isort does now use "EXT_SUFFIX" :), you can see isort/finders.py.

> as a complete aside: i assume there is a good reason, but why won't isort simply import the name and use the `__file__` property?

The reason for this is that isort made the design choice, a long time ago, to work as a globally installed utility (via Python2 or 3) that could be run against code bases across a machine independent of what version of Python they were written for and without needing to be in the virtual env.
