### ISSUE TITLE
multiple test failures (replay of #583?)

### ISSUE THREAD

**Issue by Kelledin** [timothycrosley/isort#742]
def test_long_line_comments():
        """Ensure isort correctly handles comments at the end of extremely long lines"""
        test_input = ("from foo.utils.fabric_stuff.live import check_clean_live, deploy_live, sync_live_envdir, "
                      "update_live_app, update_live_cron  # noqa\n"
                      "from foo.utils.fabric_stuff.stage import check_clean_stage, deploy_stage, sync_stage_envdir, "
                      "update_stage_app, update_stage_cron  # noqa\n")
>       assert SortImports(file_contents=test_input).output == \
                    ("from foo.utils.fabric_stuff.live import (check_clean_live, deploy_live,  # noqa\n"
                     "                                         sync_live_envdir, update_live_app, update_live_cron)\n"
                     "from foo.utils.fabric_stuff.stage import (check_clean_stage, deploy_stage,  # noqa\n"
                     "                                          sync_stage_envdir, update_stage_app, update_stage_cron)\n")
E       AssertionError: assert 'from foo.uti...stage_cron)\n' == 'from foo.util...stage_cron)\n'
E         Skipping 145 identical leading characters in diff, use -v to show
E         + _live_app, update_live_cron)
E         - _live_app,
E         -                                          update_live_cron)
E         - from foo.utils.fabric_stuff.stage import (check_clean_stage,  # noqa
E         + from foo.utils.fabric_stuff.stage import (check_clean_stage, deploy_stage,  # noqa
E         ?                                                              ++++++++++++++...
E         
E         ...Full output truncated (5 lines hidden), use '-vv' to show

test_isort.py:1349: AssertionError

---

    def test_import_case_produces_inconsistent_results_issue_472():
        """Test to ensure sorting imports with same name but different case produces the same result across platforms"""
        test_input = ('from sqlalchemy.dialects.postgresql import ARRAY\n'
                      'from sqlalchemy.dialects.postgresql import array\n')
        assert SortImports(file_contents=test_input, force_single_line=True).output == test_input
    
        test_input = 'from scrapy.core.downloader.handlers.http import HttpDownloadHandler, HTTPDownloadHandler\n'
>       assert SortImports(file_contents=test_input).output == test_input
E       AssertionError: assert 'from scrapy....oadHandler)\n' == 'from scrapy.c...loadHandler\n'
E         Skipping 39 identical leading characters in diff, use -v to show
E         + tp import HttpDownloadHandler, HTTPDownloadHandler
E         - tp import (HttpDownloadHandler,
E         -                                                   HTTPDownloadHandler)

test_isort.py:2139: AssertionError

    def test_no_extra_lines_issue_557():
        """Test to ensure no extra lines are prepended"""
        test_input = ('import os\n'
                      '\n'
                      'from scrapy.core.downloader.handlers.http import HttpDownloadHandler, HTTPDownloadHandler\n')
        expected_output = ('import os\n'
                           'from scrapy.core.downloader.handlers.http import HttpDownloadHandler, HTTPDownloadHandler\n')
>       assert SortImports(file_contents=test_input, force_alphabetical_sort=True,
                           force_sort_within_sections=True).output == expected_output
E       AssertionError: assert 'import os\nf...oadHandler)\n' == 'import os\nfr...loadHandler\n'
E         Skipping 49 identical leading characters in diff, use -v to show
E         + tp import HttpDownloadHandler, HTTPDownloadHandler
E         - tp import (HttpDownloadHandler,
E         -                                                   HTTPDownloadHandler)

test_isort.py:2205: AssertionError

---

Again, this happens with Python 2.7.15 and 3.6.6, using the 4.3.4 release from PyPI--but the offending tests pass with the GitHub tarball release, so I don't consider this a big deal.

I haven't tracked down the specific difference that triggers these failures, but it would be nice to have a PyPI release that passed all tests...

**Comment by timothycrosley** [comment]
@Kelledin I think we've tracked this down to the isort tests relying on a config at the root of the project, that isn't explicitly included in the test suite - and updated it to use a fixture that explicitly defines any necessary configuration options. If you still encounter this after the next release let me know and I'll reopen.

Thank you!

~Timothy
