### ISSUE TITLE
PyPI's configparser confuses _get_config_data()

### ISSUE THREAD

**Issue by therc** [timothycrosley/isort#743]
Some people use https://pypi.org/project/configparser/. Don't ask (I didn't).

Currently, `settings.py` handles this new twist well for the import (it tries `configparser` before `ConfigParser`). Inside `_get_config_data()`, though, it looks at the Python interpreter's version. This will break on 2.7 with configparser, because now you have a third-party module with the 3.5 API. And that means that you'll get

```
    config = configparser.SafeConfigParser()
AttributeError: 'module' object has no attribute 'SafeConfigParser'
```
which makes sense, because the 3.5 API only has `ConfigParser()`. 

Perhaps `_get_config_data()` should look at the methods on configparser. Or perhaps the import order should be changed at the top.

**Comment by timothycrosley** [comment]
Closing as this issue is resolved in the soon to be released 5.0.0 version, by virtue of being Python3.6+ only.

Thanks!

~Timothy
