### ISSUE TITLE
farmhash is not sorted as a third party

### ISSUE THREAD

**Issue by pcorpet** [timothycrosley/isort#744]
The [Farmhash library](https://pypi.org/project/pyfarmhash/) get installed as `/usr/local/lib/python3.6/site-packages/farmhash.cpython-36m-x86_64-linux-gnu.so` on my machine. But `isort` won't see that it's a third party.

I think this is due to this code:
https://github.com/timothycrosley/isort/blob/fcd80d46e66179f9464c2df745ffed07622d9ee3/isort/isort.py#L315
which would only find
 - `/usr/local/lib/python3.6/site-packages/farmhash.so`
 - `/usr/local/lib/python3.6/site-packages/farmhash.py`
 - `/usr/local/lib/python3.6/site-packages/farmhash`

I'm not sure how the import solver finds it, but I think that `isort` could be as smart.

**Comment by timothycrosley** [comment]
There's been a lot of work on improving the categorization of imports (especially C based ones) in the latest isort release. I believe this issue should now be fixed, please comment here if it turns out I am wrong.

Thanks, everyone!

~Timothy
