### ISSUE TITLE
How to use known_django as an argument?

### ISSUE THREAD

**Issue by lifez** [timothycrosley/isort#745]
I want to use something like this
```
known_django=django
sections=FUTURE,STDLIB,DJANGO,THIRDPARTY,LOCALFOLDER
```
from `.isort.cfg` in args format to setup isort in vscode

Try many options not working.

Thank.

**Comment by DylanYoung** [comment]
VS Code will use the config relative to your Workspace root as well as your user config `~/.isort`. 

I would also like to see these options exposed on the command line, but you don't need it for this.
