### ISSUE TITLE
dataclasses missing from list of standard libraries

### ISSUE THREAD

**Issue by cancan101** [timothycrosley/isort#746]
See: https://docs.python.org/3/library/dataclasses.html

**Comment by samuelcolvin** [comment]
could be added [here](https://github.com/timothycrosley/isort/blob/develop/isort/settings.py#L58)

Except `known_standard_library` doesn't seem to be python version dependent.

**Comment by cancan101** [comment]
looks like this was fixed already: https://github.com/timothycrosley/isort/commit/4db80bb28ea7f678c20b7d24d6f0574b549a0a1a#diff-57121582b6fc41e2d3a0776d1ddc59d9
