### ISSUE TITLE
Isort should never suggest fixes that exceeds the specified line length

### ISSUE THREAD

**Issue by motin** [timothycrosley/isort#755]
In all of the cases below, isort suggests a fix that succeeds the maximum line length:

**Test case 1**
Source (exceeds default line length):
```
from third_party.platform.utilities.foo_utils import foo_abcdefghijklmnopqrstuvxyz
from third_party.platform.utilities.foo_utils import bar_abcdefghijklmnopqrstuvxyz
```

Output (exceeds default line length):
```
from third_party.platform.utilities.foo_utils import (bar_abcdefghijklmnopqrstuvxyz,
                                                      foo_abcdefghijklmnopqrstuvxyz)
```

**Test case 2**
Source (dos **NOT** exceed default line length):
```
from third_party.platform.utilities.foo_utils import (
    foo_abcdefghijklmnopqrstuvxyz,
    bar_abcdefghijklmnopqrstuvxyz
)
```

Output (exceeds default line length):
```
from third_party.platform.utilities.foo_utils import (bar_abcdefghijklmnopqrstuvxyz,
                                                      foo_abcdefghijklmnopqrstuvxyz)
```

**Test case 3**
Source (exceeds default line length):
```
from third_party.platform.utilities.foo_utils.even.deeper.nested.library import foo_abcdefghijklmnopqrstuvxyz
```

Output (exceeds default line length):
```
from third_party.platform.utilities.foo_utils.even.deeper.nested.library import \
    foo_abcdefghijklmnopqrstuvxyz
```

In case isort suggests a fix that exceeds the specified line length, and there is no other fallback method / fix that isort can pull out of the hat: fail with an exception instead of continuing, or else subsequent code style tests fails due to the long lines.

**Comment by timothycrosley** [comment]
I think I disagree with the premise of this issue. isort is trying first and foremost to support the formatting output you specify, then it tries to fit that format unto the desired line length. there are some cases where a specified format with the provided imports produces output greater than the line-length. And, generally for people that desire a certain format they are aware that very occasional outcome, but have still chosen that format. If isort did what you are alluding to here, it would be correct according to line length but would be incorrect according to the specified format - and another issue could be created that said "isort should never suggest fixes that don't conform to import format". What is the value of that? And even if we did go down that path, if your import is long enough you might not be able to wrap in anyway without breaking the execution of the code!
