### ISSUE TITLE
isort can trash Python installations

### ISSUE THREAD

**Issue by akx** [timothycrosley/isort#759]
Heya :)

This is a bit of a corner case, but it's happened to me more than once already...
So `isort` is prooobably not meant to be used on Python stdlib code, since it can be a little tricky with imports in places.

However, if you happen to have a virtualenv within your working directory, or a `.tox` directory containing those, `isort -rc .` may recurse down into them, like in the logs below.

This will be a problem in any environment where the python stdlib files are writable, as they are on MacOS when you've installed Python with Homebrew; running within a virtualenv doesn't matter, since these files are usually linked into it, not copied.

```
$ isort -rc .
Fixing ./.tox/flake8/bin/python-config
Fixing ./.tox/flake8/bin/activate_this.py
[...]
Fixing ./.tox/flake8/lib/python3.7/os.py
[...]
Fixing ./.tox/flake8/lib/python3.7/site.py
[...]
```

At this point, I hit ctrl+c, because this wasn't what I wanted, removed the `.tox` directory and tried to re-run `isort`:

```
$ rm -r .tox
$ isort -rc .
Fatal Python error: initsite: Failed to import the site module
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site.py", line 73, in <module>
    import os
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 30, in <module>
    from os.path import (altsep, curdir, defpath, devnull, extsep, pardir, pathsep,
ModuleNotFoundError: No module named 'os.path'; 'os' is not a package
$
```
Oh no! Remembering I'd seen this before, I tried to run a non-virtualenv `python3`:
```
~ $ python3
Fatal Python error: initsite: Failed to import the site module
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site.py", line 73, in <module>
    import os
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 30, in <module>
    from os.path import (altsep, curdir, defpath, devnull, extsep, pardir, pathsep,
ModuleNotFoundError: No module named 'os.path'; 'os' is not a package
```
It's dead, Jim 😞 

This is fixed by reinstalling Python (`brew reinstall python3` for me) to replace the isort-tainted stdlib modules with fresh ones.

I think it'd be worth it to add special-casing in `isort` to ignore (by default; could be overridden with some sort of footgun switch) files in:

* `*/.tox/`
* `*/lib/python*.*`
* any `site-packages` directory
* any `dist-packages` directory (Debian special)

Maybe some others?

**Comment by meatballs** [comment]
Yep. I've just had exactly this situation trash my anaconda installation on my mac.

**Comment by jdufresne** [comment]
A good starting point would be to copy the defaults from Black:

https://github.com/ambv/black/blob/024c9cab55da7bd3236fd88759c9735d6149b464/black.py#L53-L55

Are you up for contributing this feature as a PR?

**Comment by meatballs** [comment]
> Are you up for contributing this feature as a PR?

Sure - if I can find a chunk of time!
