### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by caulagi** [timothycrosley/isort#760]
Is it possible to release a new version please? I want to start using the recent changes for supporting pyproject.yaml.

**Comment by srstevenson** [comment]
I presume this is blocked on https://github.com/timothycrosley/isort/issues/763 at the moment.

**Comment by hit9** [comment]
Status？

**Comment by rr-** [comment]
Before you release the new version, you might want to know that this feature isn't working well:

```console
rr-@tornado:~/src/maintained/bubblesub$ cat pyproject.toml
[tool.black]
line-length = 79
py36 = true

[tool.isort]
known_third_party = mpv
multi_line_output = 3
include_trailing_comma = true
rr-@tornado:~/src/maintained/bubblesub$ isort -rc -y **/*.py
```

Running `isort` recognizes `mpv` as third party module. This is good.

```console
rr-@tornado:~/src/maintained/bubblesub$ black .
Usage: black [OPTIONS] [SRC]...

Error: Error reading configuration file: invalid literal for int() with base 10: 'mpv'
```

Whoops! Looks like this isn't a valid TOML file. Let's fix this.

```console
rr-@tornado:~/src/maintained/bubblesub$ sed -i 's/mpv/"mpv"/' pyproject.toml
rr-@tornado:~/src/maintained/bubblesub$ black .
All done! ✨ 🍰 ✨
113 files left unchanged.
```

So far so good…

```console
rr-@tornado:~/src/maintained/bubblesub$ isort -rc -y **/*.py
Fixing /home/rr-/src/maintained/bubblesub/bubblesub/api/media/media.py
Fixing /home/rr-/src/maintained/bubblesub/bubblesub/api/media/video.py
```

…but now `isort` incorrectly looks for `import "mpv"` statements.

```console
rr-@tornado:~/src/maintained/bubblesub$ cat pyproject.toml
[tool.black]
line-length = 79
py36 = true

[tool.isort]
known_third_party = "mpv"
multi_line_output = 3
include_trailing_comma = true
rr-@tornado:~/src/maintained/bubblesub$
```

**Comment by ofek** [comment]
@jdufresne Thanks for https://github.com/timothycrosley/isort/pull/798! Can we please get a new release now?

**Comment by jdufresne** [comment]
@ofek While I can help out by reviewing and merging PRs, I do not have permission on PyPI to submit new releases. That will require @timothycrosley

**Comment by ofek** [comment]
@jdufresne Ah I see. Btw, does the config loader traverse up through the directory tree just like `black`?

**Comment by jasongi-actu** [comment]
@timothycrosley have you had a chance to look at this yet? Currently installing isort via the git repo to access the latest config options but it isn't ideal. Most of the documentation is also newer than the latest released version on pypi.

**Comment by ofek** [comment]
@timothycrosley Any progress on this?

**Comment by Gr1N** [comment]
Hi, any progress on this?

**Comment by timothycrosley** [comment]
Hi Everyone!

Good news:

https://github.com/timothycrosley/isort/releases/tag/4.3.5

4.3.5 is now officially out and includes many of the improvements and fixes you have been waiting for :crossed_fingers: without any major regressions. Officially this is the last Python2 release, however, if there does happen to be a large number of regressions I'm open to doing some hotfixes under 4.3.x, but am fully unwilling to port backwards any new features.

I'm deeply sorry for the unreasonably long delay to wrap up all these awesome improvements made by users and contributors to isort. I want everyone to know that I'll be working diligently to open deploy access to more contributors to avoid this from occurring in the future.

Thank you!

~Timothy

**Comment by ofek** [comment]
@timothycrosley We all appreciate this very much, thank you!

**Comment by das7pad** [comment]
I suggest a major version bump for the drop of python2 support.

**Comment by timothycrosley** [comment]
@das7pad Good call! I'll update the changelog to list it as the 5.0.0 release. I want to combine the next release with strict profile support - so that we can do things like ensure full-strict coverage with projects that use black with an `isort black` profile.

**Comment by timothycrosley** [comment]
A quick update on this: auto PYPI deploy has been set up against the master branch, which enables others to also do deploys starting with @jdufresne who has done a tremendous amount of work and a great job acting as a co-maintainer - even without all the tools to fully perform that role (the ability to make releases!).  I'd like to open it up to more core contributors in the future, and this is the first step to enable that to happen. If this is something that interests you, please let me know.

Due to at least in part, the large time lapse since the last release, it took *many* hotfix releases before isort felt stable based on incoming issues. However, I feel it is now stable enough to start planning completely the first 3.x only release. I'm going to let this work week pass by, and if no major new issues are reported I'll aim to deploy the Python3 release shortly after.

Thanks again, everyone!

~Timothy
