### ISSUE TITLE
isort creates a syntaxically incorrect "import import" statement

### ISSUE THREAD

**Issue by imankulov** [timothycrosley/isort#762]
There is a file with somewhat specific formatting, which makes isort generate syntactically invalid output.

`$ cat test.py`
```python
from os.path \
    import (join, split)
```

`$ isort -d test.py`
```python
from os.path import import, join, split
```

Naturally, I would expect to have

```python
from os.path import join, split
```

- isort version: `VERSION 4.3.4`
- python version. Reproduced with Python 2.7 and Python 3.7 on Linux and MacOS.

**Comment by imankulov** [comment]
Will let myself to add a yet another example to the same issue.

```python
from os.\
        path import (join, split)
```

turned into

```python
from os. import import, join, path, split
```

For the record, examples are not artificially crafted. It's a result of post-processing of some old code with some automatic formatters.

**Comment by timothycrosley** [comment]
Thanks for reporting this! This is a pretty major issue! I've implemented a new test case and applied the necessary fix for it to pass - with an intended release later today.

Thanks!

~Timothy

**Comment by imankulov** [comment]
Thanks a lot, Timothy! 🙌
