### ISSUE TITLE
Doc is out of date for `multi_line_output`

### ISSUE THREAD

**Issue by pierreglaser** [timothycrosley/isort#769]
It seems like the doc does not match the behavior of the `multi_line_output` option. 
Especially, to have long import lines not splitted, `multi_line_output` should be 7 and not 6 as said [here](https://github.com/timothycrosley/isort#multi-line-output-modes).
By the way, the command line argument parser seems also out of date in this regard. 
Should I submit a PR?
Thanks!

**Comment by imankulov** [comment]
Can confirm that the doc is out of date

```python
>>> from isort import settings
>>> settings.WrapModes
WrapModes(GRID=0, VERTICAL=1, HANGING_INDENT=2, VERTICAL_HANGING_INDENT=3, VERTICAL_GRID=4, VERTICAL_GRID_GROUPED=5, VERTICAL_GRID_GROUPED_NO_COMMA=6, NOQA=7)
```

I wonder if it would be more convenient in API, settings and CLI args to use mnemonic names, and keep integers for backward compatible. The `multi_line_output=VERTICAL_HANGING_INDENT` looks
more readable (and besides, better survives updates of the tool) than `multi_line_output=3`.

Before moving forward with a PR would probably be wise to have a confirmation from @timothycrosley that this change would make sense indeed.
