### ISSUE TITLE
Recursive import breaks isort

### ISSUE THREAD

**Issue by llpamies** [timothycrosley/isort#772]
$ cat a.py
import a
print("A")

Then,
$ cat a.py | isort -d
import a

print("A")

And isort hangs here....

**Comment by timothycrosley** [comment]
Hi @llpamies,

I'm unable to reproduce this, however I will say `-d` does not tell isort to read from stdin:

`cat a.py | isort -`

should provide the behavior you want. isort doesn't open other files based on what's imported or similar, so no recursive errors should be able to happen.

Thanks!

~Timothy
