### ISSUE TITLE
isort behavior depends on available libraries 

### ISSUE THREAD

**Issue by ppwwyyxx** [timothycrosley/isort#789]
It appears that `isort` uses available libraries to determine whether a library is third-party or not. When `bob` is not installed, it produces:
```python
import numpy

import bob
```

When `bob` is installed, it produces:
```python
import bob
import numpy
```

This non-determinism is very undesired. A python project may have some optional dependencies that's only required by some of its files. Different developers of such project may not have the same dependencies installed and therefore get different outputs by `isort`. This makes it impossible to use `isort` as a mandatory linter or pre-commit hooks.

**Comment by ericbiewener** [comment]
Would the [`known_third_party`](https://github.com/timothycrosley/isort/wiki/isort-Settings) option solve this?

**Comment by ppwwyyxx** [comment]
Thanks! This option solves the issue. So I'll need to add __all optional dependencies__ to `known_third_party`.
