### ISSUE TITLE
when parsing editorconfig with multiple entries of the same name, isort seems to throw exceptions & crash

### ISSUE THREAD

**Issue by davethegr8** [timothycrosley/isort#791]
I opened this issue the other day, which seems to be an issue in isort: https://github.com/PyCQA/pylint/issues/2661

The problem is that when an editorconfig file contains multiple declarations for the same block, isort throws an exception.

**Comment by timothycrosley** [comment]
Can't reproduce currently against develop branch. Please recheck after today's release and if the issue is still present I will reopen.

Thanks!

~Timothy
