### ISSUE TITLE
isort chokes on fifo

### ISSUE THREAD

**Issue by jnewbigin** [timothycrosley/isort#792]
If there is a fifo in the directory tree, isort stops responding.

Steps to reproduce (on linux):
```
isort
# verify that the run completes
mkfifo myfifo
isort
# observe that the run never completes
```

Presumably it opens the fifo and attempts to read, thus waiting for input which is never coming.
I recommend that isort ignores fifo by default.

**Comment by timothycrosley** [comment]
This has been fixed in develop and will be released today.

Thanks!

~Timothy
