### ISSUE TITLE
Automatic deployment to pypi

### ISSUE THREAD

**Issue by jasongi-actu** [timothycrosley/isort#803]
I think it would be a good idea to build into Travis-CI deploying to pypi. This would prevent issues like #760 from occurring.

The guide looks fairly simple and would require @timothycrosley to encrypt the pypi credentials in the config file.
https://docs.travis-ci.com/user/deployment/pypi/

**Comment by hugovk** [comment]
Here's an example (https://github.com/pylast/pylast/pull/295):

https://github.com/pylast/pylast/blob/a5c53dbf5402535ca79c66cebe1ca1e1a3dc7baa/.travis.yml#L47-L70

It has two deploys:
* tagged commits deploy to the main pypi.org
* untagged commits deploy to test.pypi.org

For both, it only does it for builds to the pylast/pylast main repo (no forks), on the master branch (no feature branches), and for a single build job (`py37`, no duplicates).

**Comment by timothycrosley** [comment]
Thanks for the assistance! Using these pages as guides, isort now has auto deploy setup.

Thanks!

~Timothy
