### ISSUE TITLE
Isort breaks on multiple imports with `import as`

### ISSUE THREAD

**Issue by thisfred** [timothycrosley/isort#804]
Isort breaks  code of the form:

```python
from foo import bar as renamed_bar

from foo import bar

renamed_bar()
bar()
 ```

Running Isort 4.3.4 without any configuration settings, turns this into:

```python
from foo import bar as renamed_bar

renamed_bar()
bar()
```

which is syntactically invalid.

The original code is admittedly weird, but it's valid Python, and occurs in the wild in things like alembic migrations.

**Comment by dset0x** [comment]
Duplicate of #606 ?
