### ISSUE TITLE
isort won't run if directories are given in the command line

### ISSUE THREAD

**Issue by r-darwish** [timothycrosley/isort#805]
When isort isn't given any files it will isort the entire project root. This is not always desirable, especially when it does not ignore files ignored by git.

I'd like to be able to run isort on several sub-direcoties, but specifying the in the command line results in:

`WARNING: Unable to parse file flask_app/ due to [Errno 21] Is a directory: '/home/roeyd/src/sherlock/flask_app'`

**Comment by akx** [comment]
Would `isort -rc flask_app other_directory third_directory` work for you?

**Comment by r-darwish** [comment]
Sure

**Comment by kingbuzzman** [comment]
@r-darwish can this be closed?

**Comment by r-darwish** [comment]
Sure

**Comment by kingbuzzman** [comment]
@r-darwish You have to close it dude.
