### ISSUE TITLE
Test suite depends on .editorconfig

### ISSUE THREAD

**Issue by jayvdb** [timothycrosley/isort#814]
If the top level project .editorconfig is removed, the test suite fails.

Either the tests should use a dedicated .editorconfig that is part of the test suite (preferred), or the top level .editorconfig should be included in the source tarball along with the tests.

That latter is not ideal IMO as it is a hidden file, so is a bit confusing that it has any impact on the test suite.

**Comment by timothycrosley** [comment]
Agreed! I've updated the project to include its editorconfig config settings via a py.test fixture defined at the top of the test suite.

Thank you!

~Timothy

**Comment by jayvdb** [comment]
Looking forward to a new release soon.

btw, there are two other tiny hacks being done in openSUSE packaging to comply with its rpmlint rules, which you may want to patch before the next release.  At least the LICENSE one is applicable, but you might want to keep the shebang in the `main.py`, but not it is only useful inside a package under Python 2, and even then is a bit dangerous wrt imports.

```
sed -i '1s/^#!.*//' isort/main.py
chmod -x LICENSE
```

**Comment by timothycrosley** [comment]
Just did the release: https://github.com/timothycrosley/isort/releases/tag/4.3.5.
I'm going to open up a new issue with the items you bring up here to make sure they make their way into the next release - thank you for this insight!

~Timothy
