### ISSUE TITLE
ISort fails to group some specific case.

### ISSUE THREAD

**Issue by MrSyee** [timothycrosley/isort#815]
ISort success ordering package, but I check a worse case.
I run an automated check of python code using pylint, and ISort failed to satisfy pylint.

My .isort.cfg setting is below.
```
[settings]
multi_line_output=3
include_trailing_comma=True
force_grid_wrap=0
combine_as_imports=True
line_length=88
```

for example, in my worse case isort make result below.
```
import cv2
import gym
import numpy
import pygame
from gym import spaces
```
I want a result.
```
import cv2
import gym
from gym import spaces
import numpy
import pygame
```
or 
```
import cv2
import numpy
import pygame
import gym
from gym import spaces
```

But a good case is this example.
```
import gym
import torch
import torch.optim as optim
```

I wonder how sort they are.

**Comment by timothycrosley** [comment]
Hi @MrSyee,

By default isort forces `from` imports to land below direct (non-from) imports, but it does support the behaviour you want as well :).

Simply add
`force_sort_within_sections=True`

to your config file to get the behaviour you want.

Cheers!

~Timothy

**Comment by MrSyee** [comment]
Thanks. It is solved.
