### ISSUE TITLE
How to enable both force_single_line and multi_line_output?

### ISSUE THREAD

**Issue by dcecile** [timothycrosley/isort#816]
In [test_isort.py](https://github.com/timothycrosley/isort/blob/master/test_isort.py#L806), I see this example where the `force_single_line` and `multi_line_output` are used together:

```py
def test_force_single_line_long_imports():
    test_input = ("from veryveryveryveryveryvery import small, big\n")
    test_output = SortImports(file_contents=test_input, multi_line_output=WrapModes.NOQA,
                              line_length=40, force_single_line=True).output
    assert test_output == ("from veryveryveryveryveryvery import big\n"
                           "from veryveryveryveryveryvery import small  # NOQA\n")
```

But I can't figure out why my changing `multi_line_output` in .isort.cfg has no effect:
```
[settings]
multi_line_output=6
force_single_line=True
line_length=40
```

The result is always mode 2 (hanging indent):
```py
from veryveryveryveryveryvery import big
from veryveryveryveryveryvery import \
    small
```

Is there something I'm missing?

(I'm trying to achieve mode 3, vertical hanging indent, together with trailing comma, to match [Black's mutli-line output](https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACpAFVdAD2IimZxl1N_WlkPinBFoc6EdwDCbsQ1e_QK-USLANiG46aMJmiHTU-maoHYWIONmkufZQbJaYizlzQiHCrnw2NaBDcUBS6ryYjygwHHoKDBEXEtwAAAAAAAf12ntG3zQMEAAXGqAQAAAOvqAIGxxGf7AgAAAAAEWVo=).)

**Comment by dcecile** [comment]
After turning on **`use_parentheses`**, now `multi_line_output` has an effect under `force_single_line`.

---

With this approach, I was able to solve my formatting problem, single-line isort now matches Black style.

`.isort.config`:

```
[settings]
multi_line_output=3
force_single_line=True
line_length=40
use_parentheses=True
include_trailing_comma=True
```

Result:
```py
from veryveryveryveryveryvery import big
from veryveryveryveryveryvery import (
    small,
)
```

**Comment by zzztimbo** [comment]
thank you @dcecile i wasted many many hours trying to figure this one out.
