### ISSUE TITLE
Sort imported items alphabetically inside if-statement

### ISSUE THREAD

**Issue by mkurnikov** [timothycrosley/isort#818]
It required for the type annotation imports, like
```
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from typing import List, Any
```

**Comment by WouldYouKindly** [comment]
Yup, would be awesome to have.

**Comment by pradyunsg** [comment]
Hehe. I swear I thought I'd filed this.

**Comment by krzysztofwolski** [comment]
> Yup, would be awesome to have.
> 
> ...and check if the import is used only for annotations and automatically put it into `if TYPE_CHECKING` section!

Damn, that would be **huge**. Managing imports in python take wayyy to much time.

**Comment by timothycrosley** [comment]
This is fixed in develop and will make it's way into the 5.0.0 release.

Thanks!

~Timothy

**Comment by pradyunsg** [comment]
Yay! Thank you so much for this!

**Comment by ObserverOfTime** [comment]
Is there a way to disable this behaviour and make isort only check top level imports?
I'd rather not have blank lines between imports within `if TYPE_CHECKING` or methods.
