### ISSUE TITLE
Wrong indentation with .editorconfig

### ISSUE THREAD

**Issue by samuelmeuli** [timothycrosley/isort#830]
isort seems to have problems parsing an `.editorconfig` file with overrides.

If the file looks like the following:

```
root = true

[*]
charset = utf-8
end_of_line = lf
indent_size = 2
indent_style = tab
insert_final_newline = true
trim_trailing_whitespace = true

[*.{py,rst}]
indent_size = 4
indent_style = space
```

isort will indent my multiline imports (`multi_line_output = 3`) with 2 tabs instead of 4 spaces. It seems to be using the wildcard configuration instead of the Python configuration which should override it.

**Comment by powens** [comment]
After diving into this issue, it looks settings.py doesn't support any editorconfig sections other than `[*]`, `[*.py]`, and `[**.py]`. Any sort of other globbing/pattern matching isn't supported currently. To work around this, you could define a separate section for both `[*.py]` and `[*.rst]` for now.

**Comment by timothycrosley** [comment]
This is fixed in develop and will make its way out in the 5.0.0 release.

Thanks!

~Timothy
