### ISSUE TITLE
Update contributors list

### ISSUE THREAD

**Issue by timothycrosley** [timothycrosley/isort#837]
Update https://github.com/timothycrosley/isort/blob/develop/ACKNOWLEDGEMENTS.md to list any missing contributors since it was last updated

**Comment by Tenzer** [comment]
`curl -s https://api.github.com/repos/timothycrosley/isort/stats/contributors | jq -r '.[].author.login'` get you quite far - if you just want the GitHub user names. If you also want people's real names (if they have them specified on GitHub) you'll have to look up each user and see what their real name is set to.

**Comment by timothycrosley** [comment]
This is now resolved. Thanks @sztamas!
