### ISSUE TITLE
Not able to install isort>=4.2.5

### ISSUE THREAD

**Issue by nitinsomanitcs** [timothycrosley/isort#847]
I am trying to install isort version>=4.2.5, but I am getting exception errors, this is having a drastic impact as all our pipelines are failing since we are not able to install pylint==1.8.4, isort version>=4.2.5 being a dependent package. we are receiving the following error:
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/d5/nrkhtw_n1271q7vpp7b9gznc0000gp/T/pip-install-Ch1dUH/isort/
Please note these used to work until yesterday, so some latest code change must have triggered this. Can anyone please look into this? This error is not there in the latest isort package[4.3.5] but it we get this exception for version 4.3.5

**Comment by timothycrosley** [comment]
@nitinsomanitcs  can you try updating setuptools and see if this resolves your issue?

Thanks!

~Timothy

**Comment by dangreenisrael** [comment]
Also being affected by this

**Comment by dangreenisrael** [comment]
If this helps, we were running into an issue where checksums mismatched due to an updated version. We had to kill our lockfile
