### ISSUE TITLE
Parameter install_requires (for futures) removed in 4.3.7 but now back in 4.3.9

### ISSUE THREAD

**Issue by susam** [timothycrosley/isort#853]
There used to be a conditional dependency on the `futures` package that was removed in `isort 4.3.7` but it is now back in `isort 4.3.9`. Is this intentional?

Here is a detailed description of this observation along with links to source code:

  - `isort 4.3.6` has `install_requires=['futures; python_version < "3.2"']` in its `setup.py` ([source][dep 4.3.6]).
  - `isort 4.3.7` does not have `install_requires` in its `setup.py` ([source][dep 4.3.7]).
  - `isort 4.3.8` does not have `install_requires` in its `setup.py` ([source][dep 4.3.8]).
  - `isort 4.3.9` has `install_requires=['futures; python_version < "3.2"']` in its `setup.py` ([source][dep 4.3.9]).

Note: Tags [4.3.7][tag 4.3.7] and [4.3.8][tag 4.3.8] point to the same commit, i.e., commit 7b129bd.

The dependency on `futures` was first removed in commit 3c54c0e: **Make isort run with Python 3 only** ([source][diff]). This commit is present in `develop` but not in `master`.

```
$ git branch --contains 3c54c0e
  develop

$ git merge-base --is-ancestor 3c54c0e develop && echo true || echo false
true

$ git merge-base --is-ancestor 3c54c0e master && echo true || echo false
false
```

Further, this commit was first released in version 4.3.7 but now missing from 4.3.9.

```
$ git merge-base --is-ancestor 3c54c0e 4.3.6 && echo true || echo false
false

$ git merge-base --is-ancestor 3c54c0e 4.3.7 && echo true || echo false
true

$ git merge-base --is-ancestor 3c54c0e 4.3.8 && echo true || echo false
true

$ git merge-base --is-ancestor 3c54c0e 4.3.9 && echo true || echo false
false
```

It has gone missing from 4.3.9 because while 4.3.7 and 4.3.8 were released from `develop` which did have this commit, 4.3.9 was released from `master` which does not have this commit.

```
$ git branch --contains 4.3.7
  develop

$ git branch --contains 4.3.8
  develop

$ git branch --contains 4.3.9
* master

$ git merge-base --is-ancestor 4.3.7 4.3.9 && echo true || echo false
false
```

Generally, one would expect a recent release to contain the commits of earlier releases, but the most recent release, 4.3.9, does not contain the commits of 4.3.7. As a result the commit titled **Make isort run with Python 3 only** which was present in 4.3.7 is no longer present in 4.3.9. Is this intentional?

Reference: I found this while investigating a build failure in cloudmarker/cloudmarker#45. While this is technically not an issue in `isort` and the issue is due to an old version of `setuptools` not handling the dependency `futures; python_version < "3.2"` properly, I still want to check with you if this dependency was brought back into 4.3.9 intentionally.

[dep 4.3.6]: https://github.com/timothycrosley/isort/blob/4.3.6/setup.py#L30
[dep 4.3.8]: https://github.com/timothycrosley/isort/blob/4.3.7/setup.py#L30
[dep 4.3.7]: https://github.com/timothycrosley/isort/blob/4.3.8/setup.py#L30
[dep 4.3.9]: https://github.com/timothycrosley/isort/blob/4.3.9/setup.py#L30

[tag 4.3.7]: https://github.com/timothycrosley/isort/commits/4.3.7
[tag 4.3.8]: https://github.com/timothycrosley/isort/commits/4.3.8
[tag 4.3.9]: https://github.com/timothycrosley/isort/commits/4.3.9

[diff]: https://github.com/timothycrosley/isort/commit/3c54c0e4177b2c92db40161a83397f1b221de57d#diff-2eeaed663bd0d25b7e608891384b7298L29

**Comment by koleror** [comment]
I believe I've got the same issue here when upgrading to 4.3.9 on Python 2.7:
```
Collecting isort==4.3.9 (from -r /home/docker/code/requirements/dev.txt (line 119))
  Downloading https://files.pythonhosted.org/packages/35/c5/025aaa76f0f337e3d91197973c42b4e807fa6dd509da70e87053d85ce278/isort-4.3.9.tar.gz (62kB)
    Complete output from command python setup.py egg_info:
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    error in isort setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected version spec in futures; python_version < "3.2" at ; python_version < "3.2"```

**Comment by timothycrosley** [comment]
If you encounter this issue please update your setuptools and try again - if this does not work please open a new issue. There was a bug in the tags on GitHub that has been resolved.

From issue #857:

Unless I get strong feedback otherwise, I'm going to keep this as invalid and simply require everyone to update their setuptools version - simply because it is not possible to list these optional requirements in a consistent way otherwise when dealing with wheel distribution AFAIK.
@susam, 4.3.7 & 4.3.8 also included the syntax in question, the tags were simply created incorrectly due to a typo on my part. I've updated the tags to be accurate.

Thanks everyone!

~Timothy
