### ISSUE TITLE
Missing isort-4.3.9 wheel package

### ISSUE THREAD

**Issue by jdufresne** [timothycrosley/isort#855]
The latest version of isort on PyPI only has an sdist package. Could you please upload the wheel package as well? Thanks.

**Comment by timothycrosley** [comment]
Thanks for letting me know!

This should be fixed now

~Timothy

**Comment by edmorley** [comment]
Hi! Thank you for uploading the wheel package. Would it be possible to add the wheel step to a script or release process docs to ensure it's created at the same time as the sdist if possible?

It's just that we use the pip hashes feature, and if the wheel is missing at time of original publishing, our dependency bot PR for updating doesn't include the wheel's hash, which later causes failures in development environments and CI when the wheel is published and pip starts favouring it over the sdist.

Many thanks :-)
