### ISSUE TITLE
Current version skips every file on Travis

### ISSUE THREAD

**Issue by JoseKilo** [timothycrosley/isort#873]
This PR #810 added a new check to skip some files/directories considered unsafe by default.

The regex excludes anything with `build` in the path, which usually would be ok.

However, Travis does its job by cloning to `/home/travis/build/`.

This effectively causes every file to be skipped by isort when running on Travis by default.

Using `--unsafe` or `safety_excludes=False` in the config solves the issue.

**Comment by jdufresne** [comment]
I think the solution would be to avoid skipping paths if the path is passed explicitly on the command line. When no path is passed, assume the PWD is explicit. This way `/home/travis/build` wouldn't be checked.

CC @akx

**Comment by kwohlfahrt** [comment]
This also affects the Nix build sandbox, which uses `/build` as it's temporary directory.

**Comment by timothycrosley** [comment]
Should be fixed in this pull request: https://github.com/timothycrosley/isort/pull/878

**Comment by timothycrosley** [comment]
This should be fixed in hotfix release 4.3.11: https://github.com/timothycrosley/isort/releases/tag/4.3.11

Thanks for reporting!

~Timothy
