### ISSUE TITLE
`isort --help` not clear on what is the default behavior

### ISSUE THREAD

**Issue by antoine-gallix** [timothycrosley/isort#879]
By just reading `isort --help`, the command description is not clear on what will the tool do if just invoked against some files. Will it report the errors? Will it output a diff of the changes? Will it change files in place? Will it do it interactively.

I think the first line of the help output should concisely describe what does the command do. The only option left is to try it out, or to read the whole list of options and try to pick out what are the default behaviors.

**Comment by timothycrosley** [comment]
Thanks for this insight! In the latest release, the isort --help documentation describes the default behavior.

Thanks!

~Timothy
