### ISSUE TITLE
PathFinder fails when virtual_env is NoneType

### ISSUE THREAD

**Issue by Embi** [timothycrosley/isort#881]
When virtual_env (/VIRTUAL_ENV) is not set, PathFinder fails:

```
PathFinder encountered an error (expected str, bytes or os.PathLike object, not NoneType) during instantiation and cannot be used
```

which results in all THIRDPARTY imports being recognized as FIRSTPARTY.

The problem is caused by the line added in commit 7834801:

```python
self.virtual_env = os.path.realpath(self.virtual_env)
```

**Comment by timothycrosley** [comment]
This should be fixed in 4.3.12: https://github.com/timothycrosley/isort/releases/tag/4.3.12

Thanks!

~Timothy
