### ISSUE TITLE
Local packages are recognized as third party if virtualenv is not used.

### ISSUE THREAD

**Issue by roman-karpovich** [timothycrosley/isort#887]
latest release changed virtual_env path resolving: https://github.com/timothycrosley/isort/pull/877/commits/7834801b86908974c4acfb81e76b450b268b6551
But, If virtualenv is not used, virtual_env is empty. `os.path.realpath` return current directory for empty string, so in this case current folder is determined as packages home and local packages are recognized as third party.
There are two options to resolve problem:
1 - don't apply realpath to empty string, so old behavior will be returned.
2 - provide correct to config.virtual_env (in my case it was /usr/local

I was able to fix by workaround, provided
`ENV VIRTUAL_ENV /usr/local`
but, as for me, it's wrong way to resolve such things. we shouldn't depend from virtualenv.

**Comment by timothycrosley** [comment]
Hi @roman-karpovich,

Thank you for reporting! A new version of isort has been released that should address this issue. If you still encounter it after updating let me know.

Thanks!

~Timothy
