### ISSUE TITLE
Add support for PyCharm style alphabetic sorting (edited from: all upper cases name is sorted top most)

### ISSUE THREAD

**Issue by yyscamper** [timothycrosley/isort#890]
Below is the sorted result using my isort configuration, you could see the both 'BALL' and `RC` is placed at the top most. The name `Action` is placed below 'BALL' and 'RC' is not correct for me:

```python
from pkg import BALL
from pkg import RC
from pkg import Action
from pkg import Bacoo
from pkg import RCNewCode
from pkg import actual
from pkg import rc
from pkg import recorder
```

What I expected is:
```python
from pkg import Action
from pkg import BALL
from pkg import Bacoo
from pkg import RC
from pkg import RCNewCode
from pkg import actual
from pkg import rc
from pkg import recorder
```

That means following the default python string odering:
```python
>>> 'BALL' < 'RC' < 'Action'
False
>>> 'Action' < 'BALL' < 'RC'
True
```

So I wonder whether there is any configuration can make it?

Below is my isort configuration:
```ini
[isort]
line_length = 80
indent = '  '
force_single_line = True
known_first_party=test
```

**Comment by yyscamper** [comment]
Seems I find the root cause from https://github.com/timothycrosley/isort/issues/370, @timothycrosley replied:
```
When doing from imports isort wants to separate CONSTANTS, Classes, and variables from each-other
```

So whether isort provides any configuration to disable such kind of separation?

**Comment by timothycrosley** [comment]
Hi @yyscamper!

Yes, you can configure this! The default setting which causes this to happen is:

`order_by_type`

which defaults to True. Simply setting order_by_type to False in a config file or doing --dont-order-by-type on the command line should give you the behavior that you want.

Thanks! 

~Timothy

**Comment by timothycrosley** [comment]
Also, you can find a reasonably complete definition of all these settings here: https://github.com/timothycrosley/isort/wiki/isort-Settings.

Thanks!

~Timothy

**Comment by yyscamper** [comment]
this is the result after disabling `order_by_type`,  this order for `Bacoo` and `BALL` is still not correct. Any  reason? @timothycrosley 

```python
from pkg import Action
from pkg import actual
from pkg import Bacoo
from pkg import BALL
from pkg import RC
from pkg import rc
from pkg import RCNewCode
from pkg import recorder
```

**Comment by timothycrosley** [comment]
Currently, when sorting without type ordering, isort ignores the casing of the strings, and gives you a fully alphabetic sort. Is your intention to have an non-typed, but case aware sort?

**Comment by yyscamper** [comment]
@timothycrosley yes, that's what I want. Most people in my team uses PyCharm, this is the default behavior for PyCharm.

**Comment by timothycrosley** [comment]
Hi @yyscamper,

I've added support for this in the lasted version of isort via the case_sensitive setting, as shown in the test uploaded to the pull request:

https://github.com/timothycrosley/isort/pull/892/files#diff-e82bf52c272f12dee456325bfcb553d8R2850

Thanks!

~Timothy

**Comment by yyscamper** [comment]
@timothycrosley I just tested using latest version, it works. Thank for you quick action on this.
