### ISSUE TITLE
Stream reading via pipe no longer working

### ISSUE THREAD

**Issue by timothycrosley** [timothycrosley/isort#895]
After https://github.com/timothycrosley/isort/pull/883 was merged, `<` style sorting was improved but `|` sorting broke completely due to usage of `seek()`

**Comment by KwatME** [comment]
I face the same bug. I think I was able to run the following command with version 4.2.3:
```sh
echo "import os" | isort -
```
I think the community would appreciate it if we could make piping work. I can imagine many developers having the same issue (after they upgrade things).

**Comment by timothycrosley** [comment]
This is fixed in the just release 4.3.15 hot fix release:

https://github.com/timothycrosley/isort/releases/tag/4.3.15

thanks!

~Timothy

**Comment by KwatME** [comment]
Good job @timothycrosley ! And thank you. I'm going to follow you :) Feel free to do the same. I use isort for https://github.com/KwatME/clean_ipynb.
