### ISSUE TITLE
Too broad warning about missing toml package

### ISSUE THREAD

**Issue by gcolombeau** [timothycrosley/isort#902]
The warning about the missing toml package is not restrictive enough in my opinion. At the moment, it is issued every time a ``pyproject.toml`` file is detected even if there is no specific configuration in it for isort. *I don't use the isort package but I use pylint and this behavior adds a lot of noise to the output*.

Would it be possible to improve this by first checking if the toml file contains an uncommented line ``[tool.isort]`` to not issue the warning if one does not want to specify some configuration in this file?

https://github.com/timothycrosley/isort/blob/f76f312abc804fc6bbd2dddf76a11581dda4cb32/isort/settings.py#L342-L354

**Comment by timothycrosley** [comment]
This should be fixed in the latest release: https://github.com/timothycrosley/isort/releases/tag/4.3.16

Thanks!

~Timothy
