### ISSUE TITLE
What is the current status of Python2 support?

### ISSUE THREAD

**Issue by wasilukm** [timothycrosley/isort#904]
Release 4.3.5 suggests that it was the last release for Python2. However even for the recent release py2 packages are still available. Therefore I wonder if Python2 is still officially supported and if it is safe to use releases >4.3.5.

**Comment by timothycrosley** [comment]
Python 2.7 will be officially supported (to run isort) for all 4.x.x releases, all releases. 4.3.5 was the last "feature" release targeting Python2.7, all releases after that have been hot-fix releases - but still target Python 2.

Thanks!

~Timothy
