### ISSUE TITLE
Requires appdirs >= 1.4.0

### ISSUE THREAD

**Issue by edmondsw** [timothycrosley/isort#907]
requirements.txt doesn't currently list a version of appdirs, meaning any version should work. But in fact if you try to use a version of appdirs < 1.4.0 you get `AttributeError: module 'appdirs' has no attribute 'system'`.

**Comment by timothycrosley** [comment]
This should be fixed in the latest release: https://github.com/timothycrosley/isort/releases/tag/4.3.16

Thanks!

~Timothy
