### ISSUE TITLE
isort with same imports but different alieces break imports 

### ISSUE THREAD

**Issue by tbicr** [timothycrosley/isort#908]
just use `isort -rc file` for next kind of imports:

```
from datetime import datetime
import datetime.datetime as dt
```

but got next result:

```
import datetime.datetime as dt
from datetime import datetime as dt
```

eg. `datetime` now unavailable in module

**Comment by timothycrosley** [comment]
This is fixed in develop and will make it's way out in the 5.0.0 release. Thanks!

~Timothy
