### ISSUE TITLE
Add flag for exiting with code 1

### ISSUE THREAD

**Issue by Jihadik** [timothycrosley/isort#914]
In my CI system, before allowing anyone to commit their code, I would like to make sure that all imports are sorted correctly. Usually, CI systems react on exit codes of the commands you specify.

Let's say in `black` there is a `--check` flag which just exits with code `1` in case there are some suggestion. The same thing in `mypy`. Can we introduce something similar in `isort`?

**Comment by timothycrosley** [comment]
Hi @Jihadik,

isort has had a `--check` option for many years, and behaves exactly as you explain :).
