### ISSUE TITLE
New release soon?

### ISSUE THREAD

**Issue by StephenBrown2** [timothycrosley/isort#937]
Any chance of cutting a new release? I'd love to start using the toml fix in a project I'm working on.

**Comment by timothycrosley** [comment]
Sorry for the delay! In that case, I'll have a new release out tonight :),

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
https://github.com/timothycrosley/isort/releases/tag/4.3.18 Took a day longer than I wanted to get in one last fix, but here you go: https://github.com/timothycrosley/isort/releases/tag/4.3.18 :)

Thanks!

~Timothy
