### ISSUE TITLE
Add imports only (without reordering)?

### ISSUE THREAD

**Issue by ferdinand-hoffmann** [timothycrosley/isort#943]
Is it possible to only add an import (like with `isort -a "from __future__ import absolute_import, unicode_literals" …`) without fixing/reordering any other imports in the file(s)?

**Comment by DylanYoung** [comment]
How do you want this to behave?  Should it add the import to the top? or the bottom? Perhaps it needs an additional flag to specify where it's added and whether it's "merged" (for example, if you have other future imports). 

Here's a little script I use for adding future statements, maybe it will get you by for now:

`#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import


import sys
from subprocess import call
from os import path, fsync
from io import open

STANDARD_HEADERS = [
    '# -*- coding: utf-8 -*-',
    'from __future__ import unicode_literals, absolute_import, division',
]
# TODO: turn these into REGEXs
EQUIVALENT_HEADERS = STANDARD_HEADERS + [
    'from __future__ import unicode_literals',
    'from __future__ import absolute_import',
    'from __future__ import division',
    '# coding=utf-8'
]
POST_HEADERS = '\n\n\n'
SEP = '\n'
EOF = '\n'

if __name__ == '__main__':
    for f_name in sys.argv[1:]:
        try:
            with open(f_name, 'r') as f:
                contents = f.read()
            contents = '\n'.join(line for line in contents.split('\n') if line.strip() not in EQUIVALENT_HEADERS).strip('\n')
        except IOError:
            contents = ''

        with open(f_name, 'w+', encoding='utf-8') as f:
            f.write('%s%s%s%s' % (
                SEP.join(STANDARD_HEADERS),
                POST_HEADERS,
                contents,
                EOF)
            )
            fsync(f.fileno())

        #call(['open', f_name])`

**Comment by timothycrosley** [comment]
I can see why you would want this, however due to the complexity in isort already I'm going to view it it as out of scope for isort, as it is an import sorting tool. If anyone believes strongly enough to submit a pull-request I will reconsider.

Thanks!

~Timothy
