### ISSUE TITLE
4.3.19 released from develop branch -- missing SortImports.place_module

### ISSUE THREAD

**Issue by vojtechtrefny** [timothycrosley/isort#947]
It looks like 4.3.19 was (by accident?) from develop branch instead of master so it contains the new compat layer for `SortImports` which is missing some "old"  SortImports API, for example the `place_module` funcion used by pylint:

```
  File "/usr/lib/python3.7/site-packages/pylint/checkers/imports.py", line 507, in leave_module
    std_imports, ext_imports, loc_imports = self._check_imports_order(node)
  File "/usr/lib/python3.7/site-packages/pylint/checkers/imports.py", line 678, in _check_imports_order
    import_category = isort_obj.place_module(package)
AttributeError: 'SortImports' object has no attribute 'place_module'
```

**Comment by timothycrosley** [comment]
Hi @vojtechtrefny, I'm not sure how you are seeing this! If you look on PYPI, https://pypi.org/project/isort/#files and look inside both the wheel and src distributions, they contain a release from the master branch (no _compat and Python2 support still in place.). I've checked and I'm able to install isort 4.3.19 on Python2.7 without issue via pip (meaning it must have been deployed from master as well). Finally, at this point the release is fully automated via travis so I'm not sure how this could happen. Could you look to see if there's any chance develop github is manually be targeted in requirements, or a different package index is being used?

Thanks!

~Timothy

**Comment by vojtechtrefny** [comment]
I am using isort from Fedora package and 4.3.19 tarball they use contains the develop version of isort. I don't know where the Fedora maintainer downloaded it. I'll report a bug for Fedora.
