### ISSUE TITLE
Sorting behaviour seemingly not stable across Python runtimes.

### ISSUE THREAD

**Issue by amcgregor** [timothycrosley/isort#952]
As can be seen in [this Travis-CI test run](https://travis-ci.org/marrow/uri/builds/538758409) the isort checks are [failing only under Pypy runtimes](https://travis-ci.org/marrow/uri/jobs/538758411#L696-L750), despite `known_first_party` [being declared](https://github.com/marrow/uri/blob/develop/setup.cfg#L35-L44).  What have I missed or am doing wrong?

**Comment by timothycrosley** [comment]
This should be fixed for the 5.0.0 release in spirit via this ticket: https://github.com/timothycrosley/isort/issues/1147
