### ISSUE TITLE
Issue with firstparty/local heading when missing

### ISSUE THREAD

**Issue by kingbuzzman** [timothycrosley/isort#953]
My setup.cfg looks like this.
```
[isort]
# Please keep this in sync with flake8
line_length=120
lines_between_types=1
known_third_party=jq
use_parentheses=True
import_heading_stdlib=Standard imports.
import_heading_django=Django imports.
import_heading_thirdparty=Third-party imports.
import_heading_firstparty=Local imports.
known_django=django
sections=FUTURE,STDLIB,DJANGO,THIRDPARTY,FIRSTPARTY,LOCALFOLDER
skip_glob=**/migrations/*
```

I recently came across an issue i hadn't encountered before:

```
# Third-party imports.
from django_filters import filters
from django_filters.rest_framework import BaseInFilter, FilterSet, NumberFilter

from .models import Inbox
```

I understand why it didnt put the header -- because i never gave local any header... BUT is there a way i can give localfolder a header IF firstparty is not present. So it looks like this:

```
# Third-party imports.
from django_filters import filters
from django_filters.rest_framework import BaseInFilter, FilterSet, NumberFilter

# Local imports.
from .models import Inbox
```

And naturaly when there is a firstparty import not to do the heading:

```
# Third-party imports.
from django_filters import filters
from django_filters.rest_framework import BaseInFilter, FilterSet, NumberFilter

# Local imports.
from firstparty import func

from .models import Inbox
```

**Comment by DylanYoung** [comment]
A simple implementation would be a `--dedup-headings` option that if present only includes the heading if it hasn't already been included.  This would be sensible to default to true.

**Comment by DylanYoung** [comment]
@timothycrosley Let me know if this draft implementation works for you and I can get some unit tests up and fix that test failure (unrelated to the implementation).

**Comment by timothycrosley** [comment]
This should be fixed for the 5.0.0 release in spirit via this ticket: https://github.com/timothycrosley/isort/issues/1147

**Comment by kingbuzzman** [comment]
@DylanYoung I see the commit, I see your branch, I don't see a PR, can you make a PR?

**Comment by timothycrosley** [comment]
This is fixed in develop via a new optional `--dedup-headings` config option and will be deployed with the 5.3.0 release.

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
This has now been released to PyPI

Thanks!

~Timothy
