### ISSUE TITLE
"check" mode for integration tests

### ISSUE THREAD

**Issue by nschloe** [timothycrosley/isort#954]
I would like to have something like `isort --check ...` that returns 0 if no changes would be applied, and 1 otherwise.

**Comment by timothycrosley** [comment]
Hi @nschloe,

isort does have such an option :) and even better it is `--check`. You can combine it with `--diff` to show you what isort would change when 1 is passed in.

For example:

```bash
isort --check --diff . -rc
```

Will run isort recursively throughout a project returning 0 if nothing would change and 1 if something would change, while displaying those proposed changes.

Hope this is helpful!

Thanks!

~Timothy
