### ISSUE TITLE
Suggestion for future.standard_library.install_aliases() ?

### ISSUE THREAD

**Issue by ndevenish** [timothycrosley/isort#956]
For one of it's transforms, [futurize](https://github.com/PythonCharmers/python-future) inserts the following lines at the top of the imports, that needs to go before other imports:
```python
from future import standard_library
standard_library.install_aliases()
```
Is there any way to get isort to leave this code line alone? I can get the import to come first with
```
known_compat=future
sections=FUTURE,COMPAT,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER
```
but that obviously still moves the code down. At the moment I'm thinking of putting a custom transform that runs after isort that moves it back up, but if there is an easier way that lets an isort run be idempotent that would be great.

**Comment by timothycrosley** [comment]
This is fixed in develop and will make it's way into isort 5.0.0.
Thanks!

~Timothy
