### ISSUE TITLE
Long aliases and use_parentheses generates invalid syntax

### ISSUE THREAD

**Issue by mattbennett** [timothycrosley/isort#957]
isort with `use_parentheses=True` inserts parens after the `as` if the alias is very long. 

Example:

``` python
from package import module as very_very_very_very_very_very_very_very_very_very_long_alias
```
results in
``` python
from package import (
    module as (
    very_very_very_very_very_very_very_very_very_very_long_alias))
```

This is not valid syntax.

**Comment by EgorChernik** [comment]
The new issue comes))
<pre>from package (
    very_long_module_name as nice_alias,
)</pre>

`line_length` doesn't work anymore with that import-construction.

**Comment by mattbennett** [comment]
@EgorChernik, in ad6af18 you've addressed the second point that I made in my PR: https://github.com/timothycrosley/isort/pull/958

For my usecase (isort combined with black), I actually don't want line-length to be respected in this case. I would argue that the reason `use_parentheses` exists is to avoid backslashes, so it's not completely obvious to me that this is something that needs fixing.

**Comment by timothycrosley** [comment]
@mattbennett Thanks for reporting and fixing this issue!

I've pushed a hot fix release that includes your fix: https://github.com/timothycrosley/isort/releases/tag/4.3.21

@EgorChernik this is a good point, long term it may make sense to have a strict line length enforcement setting, to enable nested wrapping like this.

Thanks!

~Timothy
