### ISSUE TITLE
include_trailing_comma does't work fine enough if inline-comment exists 

### ISSUE THREAD

**Issue by EgorChernik** [timothycrosley/isort#959]
Hi, guys! 
Here is the problem:
Example:
<pre>from pretty_lib import (
    pretty_foo  # turns on God-mode,,,,,,,
)</pre>

Every time I run isort, it adds to the end of the line another comma. I think something goes wrong.
The snippet below, I think should be right.
<pre>from pretty_lib import (
    pretty_foo,  # turns on God-mode
)</pre>

**Comment by timothycrosley** [comment]
This is fixed in develop and will be released in the 5.0.0 release.

Thanks!

~Timothy
