### ISSUE TITLE
Respect .gitignore

### ISSUE THREAD

**Issue by fpuga** [timothycrosley/isort#960]
To avoid (miss)configurations it will be awesome that `isort` ignore by default the patterns set in `.gitignore`.

Other projects like black [are also thinking](https://github.com/python/black/issues/475) on doing it.

**Comment by mdagaro** [comment]
I'm interested in taking up this issue if it's okay @timothycrosley

**Comment by timothycrosley** [comment]
@mdagaro, it would be very appreciated, thank you!

**Comment by timothycrosley** [comment]
This is implemented in the develop branch (Thanks @mdagaro!) and will be deployed with the 5.2.0 minor release.

**Comment by timothycrosley** [comment]
This was just deployed with version 5.2.0 of isort. Thanks! 

~Timothy
