### ISSUE TITLE
Don't process invalid syntax

### ISSUE THREAD

**Issue by ppwwyyxx** [timothycrosley/isort#962]
```
╰─$cat a.py                                                                                                                                                                                              
from A import (
    func,
    gunc,
from B import junc
from C import kunc
╰─$isort a.py
Fixing /home/xx/a.py
╰─$cat a.py                                                                                                                                                                                                  
from A import B, C, from, func, gunc, import, junc, kunc
```

I hope that isort can leave the imports as-is when it has syntax errors (or better, report the errors).
My file has a lot of imports and it is messed up quite hard by isort, due to an unclosed brace.

**Comment by timothycrosley** [comment]
Hi @ppwwyyxx,

I believe isort provides the functionality you desire via the atomic flag:  

`isort --atomic a.py`

From the documentation:

Finally, to atomically run isort against a project, only applying changes if they don't introduce syntax errors do:

```
isort -rc --atomic .
```

(Note: this is disabled by default as it keeps isort from being able to run against code written using a different version of Python)

Let me know if this addresses your concern!

Thanks!

~Timothy

**Comment by ppwwyyxx** [comment]
Thanks for the quick response! This resolves the issue!
