### ISSUE TITLE
Strange version 4.3.21-2

### ISSUE THREAD

**Issue by decaz** [timothycrosley/isort#966]
I don't know why but these files are different:
- https://github.com/timothycrosley/isort/blob/4.3.21/.pre-commit-hooks.yaml
- https://github.com/timothycrosley/isort/blob/4.3.21-2/.pre-commit-hooks.yaml

**Comment by StephenBrown2** [comment]
Seconded. When running `pre-commit autoupdate`, it _always_ thinks isort is out of date, and flips between the two versions `4.3.21` and `4.3.21-2`.

Could we get a minor version bump to `4.3.22` and resolve the `.pre-commit-hooks.yaml` difference?

**Comment by StephenBrown2** [comment]
Bumping this, hoping the hotfix change can be released as `4.3.22`, though I know not much activity has happened here recently.

**Comment by timothycrosley** [comment]
Closing this as it's been a long time, and now isort 5.0.0 has been released and is correctly tagged.
