### ISSUE TITLE
not_ settings not working on python 3

### ISSUE THREAD

**Issue by gazpachoking** [timothycrosley/isort#967]
When defining not_known_standard_library = ['builtins'], this doesn't actually get removed from the list of builtins on python 3. This is because the `_as_list` function returns a `filter` object, which is an iterator (on python 3), and can only be looped through once. This seems to be fixed in the latest source code, as the filter function in _as_list has been replaced by a list comprehension, however the version released on pypi (4.3.21) is still using the filter function in _as_list. Seems like it's just a problem with the release, as the git tag 4.3.21 has the bug fixed.

**Comment by gazpachoking** [comment]
I've just noticed there is a 4.3.21-2 tag in the git repo, which has the problematic `filter`:
https://github.com/timothycrosley/isort/blob/4.3.21-2/isort/settings.py#L268

Whereas the 4.3.21 does not, and therefore does not contain this bug:
https://github.com/timothycrosley/isort/blob/4.3.21/isort/settings.py#L325

**Comment by timothycrosley** [comment]
Marking this as closed in preparation for the 5.0.0 release which has this issue resolved.

Thanks!

~Timothy
