### ISSUE TITLE
Extra line between imports & top-level defs (constants)

### ISSUE THREAD

**Issue by houzefa-abba** [timothycrosley/isort#968]
Given the following:

```python
from aaa import bbb


MY_DEF_1 = "foo"
MY_DEF_2 = "bar"


class SomeClass(object):
    pass
```

`isort` removes 1 empty line between imports & top-level defs.

`black` accepts both 1 empty line or 2 empty lines (but of course, 3 empty lines get folded back to 2 empty lines).

I would love to consistently have these 2 empty lines before my defs.
Thanks

**Comment by timothycrosley** [comment]
isort follows pep8 on this, while also allowing it to be configured. Discrepencies with black have been resolved.
