### ISSUE TITLE
Support google style guide

### ISSUE THREAD

**Issue by peteboothroyd** [timothycrosley/isort#969]
The [google python style guide](https://github.com/google/styleguide/blob/gh-pages/pyguide.md) suggests enforcing one import per line which can be achieved with the `force_single_line` option. However they also suggest an [exception](https://github.com/google/styleguide/blob/gh-pages/pyguide.md#31912-imports-for-typing) for the `typing` module. I can't find any way of specifying this to isort, does it exist? If not would it be much effort to implement? I imagine that a nice way of doing this would be to allow specifying certain packages as overrides for the `force_single_line` rule.

**Comment by timothycrosley** [comment]
This is now supported in develop and will make it's way into the 5.0.0 release:

https://github.com/timothycrosley/isort/blob/develop/isort/profiles.py#L22

Thanks!

~Timothy

**Comment by peteboothroyd** [comment]
awesome, thank you very much!
