### ISSUE TITLE
Wrap length taking number as string

### ISSUE THREAD

**Issue by jaswanth098** [timothycrosley/isort#971]
Ref: https://github.com/timothycrosley/isort/blob/develop/isort/main.py#L287
I have been trying to wrap_length, but isort throws the following error and quits
```bash
TypeError: '>' not supported between instances of 'str' and 'int'
```

**Comment by jaswanth098** [comment]
I have found the problem 
Ref: https://github.com/timothycrosley/isort/blob/develop/isort/main.py#L287

**Comment by Zarathustra2** [comment]
@jaswanth098 @timothycrosley This can be closed as PR has been merged!

**Comment by jaswanth098** [comment]
Yes, can be closed @Zarathustra2 closing it

**Comment by jaswanth098** [comment]
When will be the nearest release?
