### ISSUE TITLE
from __future__ imports must occur at the beginning of the file

### ISSUE THREAD

**Issue by kiilerix** [timothycrosley/isort#973]
```
$ ( echo 'a = 1'; echo 'import os' ) > a.py && isort -a "from __future__ import absolute_import" a.py && nl -ba a.py && flake8 a.py 
Fixing /home/mk/kallithea/a.py
     1	a = 1
     2	from __future__ import absolute_import
     3	
     4	import os
a.py:2:1: F404 from __future__ imports must occur at the beginning of the file
```

I have no strong opinion on whether imports generally should come before or after such assignments, but it seems like future imports should be forced up.

Using
flake8==3.7.8
isort==4.3.21

**Comment by mdagaro** [comment]
https://docs.python.org/2/reference/simple_stmts.html#future

A future statement must appear near the top of the module. The only lines that can appear before a future statement are:
* the module docstring (if any),
* comments,
* blank lines, and
* other future statements.

It looks like python thinks it should be. It looks like this isn't explicitly enforced though.

**Comment by r3m0t** [comment]
isort is also sorting ``from __future__ import ..`` to be after ``import __future__``, but Python requires it to be before.

**Comment by timothycrosley** [comment]
I'm going to close this now, as isort has explicitly switched to a streaming approach, where it never changes where in your file imports are, just the ordering where they are already placed.
